### ISSUE TITLE
Some badssl tests fail on Windows (-msvc)

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#100]
failures:
    online::many_sans
    online::mozilla_inter
    online::mozilla_modern
    online::mozilla_old
    online::rsa8192
    online::sha256
    online::too_many_sans

<details>
---- online::many_sans stdout ----
        We expected to find '<title>1000-sans.badssl.com</title>' in the following output:
Output { status: ExitStatus(ExitStatus(1)), stdout: "TLS read error: Err(Error { repr: Os { code: 10035, message: \"A non-blocking socket operation could not be completed immediately.\" } })\nConnection closed\n", stderr: "" }
thread 'online::many_sans' panicked at 'Test failed', tests\common\mod.rs:278
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- online::mozilla_modern stdout ----
        We expected to find '<title>mozilla-modern.badssl.com</title>' in the following output:
Output { status: ExitStatus(ExitStatus(1)), stdout: "TLS read error: Err(Error { repr: Os { code: 10035, message: \"A non-blocking socket operation could not be completed immediately.\" } })\nConnection closed\n", stderr: "" }
thread 'online::mozilla_modern' panicked at 'Test failed', tests\common\mod.rs:278

---- online::mozilla_inter stdout ----
        We expected to find '<title>mozilla-intermediate.badssl.com</title>' in the following output:
Output { status: ExitStatus(ExitStatus(1)), stdout: "TLS read error: Err(Error { repr: Os { code: 10035, message: \"A non-blocking socket operation could not be completed immediately.\" } })\nConnection closed\n", stderr: "" }
thread 'online::mozilla_inter' panicked at 'Test failed', tests\common\mod.rs:278

---- online::sha256 stdout ----
        We expected to find '<title>sha256.badssl.com</title>' in the following output:
Output { status: ExitStatus(ExitStatus(1)), stdout: "TLS read error: Err(Error { repr: Os { code: 10035, message: \"A non-blocking socket operation could not be completed immediately.\" } })\nConnection closed\n", stderr: "" }
thread 'online::sha256' panicked at 'Test failed', tests\common\mod.rs:278

---- online::too_many_sans stdout ----
        We expected to find 'TLS error: CorruptMessagePayload\(Handshake\)' in the following output:
Output { status: ExitStatus(ExitStatus(1)), stdout: "TLS read error: Err(Error { repr: Os { code: 10035, message: \"A non-blocking socket operation could not be completed immediately.\" } })\nConnection closed\n", stderr: "" }
thread 'online::too_many_sans' panicked at 'Test failed', tests\common\mod.rs:278

---- online::rsa8192 stdout ----
        We expected to find '<title>rsa8192.badssl.com</title>' in the following output:
Output { status: ExitStatus(ExitStatus(1)), stdout: "TLS read error: Err(Error { repr: Os { code: 10035, message: \"A non-blocking socket operation could not be completed immediately.\" } })\nConnection closed\n", stderr: "" }
thread 'online::rsa8192' panicked at 'Test failed', tests\common\mod.rs:278

---- online::mozilla_old stdout ----
        We expected to find '<title>mozilla-old.badssl.com</title>' in the following output:
Output { status: ExitStatus(ExitStatus(1)), stdout: "TLS read error: Err(Error { repr: Os { code: 10035, message: \"A non-blocking socket operation could not be completed immediately.\" } })\nConnection closed\n", stderr: "" }
thread 'online::mozilla_old' panicked at 'Test failed', tests\common\mod.rs:278

failures:
    online::many_sans
    online::mozilla_inter
    online::mozilla_modern
    online::mozilla_old
    online::rsa8192
    online::sha256
    online::too_many_sans

test result: FAILED. 7 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out
</details>

This test has been broken this way on Windows since at least 0dd525601a70b15675f77a851d7a500456964def, which is the earliest version that I can easily test.

**Comment by ctz** [comment]
We now regularly run tests on Windows thanks to azure.
