### ISSUE TITLE
Lower handshake log level

### ISSUE THREAD

**Issue by pjhades** [ctz/rustls#105]
Hello! We get a lot of handshake log output like:

```
Server cert is [Certificate([48, 130, 3, 94, 48, 130, 2, ....
```

Personally I do not see any usefulness in printing the certificate as you can basically do nothing with it. (I may be wrong.) Is it possible to change this output from `info!` to `debug!`? If yes I'll send a quick PR.

**Comment by ctz** [comment]
I think this was done by #121
