### ISSUE TITLE
Using rustls synchronously

### ISSUE THREAD

**Issue by inejge** [ctz/rustls#12]
When adapting hyper with blocking I/O to use rustls (for rustup's SSL stream adapter) I had to:

1. [Modify `wants_read()`](https://github.com/inejge/rustls/commit/3b97e2018ca103a7d98691a7c6c97a097c82da96) to return `false` when there's unconsumed plaintext content in the buffer;

2. [Check `wants_write()`](https://github.com/inejge/rustup.rs/commit/761a6bc46cafc30863a3e51f3d011fb5631d053c) immediately after processing input packets, without which the initial protocol negotiation wouldn't finish.

With these modifications, rustup + hyper + rustls works fine in the limited testing I've put it through. What I'd like to know is a) whether the change in (1.) above is acceptable, or maybe some other function could be added to inquire about rustls' plaintext buffer status, and b) does (2.) hide some nasty surprise in the face of protocol errors and the like.

**Comment by ctz** [comment]
1. The original idea of `wants_read` was to have this precise behaviour: so that there was a degree of back-pressure from a neglected plaintext buffer to the socket. So, thanks for that.

2. I think that's OK. Rustls does not asynchronously send packets to the peer; everything it does is driven from received data or other API calls. So there's no chance of you blocking in read (say) causing non-delivery of other data.

**Comment by inejge** [comment]
Excellent, thanks. I'll close this issue and update my PR for rustls support in rustup.

**Comment by Philipp91** [comment]
I think a code sample how to use rustls with synchronous socket APIs (like hyper or std::net::TcpStream) would be useful. From the rustup code linked above, I managed to put together this loop:
```
let rc_config = Arc::new(config);
let mut client = rustls::ClientSession::new(&rc_config, "example.com");
let mut stream = TcpStream::connect("example.com:443").unwrap();
client.write(b"GET / HTTP/1.0\r\n\r\n").unwrap();
client.write_tls(&mut stream).unwrap();

loop {
    while client.wants_read() {
        client.read_tls(&mut stream).unwrap();
        client.process_new_packets().unwrap();
        while client.wants_write() {
            client.write_tls(&mut stream).unwrap();
        }
    }

    let plaintext = read(&mut client).unwrap();
    println!("Read: {}", String::from_utf8(plaintext).unwrap());
}
const BLOCK_SIZE: usize = 128;

fn read(stream: &mut std::io::Read) -> std::io::Result<Vec<u8>> {
    let mut result = Vec::new();
    let mut buf = [0; BLOCK_SIZE];
    loop {
        let bytes = try!(stream.read(&mut buf));
        if bytes < BLOCK_SIZE {
            result.append(&mut buf[..bytes].to_vec());
            return Ok(result);
        }
        result.append(&mut buf.to_vec());
    }
}
```

This code has the following issues:

1. Sometimes (maybe when the server responds too slowly or quickly?) the read function fails with an error before receiving the response: `Error { repr: Custom(Custom { kind: ConnectionAborted, error: StringError("CloseNotify alert received") }) }`. On my machine, this happens with https://httpbin.org/encoding/utf8.
2. After receiving the response, it may loop infinitely. This happens with https://httpbin.org/ip.
3. It needs this `read` helper function. Maybe there is a way to avoid that and use a built-in function?
