### ISSUE TITLE
Is it possible to use self-signed certs?

### ISSUE THREAD

**Issue by wafflespeanut** [ctz/rustls#124]
Hi! I was experimenting with rustls for HTTP + TLS server. I tried using self-signed certs, but I was unable to set it up properly.

So, I generate a key, a cert request and then I sign the cert.

``` bash
openssl genrsa -out server.key 4096
openssl req -new -key server.key -out csr.pem
openssl x509 -req -days 7300 -in csr.pem -signkey server.key -out server.crt
```

In the code, I have something like this,

``` rust
let certs = pemfile::certs(&mut reader).unwrap();
/// `reader` for private key
let mut keys = pemfile::rsa_private_keys(&mut reader).unwrap();
keys.truncate(1);
let pkey = keys.pop().unwrap();

let store = RootCertStore::empty();
let verifier = AllowAnyAnonymousOrAuthenticatedClient::new(store);
let mut tls_config = ServerConfig::new(verifier);
tls_config.set_single_cert(certs, pkey);
```

Then, I use `tokio-rustls` for serving requests. But, whenever I get the requests, I get an internal error (during client hello). Debugging showed that the execution stops [here](https://github.com/ctz/rustls/blob/db74024411fe56c52f7c46e5e0a1ae0bdff0cd22/src/server/hs.rs#L913). The cert gets rejected because it's invalid. Am I doing something wrong? Or, if this is the way it's supposed to work, then how can we make use of self-signed certs?

Thanks.

**Comment by wafflespeanut** [comment]
cc @briansmith

**Comment by briansmith** [comment]
Instead of using a self-signed cert, I would generate a root CA cert, then have that root CA issue a end-entity cert, and then configure the client to trust the root CA. The same effect, only slightly more work, and much closer to what a production deployment of these things would do.

**Comment by wafflespeanut** [comment]
Ok cool. I was just wondering whether we'd be able to use self-signed certs. Thanks 😄

**Comment by Darkspirit** [comment]
https://sourceforge.net/projects/xca/files/xca/1.3.2/ or https://packages.debian.org/stretch/xca
But don't forget to set a SAN (your command didn't include one).

**Comment by wafflespeanut** [comment]
@briansmith Btw, just asking - would it cause any trouble if accepting self-signed certs were a feature? Almost all the libs I know of (in other lang like Python, Node, Java, etc.) support self-signed certs.

**Comment by briansmith** [comment]
@wafflespeanut I think you can plug a custom certificate verifier into Rustls that accepts self-signed certificates. Not sure though.

**Comment by briansmith** [comment]
> Then, I use tokio-rustls for serving requests. But, whenever I get the requests, I get an internal error (during client hello). Debugging showed that the execution stops here. The cert gets rejected because it's invalid.

Is the certificate a syntactically-valid version 3 X.509 end-entity (basicConstraints.cA isn't set) certificate with a subjectAltName extension (that contains the hostname as a dNSName, if SNI is used)?

**Comment by wafflespeanut** [comment]
Oh, looks like x509 v3 with SAN works! Might be worth mentioning in the docs? 😄
