### ISSUE TITLE
Handshake fails with BadDER

### ISSUE THREAD

**Issue by P-E-Meunier** [ctz/rustls#127]
Hi!

My Tokio-based PostgreSQL crate https://nest.pijul.com/pmeunier/pleingres was originally based on Rustls, but I couldn't connect to a Google Cloud PostgreSQL database.

I replaced tokio-rustls with tokio-openssl, and it started working.

The error originated from webpki, and was BadDER. The CA certificate was from Google, and there was no other DER-encoded file involved (besides what's in webpki-roots maybe?).

Now that I got a working version, I can reproduce that bug if needed. With OpenSSL, I needed a function that doesn't check the hostname (the host I want to connect to has no hostname and is supposed to be accessed by its IP address).

**Comment by P-E-Meunier** [comment]
The strange thing though, is that rustls doesn't complain when adding the certificate (`add_pem_file()`), it crashes during the negotiation.

The certificate is
```
-----BEGIN CERTIFICATE-----
MIIDITCCAgmgAwIBAgIBADANBgkqhkiG9w0BAQUFADBIMSMwIQYDVQQDExpHb29n
bGUgQ2xvdWQgU1FMIFNlcnZlciBDQTEUMBIGA1UEChMLR29vZ2xlLCBJbmMxCzAJ
BgNVBAYTAlVTMB4XDTE3MTAyNzE0NTAwNVoXDTE5MTAyNzE0NTEwNVowSDEjMCEG
A1UEAxMaR29vZ2xlIENsb3VkIFNRTCBTZXJ2ZXIgQ0ExFDASBgNVBAoTC0dvb2ds
ZSwgSW5jMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAL/4CZtILHnNHrYpoTTgTQdWLT8l4gT4XBN4p+usg6g+8LwBwj/X8EPvH6rN
EcKt9yIIrVjooFEWjLMeQAwDHuUWATRpzLfE63J8uQDq4CgUFkkrhx/3FA+iKP96
wNB8F+BcxG3Fg5jWQ4ZNxJUYhXm+VNOu6pftyIVstrTzAs/E7+P50zcmjeXpattF
yeIIb9xmE7Kzs3YBp9QvzlE/KZ4xv3CuGNzjSE28E3OsNw02fhobxMX6MLQIkrWu
pkidtH7s4QgIgad/mt60+KPU5Naj8rZZ2H3ldgtmhPvNkuGjMvXX9K9ZRV/GIWtD
L/nYW/7N+QgIKI8WzBXL6OV7jesCAwEAAaMWMBQwEgYDVR0TAQH/BAgwBgEB/wIB
ADANBgkqhkiG9w0BAQUFAAOCAQEAnOg3pYPnFkYhIzrMtFnfnJl9AkrIdYngiaOF
npDB+UD4+QR4TpOIlrS7Fm4h6NCKjniKYg6vnflbiIk5V5kcQvCcx06jlhvIbCGb
M3H8w/4vFHhf4FkQeEtagUCrVdsK1mxNMdhCvB3z3G0seS7cOu07R8fzKdVV5JWo
SQfiDxPmGtjR8rJ1j0s811YQTYgWU3GGe8hsj0rfeFPtyxexRoUKxbeBfWs0sfs9
OU+6L0sRojBMN+dlnFGaOXZs990bCJyvU2LoY4azZF+hcQwK8TC2U/8ZxEr9vxAU
W5DlWUCcYAYlVH3QiFao9y1CKNe/t1aUf9X/d4wPxZUG2p+/dQ==
-----END CERTIFICATE-----
```

**Comment by briansmith** [comment]
> the host I want to connect to has no hostname and is supposed to be accessed by its IP address

Does its certificate have an subjectAltName/iPAddress? If not, how do you validate its identity? What *is* its identity?

**Comment by briansmith** [comment]
> -----BEGIN CERTIFICATE-----
> MIIDITCCAgmgAwIBAgIBADANBgkqhkiG9w0BAQUFADBIMSMwIQYDVQQDExpHb29n
> bGUgQ2xvdWQgU1FMIFNlcnZlciBDQTEUMBIGA1UEChMLR29vZ2xlLCBJbmMxCzAJ
> BgNVBAYTAlVTMB4XDTE3MTAyNzE0NTAwNVoXDTE5MTAyNzE0NTEwNVowSDEjMCEG
> A1UEAxMaR29vZ2xlIENsb3VkIFNRTCBTZXJ2ZXIgQ0ExFDASBgNVBAoTC0dvb2ds
> ZSwgSW5jMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
> ggEBAL/4CZtILHnNHrYpoTTgTQdWLT8l4gT4XBN4p+usg6g+8LwBwj/X8EPvH6rN
> EcKt9yIIrVjooFEWjLMeQAwDHuUWATRpzLfE63J8uQDq4CgUFkkrhx/3FA+iKP96
> wNB8F+BcxG3Fg5jWQ4ZNxJUYhXm+VNOu6pftyIVstrTzAs/E7+P50zcmjeXpattF
> yeIIb9xmE7Kzs3YBp9QvzlE/KZ4xv3CuGNzjSE28E3OsNw02fhobxMX6MLQIkrWu
> pkidtH7s4QgIgad/mt60+KPU5Naj8rZZ2H3ldgtmhPvNkuGjMvXX9K9ZRV/GIWtD
> L/nYW/7N+QgIKI8WzBXL6OV7jesCAwEAAaMWMBQwEgYDVR0TAQH/BAgwBgEB/wIB
> ADANBgkqhkiG9w0BAQUFAAOCAQEAnOg3pYPnFkYhIzrMtFnfnJl9AkrIdYngiaOF
> npDB+UD4+QR4TpOIlrS7Fm4h6NCKjniKYg6vnflbiIk5V5kcQvCcx06jlhvIbCGb
> M3H8w/4vFHhf4FkQeEtagUCrVdsK1mxNMdhCvB3z3G0seS7cOu07R8fzKdVV5JWo
> SQfiDxPmGtjR8rJ1j0s811YQTYgWU3GGe8hsj0rfeFPtyxexRoUKxbeBfWs0sfs9
> OU+6L0sRojBMN+dlnFGaOXZs990bCJyvU2LoY4azZF+hcQwK8TC2U/8ZxEr9vxAU
> W5DlWUCcYAYlVH3QiFao9y1CKNe/t1aUf9X/d4wPxZUG2p+/dQ==
> -----END CERTIFICATE-----

If I am reading correctly, this certificate is a CA certificate, not an end-entity certificate. Where's the end-entity certificate?

**Comment by P-E-Meunier** [comment]
I guess it's signed by the CA certificate when handshaking.
I don't know how I'm supposed to validate the server's identity, I (naively) thought it was the only certificate signed by that CA certificate.

**Comment by briansmith** [comment]
> I guess it's signed by the CA certificate when handshaking.
> I don't know how I'm supposed to validate the server's identity, I (naively) thought it was the only certificate signed by that CA certificate.

There must be some miscommunication here as I doubt Google set it up to use a CA certificate as an end-entity certificate. Can you use `openssl s_client -showcerts -connect example.com:443`  to connect to the server, and then attach the complete cert chain here?

**Comment by P-E-Meunier** [comment]
I meant "I guess the certificate is signed by that CA certificate", which I realise does not contain much information.

So, that openssl command doesn't work for me, since TLS in the Postgres protocol comes after a few binary commands. Is there anything I can do with the openssl crate or the rustls crate to do this?

**Comment by briansmith** [comment]
If it were me, I would use Wireshark and extract the certs out of the pcap, or at least just share the pcap for that one connection.

**Comment by jbg** [comment]
I had the same problem. There's a script [here](https://github.com/thusoy/postgres-mitm/blob/master/postgres_get_server_cert.py) that can fetch the server certificate from a PostgreSQL server.

My Google Cloud SQL instance gives back a version 3 certificate. The CN looks like `abc-1234:def` where `abc-1234` is the Google Cloud "project name" and `def` is the Cloud SQL instance name. There is no subjectAltName extension.

**Comment by briansmith** [comment]
> My Google Cloud SQL instance gives back a version 3 certificate. The CN looks like abc-1234:def where abc-1234 is the Google Cloud "project name" and def is the Cloud SQL instance name. There is no subjectAltName extension.

I suggest you file a bug with Google telling them that their system[1] is terrible and they need to improve it.

[1] https://cloud.google.com/sql/docs/mysql/configure-ssl-instance

**Comment by jbg** [comment]
I can absolutely contact them regarding this. Do you by any chance have links to relevant RFCs/documents indicating that their CN is invalid and/or that subjectAltName is a required extension?

From some basic research it seems that their CN is valid according to X.509, but I imagine there may be more specific standards relating to X.509 as used in a TLS context.

**Comment by jbg** [comment]
I found RFC6125, but it should be noted that this RFC suggests to "move away from including and checking strings that look like domain names in the subject's Common Name" and to move toward SAN for that purpose. It doesn't seem to make any recommendations regarding moving away from the use of CN when it does not contain something that looks like a domain name (e.g. some domain-specific identifier defined in the context of an internal PKI).

There are many "internal" uses of PKI that do not use DNS. The "abc-1234:def" string above is a reasonable domain-specific identifier for the thing I'm connecting to, and seems to be valid as a CN of an X.509 certificate, so it seems to me that a suitably flexible TLS library would allow me to verify and accept a properly-signed certificate containing this CN.

Is this outside of the scope of webpki though? (Especially given the "web" in "webpki".) And if so, should that also limit the scope of rustls?

**Comment by briansmith** [comment]
Rustls also has a way to plug in custom certificate verification, so you can verify such certificates using some other certificate verification code that implements whatever the GCP semantics are.

**Comment by jbg** [comment]
I tried to use that, but even with a certificate verifier that always returns success, the BadDER error still happens. It seems that webpki can't parse the certificate at all and this failure happens before the certificate verifier is called.

**Comment by kelnos** [comment]
I _think_ I'm running into this as well.  I'm using `rumqtt`, a rust MQTT client.  I get `BadDER` even when I don't pass client certificates, but only pass the system's CA cert file (`/etc/ssl/certs/ca-certificates.crt`) as the trusted CA store, which seems like something that should work, no?  (I also get the same error when I pass a CA of my own making.)

`rumqtt` isn't using the latest `rustls` (0.15.2) which is not using the latest webpki (0.19.1), so I figure that could be a factor as well.  Not sure it's worth cloning the `rumqtt` source and bumping deps to see if upgrading helps.

**Comment by mleonhard** [comment]
I also ran into this with a self-signed cert.  You can reproduce the error with the program below and a certificate with only a Common Name entry:
```
$ openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -out localhost.cert -keyout localhost.key -subj '/CN=localhost'
Generating a 2048 bit RSA private key
........................................+++
...............................................+++
writing new private key to 'localhost.key'
-----
$ cargo run
INFO server listening on 127.0.0.1:1690
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: WebPKIError(BadDER) }', src/main.rs:87:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "tls handshake eof" }', src/main.rs:67:72
```


The workaround for self-signed certificates is to add Subject Alternative Name entries.  There are two ways to do it:

1. Use a newer version of OpenSSL which accepts multiple `-addext 'subjectAltName = DNS:localhost'` parameters.
   See:
   - [Provide subjectAltName to openssl directly on the command line](https://security.stackexchange.com/a/183973).
1. Put the SAN values in an `openssl.cfg` file and pass the `-config openssl.cfg` parameter to the `openssl` command.
   This works on MacOS 10.15.6 which has an `openssl` command from LibreSSL 2.8.3.
   See:
   - [PKCS#10 certificate request and certificate generating utility](https://www.openssl.org/docs/man1.1.1/man1/req.html)
   - [X509 V3 certificate extension configuration format](https://www.openssl.org/docs/man1.1.1/man5/x509v3_config.html)

Here's how to use `openssl.cfg`:
```
$ openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -out localhost.cert -keyout localhost.key -subj '/CN=localhost' -config openssl.cfg
Generating a 2048 bit RSA private key
..............................................+++
........................+++
writing new private key to 'localhost.key'
-----
$ cargo run
INFO server listening on 127.0.0.1:1690
INFO client read "response"
```

```
# openssl.cfg
[req]
distinguished_name=dn
x509_extensions=ext
[ dn ]
CN=localhost
[ ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
IP.1 = 127.0.0.1
IP.2 = ::1
```

Example program:
```
# Cargo.toml
[package]
name = "example"
version = "0.1.0"
edition = "2018"

[dependencies]
pem = "0.8"
rustls = {version = "0.18", features = ["dangerous_configuration"]}
tokio = {version = "0.2", features = ["full"]}
tokio-rustls = "0.14"
webpki = "0.21"
```

```rust
// src/main.rs
// This program shows how to use TLS with certificate pinning.

use std::println;
use std::sync::Arc;

/// AcceptSpecificCertsVerifier implements certificate pinning.
/// 
/// The rustls library has an open issue to add something like this:
/// "Implement support for certificate pinning" https://github.com/ctz/rustls/issues/227
struct AcceptSpecificCertsVerifier {
    certs: Vec<rustls::Certificate>,
}

impl rustls::ServerCertVerifier for AcceptSpecificCertsVerifier {
    fn verify_server_cert(
        &self,
        _roots: &rustls::RootCertStore,
        presented_certs: &[rustls::Certificate],
        _dns_name: webpki::DNSNameRef,
        _ocsp_response: &[u8],
    ) -> Result<rustls::ServerCertVerified, rustls::TLSError> {
        let presented_cert = &presented_certs[0];
        for cert in &self.certs {
            if presented_cert == cert {
                return Ok(rustls::ServerCertVerified::assertion());
            }
        }
        return Err(rustls::TLSError::WebPKIError(webpki::Error::UnknownIssuer));
    }
}

fn arbitrary_dns_name() -> webpki::DNSName {
    webpki::DNSNameRef::try_from_ascii_str("arbitrary1")
        .unwrap()
        .to_owned()
}

async fn async_main() -> () {
    let cert_pem_bytes = tokio::fs::read("localhost.cert").await.unwrap();
    let cert_pem = pem::parse(cert_pem_bytes).unwrap();
    assert_eq!(cert_pem.tag, "CERTIFICATE");
    let cert = rustls::Certificate(cert_pem.contents);

    let key_pem_bytes = tokio::fs::read("localhost.key").await.unwrap();
    let key_pem = pem::parse(key_pem_bytes).unwrap();
    let key = rustls::PrivateKey(key_pem.contents);
    assert_eq!(key_pem.tag, "PRIVATE KEY");

    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 1690));
    let mut listener = tokio::net::TcpListener::bind(&addr).await.unwrap();
    println!(
        "INFO server listening on {}",
        listener.local_addr().unwrap()
    );

    let mut server_config = rustls::ServerConfig::new(rustls::NoClientAuth::new());
    server_config
        .set_single_cert(vec![cert.clone()], key)
        .unwrap();
    let server_config_arc = Arc::new(server_config);

    tokio::spawn(async move {
        let tls_acceptor = tokio_rustls::TlsAcceptor::from(server_config_arc);
        loop {
            let (tcp_stream, _addr) = listener.accept().await.unwrap();
            let mut tls_stream = tls_acceptor.accept(tcp_stream).await.unwrap();
            use tokio::io::AsyncWriteExt;
            if let Err(e) = tls_stream.write_all(b"response").await {
                println!("WARN server write error: {:?}", e);
                return;
            }
        }
    });

    let mut client_config = rustls::ClientConfig::new();
    client_config
        .dangerous()
        .set_certificate_verifier(Arc::new(AcceptSpecificCertsVerifier { certs: vec![cert] }));
    let tls_connector = tokio_rustls::TlsConnector::from(Arc::new(client_config));
    let tcp_stream = tokio::net::TcpStream::connect("127.0.0.1:1690")
        .await
        .unwrap();
    let mut tls_stream = tls_connector
        .connect(arbitrary_dns_name().as_ref(), tcp_stream)
        .await
        .unwrap();
    use tokio::io::AsyncReadExt;
    let mut buf = String::new();
    if let Err(e) = tls_stream.read_to_string(&mut buf).await {
        println!("WARN client read error: {:?}", e);
        return;
    }
    println!("INFO client read {:?}", buf);
}

pub fn main() {
    let mut runtime = tokio::runtime::Builder::new()
        .threaded_scheduler()
        .enable_all()
        .build()
        .unwrap();
    runtime.block_on(async_main());
    runtime.shutdown_background();
}
```

**Comment by mleonhard** [comment]
Here's how the error occurs:
1. [`ExpectCertificateVerify::handle()`](https://github.com/ctz/rustls/blob/748341d49af8e24a80eb9bd40437e92ffa1a4850/rustls/src/client/tls13.rs#L565) first calls the configured `ServerCertVerifier::verify_server_cert()` to check the cert.
1. Then it calls [`ServerCertVerifier::verify_tls13_signature()`](https://github.com/ctz/rustls/blob/748341d49af8e24a80eb9bd40437e92ffa1a4850/rustls/src/verify.rs#L123)
1. which calls [`verify_tls13()`](https://github.com/ctz/rustls/blob/748341d49af8e24a80eb9bd40437e92ffa1a4850/rustls/src/verify.rs#L528)
1. which calls [`webpki::EndEntityCert::from()`](https://github.com/briansmith/webpki/blob/8b741a41a14428b996886b4ed22b51baa1fb8a3a/src/cert.rs#L46)
1. which calls [`parse_cert_internal()`](https://github.com/briansmith/webpki/blob/8b741a41a14428b996886b4ed22b51baa1fb8a3a/src/cert.rs#L46) which returns an error if the extensions are not present.

I agree that `rustls` should require Subject Alternative Name entries when it verifies certificates.  But when the user provides their own certificate verifier, I think `rustls` should not perform any additional verification.

Therefore, let's move the SAN check from [`webpki::EndEntityCert::from()`](https://github.com/briansmith/webpki/blob/8b741a41a14428b996886b4ed22b51baa1fb8a3a/src/webpki.rs#L117) to 
[`webpki::EndEntityCert::verify_is_valid_for_dns_name()`](https://github.com/briansmith/webpki/blob/8b741a41a14428b996886b4ed22b51baa1fb8a3a/src/webpki.rs#L184).

**Comment by mleonhard** [comment]
https://github.com/briansmith/webpki/issues/90

**Comment by ctz** [comment]
> But when the user provides their own certificate verifier, I think `rustls` should not perform any additional verification.

Supplying implementations for verify_tls13_signature/verify_tls12_signature will prevent the certificates from ever touching webpki. See the docs for these methods: https://docs.rs/rustls/0.18.1/rustls/trait.ServerCertVerifier.html

**Comment by mleonhard** [comment]
Thanks for pointing that out.  I implemented `verify_tls13_signature` & `verify_tls12_signature` using [x509-signature crate](https://crates.io/crates/x509-signature).  Example code:
https://github.com/paritytech/x509-signature/issues/4#issuecomment-691729509

**Comment by MightyPork** [comment]
Have just hit that [webpki bug with IP addresses](https://github.com/briansmith/webpki/issues/54) during local testing with self signed certs, and then this.

Here is my non-verifier for local testing. `rustls` requires the `dangerous_configuration` feature for this to work

```rust
/// Blindly trust any cert
/// Please DO NOT use in production
struct AcceptAnyCertVerifier;

impl ServerCertVerifier for AcceptAnyCertVerifier {
    fn verify_server_cert(&self, roots: &RootCertStore, presented_certs: &[Certificate], dns_name: DNSNameRef, ocsp_response: &[u8]) -> Result<ServerCertVerified, TLSError> {
        // YOLO
        Ok(ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &Certificate,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, TLSError> {
        // LOOKS GOOD
        Ok(HandshakeSignatureValid::assertion())
    }

    fn verify_tls13_signature(
        &self,
        _message: &[u8],
        _cert: &Certificate,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, TLSError> {
        // YUP VALID
        Ok(HandshakeSignatureValid::assertion())
    }
}
```

Usage

```rust
let mut tls_config = ClientConfig::new();
tls_config.dangerous().set_certificate_verifier(Arc::new(AcceptAnyCertVerifier));
```

**Comment by ctz** [comment]
They are out of scope in the sense that the core crate does not know how to validate non-webpki certificates. But as mentioned above, there are extension points (released in 0.18.0) to allow complete replacement of the certificate validation code for non-web uses.

I'd encourage people using standardised non-web TLS to build an ecosystem of certificate verifiers specific to those standards.

**Comment by jbg** [comment]
Got it! Thanks for the clarification. Should such an ecosystem develop, I hope that rustls will gain the ability to directly use a crate for verifying IPAddress SANs and other things that are out of scope for webpki, since I don't think it's a good situation for every app/lib using rustls to write their own certificate verification logic.

**Comment by djc** [comment]
I'm working with Brian to enable support for IP addresses in SANs, so that part at least should still be covered by the existing stack.
