### ISSUE TITLE
Build examples on CI

### ISSUE THREAD

**Issue by johnthagen** [ctz/rustls#138]
I don't think that the examples are currently being built on CI. Could they be added?

I should be a few lines like:

```
- cargo build --example XXXX
```

I ask because currently I am trying to build one of the examples and having type conflicts. Is it necessary to use git repos in the Cargo.toml for webpki / webpki-roots? It seems to be making it a lot harder to get started with the examples.

**Comment by ctz** [comment]
These are built by `cargo test`
