### ISSUE TITLE
helper methods for certificate management

### ISSUE THREAD

**Issue by Geal** [ctz/rustls#140]
Hello!
I am currently working on importing rustls in the [sozu HTTP reverse proxy](github.com/sozu-proxy/sozu) and a bit puzzled by how to load and manipulate certificates. Specifically, I'd like to get the list of names in common name and subject alternative name fields, coming from a certificate in PEM format.
So from what I see, I can get the DER representation with [`internal::pemfile::certs`](https://docs.rs/rustls/0.11.0/rustls/internal/pemfile/fn.certs.html) which I'll reuse to create a `CertifiedKey`.
Then, what should I do? wrap this `Certificate` in [`untrusted::Input`](https://docs.rs/untrusted/0.5.1/untrusted/struct.Input.html) and load it in a [`webpki::EndEntityCert`](https://docs.rs/webpki/0.17.0/webpki/struct.EndEntityCert.html)? But then webpki's `name` module is not publicly exported.
I could probably write the code to extract names from a certificate, but where do you think I should put it? in webpki? Or would such helper functions be useful directly in rustls?

**Comment by ctz** [comment]
I think things which decode certificates should live in webpki.

**Comment by Geal** [comment]
Either solution is fine by me. @briansmith what do you think? That would still require a patch to webpki to expose some things from the `name` module
