### ISSUE TITLE
Connecting to server with self-signed certificate

### ISSUE THREAD

**Issue by wrell** [ctz/rustls#143]
I'm trying to connect to a local IOT device that uses a self-signed certificate. I got the cert from the device with `openssl s_client -showcerts -connect x.x.x.x:y` which gives me this:
```
CONNECTED(00000003)
depth=0 CN = f4763d2f-19a3-4556-dcf6-c83659c6b159
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = f4763d2f-19a3-4556-dcf6-c83659c6b159
verify return:1
---
Certificate chain
 0 s:/CN=f4763d2f-19a3-4556-dcf6-c83659c6b159
   i:/CN=f4763d2f-19a3-4556-dcf6-c83659c6b159
-----BEGIN CERTIFICATE-----
MIIC2jCCAcKgAwIBAgIEB6rmujANBgkqhkiG9w0BAQsFADAvMS0wKwYDVQQDDCRm
NDc2M2QyZi0xOWEzLTQ1NTYtZGNmNi1jODM2NTljNmIxNTkwHhcNMTcxMjIxMDgz
ODEwWhcNMTcxMjIzMDgzODEwWjAvMS0wKwYDVQQDDCRmNDc2M2QyZi0xOWEzLTQ1
NTYtZGNmNi1jODM2NTljNmIxNTkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC6oUsqWt0g+hInVr3/0uQHl3gnnykcBQ8f92EzGsbsi5BbJQrCHMHtwInf
H3aVGTH5MWhbdNzUuET7in3YODbKnH2Us+3w8uAfgJnawa4QV7hXgksTAOEPo/7b
zUrgDxewv+8zh/vBWks3zfXdBlEvpAYr++e4ZfychqMhMfrv75lHZ0zTWr1XKarm
eokO4Jsjj+QbSFNxqrYS9M8nP91Cd8NT/JQOQU7p/FriWbVpO1e8nHdg5Ba78TAn
C8jS4L7dIO3XGdVJlM7ztDONu3bUP/eyNjLgKZzgYVPjosdP/vpUCnbPg5brsqbf
MIYnGyd6f3ZPRBTEQtl3HjMLmYttAgMBAAEwDQYJKoZIhvcNAQELBQADggEBALVP
ajuweNEg0ueNTDZA93lMdQ4xP6dOCkfG19KGgaFMd2Lx8pDDrCeoETsRy9BDfxrP
5Qx4gxChqrOhA0O49heBKlE4xbrp1jCik9IBq2KycpJfwE9uRyfoL2fysgsDpSo1
aCh3PzLLNakC/m2UwhHR/9uaAEeSrp25DBODptUpfFZQMKRG9XA9g1mtahtLtYAI
9JcFHgqk/leLFN0jfYpAum1t6XZ9Uu6w/oEG2L+4Y+38S3KMfKif2OYZekSAwbs8
qmtyKJrqB4boa4B2LQzWmIO8wiJZcD1Lw5bdQJ7iD8xBgIIF363+UgaJYH7WFxGI
dYKXugORZIpHq1i0dmQ=
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=f4763d2f-19a3-4556-dcf6-c83659c6b159
issuer=/CN=f4763d2f-19a3-4556-dcf6-c83659c6b159
---
No client certificate CA names sent
---
SSL handshake has read 1442 bytes and written 500 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: 065BC0F4123905DCC9824BB20F8A3915155C3D5F23D0FC6B907E9BBEC2141090
    Session-ID-ctx: 
    Master-Key: FD24A5F11B34BDBB6B0068F9C3826AA0B35399473AD1C70B4ACDE4AE0530185AC07E8872704E5E98FF979FB136BEAC2A
    TLS session ticket lifetime hint: 7197 (seconds)
    TLS session ticket:
    0000 - 48 d5 60 63 5f 06 01 d9-1f 3c 80 60 c1 6e cc 69   H.`c_....<.`.n.i
    0010 - 54 1b 10 bd 32 d2 dd 9e-ef ac a4 9e 58 c0 f0 be   T...2.......X...
    0020 - f2 ed 67 d3 3f 12 01 8b-1c 55 66 e2 bf 1d c7 a5   ..g.?....Uf.....
    0030 - e4 e9 7e 01 9d 07 b1 e6-24 28 cd 35 19 8b 4b fe   ..~.....$(.5..K.
    0040 - 49 82 b6 ae a1 3e dd 3e-02 5e 47 0d 73 7c f2 0e   I....>.>.^G.s|..
    0050 - 9a a3 16 aa 03 2d e3 2d-8d 32 c6 ad 57 e6 20 d8   .....-.-.2..W. .
    0060 - 66 0f 03 c5 a1 75 a6 2b-99 64 9e 78 e9 80 70 22   f....u.+.d.x..p"
    0070 - 8c 66 42 e8 f8 3a 51 41-5c 0b 2f 17 75 cc 5f fc   .fB..:QA\./.u._.
    0080 - 0b 81 2c 5f d9 c1 da 90-9f 7a 2a 07 8b 27 4c fe   ..,_.....z*..'L.
    0090 - df 7f 3d 6b 93 58 2f 52-8a e3 ac d1 56 56 d4 88   ..=k.X/R....VV..

    Start Time: 1513896524
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
```
So I saved the cert and tried adding it to the `RootCertStore` with this:
```
    let mut file = std::fs::File::open("cert.cer").unwrap();
    let mut file = std::io::BufReader::new(file);

    let mut config = rustls::ClientConfig::new();
    println!("{:?}", config.root_store.add_pem_file(&mut file).unwrap()); // (0, 1)
    println!("{:?}", config.root_store.len()); // 0
```
Which if I understand the function correctly means it tried to load the certificate, but found it 'unsuitable'.

So I'm at a loss as to where I should go from here.

Another thing is that my device only has an IP address and a port, so I have no idea what I should do about the `hostname` in `ClientSession::new`. Is what I'm trying to do even possible?

**Comment by wrell** [comment]
Found the issue, the error stems from this part of webpki: https://github.com/briansmith/webpki/blob/d4cff28a541343c17c464145d3406949da6d9b77/src/cert.rs#L99-L116

I guess the cert is lacking the extensions @briansmith wrote about.

**Comment by tomaka** [comment]
There is code that checks specifically for self-signed certificates:
- https://github.com/briansmith/webpki/blob/6c710deee874e256636064f8f5e437b95d63c88d/src/error.rs#L27
- https://github.com/ctz/rustls/blob/27d29e428327cfb0375d4698e9e47d01eecf150e/rustls-mio/tests/badssl.rs#L56-L64

Therefore I'm assuming this is not supported on purpose.

**Comment by jbg** [comment]
I sent https://github.com/briansmith/webpki/pull/127 to webpki in April but so far it was completely ignored. Have been using a fork of webpki since then. If webpki is unmaintained maybe rustls could support an alternative?

**Comment by burdges** [comment]
You're after https://github.com/paritytech/x509-signature I think.  webpki rejected several requests for self signed certs.  

It's plausible you want certificates that are slightly more than self signed, but p2p runs into chicken v egg problems there.

**Comment by jbg** [comment]
Thanks, I know about `x509-signature`. It's news to me if webpki rejected requests for self-signed cert support, though. As mentioned in the above-linked PR, Brian [told me](https://github.com/briansmith/webpki/issues/114#issuecomment-598297061) that he'd be happy to review a PR adding support for self-signed certs. It's just that after the PR was sent, it was ignored for the last 8 months.

I'm not sure it's a great situation for everyone who wants to trust end-entity certs with rustls (or use IP address SANs, or anything else webpki doesn't support) to have to do their own certificate parsing.
