### ISSUE TITLE
"signing failed" when using client certificate authentication

### ISSUE THREAD

**Issue by ian-p-cooke** [ctz/rustls#147]
Would you confirm that the example client/server works with client certificate authentication?  I can't get it to work.   using openssl as the client does work.  I did notice that the example client chose suite TLS13_CHACHA20_POLY1305_SHA256 while the openssl client session chose suite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 but no matter what parameters I passed to the client example I couldn't get past the 'signing failed' error.

> ./target/debug/examples/tlsserver --verbose --certs test-ca/rsa/end.fullchain --key test-ca/rsa/end.rsa --auth test-ca/rsa/client.fullchain --require-auth -p 8443  echo
> DEBUG:tlsserver: Accepting new connection from V4(127.0.0.1:52203)
> DEBUG:rustls::server::hs: decided upon suite SupportedCipherSuite { suite: TLS13_CHACHA20_POLY1305_SHA256, kx: BulkOnly, bulk: CHACHA20_POLY1305, hash: SHA256, sign: Anonymous, enc_key_len: 32, fixed_iv_len: 12, explicit_nonce_len: 0 }
> DEBUG:tlsserver: eof

> echo hello world | ./target/debug/examples/tlsclient --verbose --cafile test-ca/rsa/end.fullchain -p 8443 --auth-key test-ca/rsa/client.rsa --auth-certs test-ca/rsa/client.cert localhost
> DEBUG:rustls::anchors: add_pem_file processed 3 valid and 0 invalid certs
> DEBUG:rustls::client::hs: No cached session for DNSName("localhost")
> DEBUG:rustls::client::hs: Not resuming any session
> DEBUG:rustls::client::hs: Using ciphersuite TLS13_CHACHA20_POLY1305_SHA256
> DEBUG:rustls::client::hs: Not resuming
> DEBUG:rustls::client::hs: TLS1.3 encrypted extensions: [ServerNameAck]
> DEBUG:rustls::client::hs: ALPN protocol is None
> DEBUG:rustls::client::hs: Got CertificateRequest CertificateRequestPayloadTLS13 { context: PayloadU8([]), sigschemes: [ECDSA_NISTP384_SHA384, ECDSA_NISTP256_SHA256, RSA_PSS_SHA512, RSA_PSS_SHA384, RSA_PSS_SHA256, RSA_PKCS1_SHA512, RSA_PKCS1_SHA384, RSA_PKCS1_SHA256, RSA_PKCS1_SHA1], canames: [PayloadU16([48, 26, 49, 24, 48, 22, 6, 3, 85, 4, 3, 12, 15, 112, 111, 110, 121, 116, 111, 119, 110, 32, 99, 108, 105, 101, 110, 116]), PayloadU16([48, 44, 49, 42, 48, 40, 6, 3, 85, 4, 3, 12, 33, 112, 111, 110, 121, 116, 111, 119, 110, 32, 82, 83, 65, 32, 108, 101, 118, 101, 108, 32, 50, 32, 105, 110, 116, 101, 114, 109, 101, 100, 105, 97, 116, 101]), PayloadU16([48, 26, 49, 24, 48, 22, 6, 3, 85, 4, 3, 12, 15, 112, 111, 110, 121, 116, 111, 119, 110, 32, 82, 83, 65, 32, 67, 65])], extensions: [] }
> DEBUG:rustls::client::hs: Attempting client auth
> DEBUG:rustls::client::hs: Server cert is [...]
> TLS error: General("signing failed")
> Connection closed

> echo hello world | openssl s_client -ign_eof -quiet -CAfile test-ca/rsa/end.fullchain -cert ./test-ca/rsa/client.cert -key ./test-ca/rsa/client.rsa -connect localhost:8443
> depth=2 CN = ponytown RSA CA
> verify return:1
> depth=1 CN = ponytown RSA level 2 intermediate
> verify return:1
> depth=0 CN = testserver.com
> verify return:1
> hello world

> DEBUG:tlsserver: Accepting new connection from V4(127.0.0.1:52207)
> DEBUG:rustls::server::hs: decided upon suite SupportedCipherSuite { suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, kx: ECDHE, bulk: AES_256_GCM, hash: SHA384, sign: RSA, enc_key_len: 32, fixed_iv_len: 4, explicit_nonce_len: 8 }
> DEBUG:tlsserver: plaintext read 12
> DEBUG:tlsserver: eof

**Comment by ctz** [comment]
This is fixed on master now. The problem was ring can't use 2560-bit keys.

**Comment by briansmith** [comment]
> This is fixed on master now. The problem was ring can't use 2560-bit keys.

*ring* can verify signatures using 2560-bit keys but it does have a restriction currently regarding generating signatures (i.e. signing) with these odd key sizes. It would be useful to know if there are real-world use cases for supporting the odd key sizes; right now we're just following NIST's advice, IIRC.

**Comment by ctz** [comment]
Yup, it's really not important that 2560-bit keys work for signing in *ring*. I don't have evidence that there are any such keys in deployment.
