### ISSUE TITLE
ECC PrivateKey support for ServerConfig?

### ISSUE THREAD

**Issue by rrichardson** [ctz/rustls#148]
I am probably missing something important, but I can't find a way to construct a ServerConfig with an ECC key.  Is this intentional, or is there a different path for constructing said ServerConfig than the `set_single_cert` method?

**Comment by rrichardson** [comment]
Digging into it further, it looks like `src/sign.rs` would have to include the relevant ecdsa bits from ring, and impl `SigningKey` and `Signer` for `ECDSAKeyPair` and/or `Ed25519KeyPair` 

Is there a reason why this hasn't been done?  If it is a matter of just doing it,  I can take a stab at a PR.

**Comment by ctz** [comment]
Yes, this feature is waiting for support for ECDSA signing in *ring*. There's a work-in-progress branch jbp-ecdsa

**Comment by briansmith** [comment]
> Yes, this feature is waiting for support for ECDSA signing in ring. There's a work-in-progress branch jbp-ecdsa

Check out https://github.com/runconduit/conduit/blob/master/proxy/src/transport/tls/cert_resolver.rs for my suggested implementation strategy. Feel free to take any code from there that you want. My plan is to adapt Ed25119 and eventually RSA to that API and deprecate/remove the old `RSAKeyPair`/`Ed25519KeyPair` APIs.

**Comment by ctz** [comment]
Thanks! This is on master now.
