### ISSUE TITLE
Specify TLS Version

### ISSUE THREAD

**Issue by David-Rumley** [ctz/rustls#152]
It would be great to be able to specify the TLS version. In the 'tlsserver' example there is no way to force the TLS Server to start only in TLS 1.3. Looking at the code it does not seem like there is a way to do it either.

**Comment by Darkspirit** [comment]
In this line
https://github.com/ctz/rustls/blob/eee5e6526d64fbd0386329228148720d78fe898c/examples/tlsserver.rs#L540
you could add:
config.versions = vec![rustls::ProtocolVersion::TLSv1_3];

**Comment by djc** [comment]
(rustls master at this point implements draft 23, as well.)

**Comment by ctz** [comment]
This is in the two example programs now.
