### ISSUE TITLE
Any plans to support no_std

### ISSUE THREAD

**Issue by gurry** [ctz/rustls#157]
What will it take to add no_std support? If I find time I can probably work on it.

**Comment by ctz** [comment]
I haven't looked much at what no_std actually means for a crate (like, which bits of std become unavailable). I'd be very interested to know your opinion on what the impact on rustls that no_std support would have?

**Comment by gurry** [comment]
With no_std your crate is forbidden to use the std library. It can use only [core](https://doc.rust-lang.org/core/) library which is subset of std. Core excludes things like heap allocation APIs, file system APIs, network APIs. As a result you can't use modules such as `std::string`, `std::fs` and `std::net`. The loss of these modules may have a tangible impact for `rustls`.

**Comment by gurry** [comment]
Closed by accident. Reopening.

**Comment by ctz** [comment]
Probably the first things to attack for this would be the problematic types that appear in the public API:

- String is used to specify ALPN names, see #115. I'd like to keep the string API for convenience (while the standard says the names are encodingless octet strings, *in practice* they are all 7-bit ASCII strings like `h2`) but we could totally have `alpn_protocols: Vec<Vec<u8>>` being set by `set_alpn_protocols(protos: &[&str]])`.
- Vec is used in a variety of places in the public API and quite extensively internally, so I think rustls will likely always require an allocator/liballoc.
- Arc similarly.

Do you know if traits like `std::io::Read` are available in `no_std`?

**Comment by gurry** [comment]
No, `std::io::Read` and `std::io::Write` are not available :(.

The allocator will be a significant challenge I think because embedded environments generally don't provide one. There are some `no_std` environments like UEFI which do have an allocation mechanism. In those case we can easily write the needed abstractions or adapters, but for embedded we may have to write a custom heap/memory pool on top of large chunk stack of make do with fixed size arrays instead of vectors (this of course adds limitations, but then `no_std` environments are limited environments to begin with).

`Arc` may be redundant because most `no_std` environments don't have any notion of threads, i.e. programs are always single threaded. So we can completely substitute it out for `no_std` compilation with something `Rc`-like (even `Rc` is not available in `no_std`; so will have to code something by hand)

Overall I think it may require some fundamental rethink in certain areas, but it's definitely doable (from my limited understanding so far). I'll see if I can do some work on it in free time.

**Comment by gurry** [comment]
By the way, just found out about the [`alloc` crate](https://doc.rust-lang.org/alloc/) which can provide some of the above capabilities like `Vec` and `String`. So probably we don't have to lose everything.

Since I got all the information I asked for. I'm closing this issue. If I get time some time in future, I might start working on this.

([This](https://os.phil-opp.com/kernel-heap/#including-the-alloc-crate) is the way to use the `alloc` crate, by the way)

**Comment by jonas-schievink** [comment]
`no_std` support would be awesome as rustls could be a worthwhile alternative to mbedtls on embedded systems. There's already [smoltcp](https://github.com/m-labs/smoltcp), a TCP stack which can work basically without dynamic allocation, so it might have solved many of the same problems rustls would run into already.

**Comment by thejpster** [comment]
I too have a need for a Rust Embedded TLS stack for a project I'm working on. Once you need to pull in mbedtls, you start thinking maybe I should just write the whole application in C and use mbed OS.

**Comment by benpye** [comment]
@ctz I've been investigating this - would it be worth opening a tracking issue to work out what needs to be done to support `no_std`? It looks like the deps are already supporting no_std with the exception of sct - sct is trivial to fix to run with `no_std` where `alloc` is available - I intend to submit a PR for that.

Eliminating the use of std in rustls itself is certainly a larger undertaking but I think a valuable one. A TLS stack is currently the biggest missing piece in a full embedded Rust IoT project. My plan B is to write a wrapper around BearSSL which does not require any dynamic allocation but also does not provide DTLS - which is desirable for CoAP

**Comment by briansmith** [comment]
I believe we'd also need a way to get the current system time. In webpki, I have a solution for that on wasm32-unknown-unknown. But, I don't know about other platforms. Some no_std platforms won't have a clock. How would you deal with that?

**Comment by jonas-schievink** [comment]
This is usually solved on a product- or microcontroller-specific basis by adding a real-time clock, so there would need to be some way of plugging in a custom time source.

**Comment by briansmith** [comment]
> We do lack Mutex on `no_std` but we could use something like `spin` - https://github.com/mvdnes/spin-rs

I am not sure that we should replace mutexes with spinlocks in Rustls. Also, is spin-rs the best splinlock implementation? Does it actually spin before yielding to the OS? Also check out https://github.com/mvdnes/spin-rs/issues/65 and the related PR. (This is something I'd like to resolve for *ring* too.)

Here are some uses of `Mutex` in Rustls:

* `KeyLogFile`. This would just be `#[cfg(...)]`'d out in a no_std configuration.

* `ClientSessionMemoryCache`, `ServerSessionMemoryCache` `TicketSwitcher`, The initial `no_std` port could just omit the session cache (no resumption) at the start.

**Comment by briansmith** [comment]
> This is usually solved on a product- or microcontroller-specific basis by adding a real-time clock, so there would need to be some way of plugging in a custom time source.

It would be good to see how that would work in a way that wouldn't require Rustls (and webpki) to add a type parameter for the time source to (almost) everything. CSPRNG has a similar issue in *ring*.

**Comment by thejpster** [comment]
To avoid putting `<T> where T: Rtc` everywhere, could you store a `&'static dyn Rtc` and get the user to supply one at init time? Where Rtc is some locally defined trait for getting date/time.

**Comment by burdges** [comment]
We rejected `static mut : &mut dyn RngCore` in rand because one badly written dependency weakens everything.  You could mabye break dependencies that abused this, although not sure how that interacts with tests.
```
#[no_mangle]
extern "C" fn rustls_rtc() -> &'static dyn Rtc;  // Or [usize; 2] maybe?

macro_rules { init_default_rustls_rtc => {
    #[no_mangle]
    extern "C" fn rustls_rtc() -> &'static dyn Rtc { ... }
} } }
```

**Comment by yaoxin1995** [comment]
Dose the rusttls already support no_std?

**Comment by djc** [comment]
No.

**Comment by goldwind-ting** [comment]
Dose the rusttls already support no_std?

**Comment by ctz** [comment]
Yes, see release notes: https://github.com/rustls/rustls/releases/tag/v%2F0.23.0
