### ISSUE TITLE
ClientSession::getPeerCertificates() always returns None in the simpleclient example.

### ISSUE THREAD

**Issue by kevinis** [ctz/rustls#164]
I'm testing the getPeerCertificates() API for MesaLink. And it seems the API always return None in the simpleclient example. 

To reproduce the bug please add the following lines after `examples/simpleclient.rs, Line 28`
```rust
match tls.sess.get_peer_certificates() {
    Some(certs) => writeln!(&mut std::io::stderr(), "Certificate: {:?}", certs[0]).unwrap(),
    None =>  writeln!(&mut std::io::stderr(), "No certificate").unwrap(),
}
```

Both `client_can_get_server_cert` and `server_can_get_client_cert`  in `tests/api.rs` pass without any problem. Could you please help me look into this issue? Thanks!

**Comment by kevinis** [comment]
I found only one place where **server_cert_chain** is written:

`src/client/hs.rs` Line 1278
```rust
impl State for ExpectTLS13CertificateVerify {
    fn handle(mut self: Box<Self>, sess: &mut ClientSessionImpl, m: Message) -> NextStateOrError {
    .... .....
        sess.server_cert_chain = self.server_cert.take_chain();
``` 
So is it possible to extend this API to TLS 1.2 as well?

**Comment by ctz** [comment]
Thanks for the report. I can confirm this bug. I'm extending the testing in this area so it doesn't regress before fixing it.
