### ISSUE TITLE
Switch back to a stable version of ring

### ISSUE THREAD

**Issue by Keruspe** [ctz/rustls#167]
See https://twitter.com/BRIAN_____/status/955339612381093888

**Comment by ctz** [comment]
rustls relies on new types and functionality only present in webpki 0.18 and later, and this relies on 0.13.0-alpha ring. These types appear in the public API, too, so it's not just a case of backing some changes out.

**Comment by briansmith** [comment]
I will release a new version of stable ring and webpki RSN. I am actually testing a new integration of rustls + tokio-rustls into a product and once that testing is done, I'll submit the various PRs.
