### ISSUE TITLE
AES doesn't work on my vServer

### ISSUE THREAD

**Issue by Darkspirit** [ctz/rustls#175]
My suspicion is a missing AES-NI, but I don't know what I'm talking about.
I am unsure if I should report this here or over at ring.

**Server:**
https://dev.terrax.net (IPv6-only DNS + HTTPS)
`Error: Custom { kind: Other, error: DecryptError }`

**Chrome Dev 68.0.3440.15 on Debian Testing:**
`ERR_CONNECTION_CLOSED`
(or `ERR_SSL_VERSION_INTERFERENCE` if I set chrome://flags/#tls13-variant to Draft 28)
Chrome can connect if I only allow Chacha on the server.

**Firefox Nightly always prefers Chacha.**
* TLS 1.3: If I create security.tls13.chacha20_poly1305_sha256;false and set security.tls.version.fallback-limit;4 on about:config, I get [`SSL_ERROR_BAD_MAC_READ`](https://searchfox.org/mozilla-central/search?q=SSL_ERROR_BAD_MAC_READ).
* TLS 1.2: security.tls.version.max;3 + security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256;false = Nightly doesn't want to connect and redirects me without an error to about:newtab.

**OpenSSL**
I am using
https://ftp.halifax.rwth-aachen.de/debian/pool/main/o/openssl/libssl1.1_1.1.1~~pre7-1_amd64.deb
https://ftp.halifax.rwth-aachen.de/debian/pool/main/o/openssl/openssl_1.1.1~~pre7-1_amd64.deb

openssl s_client -state -connect dev.terrax.net:443 -ciphersuites TLS_AES_256_GCM_SHA384

> CONNECTED(00000003)
> SSL_connect:before SSL initialization
> SSL_connect:SSLv3/TLS write client hello
> SSL_connect:SSLv3/TLS write client hello
> SSL3 alert write:fatal:bad record mac
> SSL_connect:error in error
> 139646150058432:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../ssl/record/ssl3_record.c:669

https://github.com/openssl/openssl/blob/c0a58e034d3eff68ca5e0d36d7b4d147425b0599/ssl/record/ssl3_record.c#L661

openssl s_client -state -connect dev.terrax.net:443 -ciphersuites TLS_CHACHA20_POLY1305_SHA256
(works)

-----
```
    config.set_single_cert(certs, privkey);
    let cipherlist = [
        "TLS13_CHACHA20_POLY1305_SHA256".to_string(),
        "TLS13_AES_256_GCM_SHA384".to_string(),
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256".to_string(),
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384".to_string(),
    ];
    config.ciphersuites = lookup_suites(&cipherlist);
    config.ignore_client_order = false;
    config.set_persistence(rustls::ServerSessionMemoryCache::new(256));
    config.set_protocols(&vec!["h2".to_string()]);
    config.ticketer = rustls::Ticketer::new();
    config.versions = vec![
        rustls::ProtocolVersion::TLSv1_3,
        rustls::ProtocolVersion::TLSv1_2,
    ];
```
```
rustls = "0.12"
tokio-rustls = "0.5.0"
tokio =  "0.1.6"
hyper = "0.12"
futures = "0.1"

[patch.crates-io]
"rustls" = { git = 'https://github.com/ctz/rustls', branch = 'jbp-tls13-draft-28' }
```

AES works on my PC (which has an aes flag):
```
darkspirit@darkspirit:~$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
stepping        : 9
microcode       : 0x84
cpu MHz         : 1767.704
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 6000.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

```
AES doesn't work here:
```
terrax@terrax:~$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel Core i7 9xx (Nehalem Class Core i7)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2266.746
cache size      : 16384 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc rep_good nopl xtopology cpuid pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt hypervisor lahf_lm pti
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 4533.49
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

```

**Comment by briansmith** [comment]
> My suspicion is a missing AES-NI, but I don't know what I'm talking about.

It's very likely. Can you try `cargo test -p ring`?

**Comment by briansmith** [comment]
> Intel Core i7 9xx (Nehalem Class Core i7)

I am fixing this now. I broke it between 0.13.1-alpha2 and 0.13.1-alpha3.

**Comment by Darkspirit** [comment]
`ring = { git = 'https://github.com/briansmith/ring', branch = 'master' }`

cargo test -p ring > [test2.log](https://github.com/ctz/rustls/files/2086363/test2.log)

TLS 1.2 and TLS 1.3 draft 28 now have a working AES. [Thank you!](https://www.hardenize.com/report/dev.terrax.net#www_tls) :)
