### ISSUE TITLE
Supported signature algorithms should be determined by Cert Verifier

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#176]
1. The ServerCertVerifier and ClientCertVerifier interfaces should be extended to allow them to filter which signature schemes (algorithms, digest algorithms, and curves) are supported. This would be analogous to what's possible with `ResolvesClientCert`/`ResolvesServerCert`/`Signer`.

2. The provided implementations like `AllowAnyAnonymousOrAuthenticatedClient` should allow the user to provide a filter for signature schemes so that one doesn't have to implement a custom "dangerous" implementation of the traits.

3. Everywhere that the client/server advertises supported signature algorithms & curves, it should filter the list using the `ServerCertVerifier`/`ClientCertVerifier`.

Example use case: An application may only want to trust one kind of signature scheme (e.g. ECDSA) in order to minimize the amount of crypto code it relies on.

**Comment by briansmith** [comment]
Note in particular that if one implemented a custom `ServerCertVerifier` and/or `ClientCertVerifier` then that custom verifier might not support every signature scheme.

**Comment by ctz** [comment]
This was done in 1e98fa2eb.
