### ISSUE TITLE
Bump untrusted for security

### ISSUE THREAD

**Issue by tirkarthi** [ctz/rustls#181]
Hi,

This project seems to use `untrusted = 0.6.1` as I can see from the cargo.toml file on master branch. Recently a security issue was fixed as part of 0.6.2 release. Please refer to https://github.com/RustSec/advisory-db/commit/3c0458d26bd19e30dc19ae5ca9a4540cc9c0394b . You can also consider adding [cargo audit](https://github.com/RustSec/cargo-audit) as part of the build step to get notified in the future.

Kindly ignore if this is irrelevant or fixed on another branch.

Thanks.

**Comment by ctz** [comment]
Done, thanks.
