### ISSUE TITLE
`Stream::new()` takes its arguments by reference, making it difficult to wrap

### ISSUE THREAD

**Issue by jbg** [ctz/rustls#183]
Apologies in advance if I'm missing something obvious here.

I'm trying to wrap `Stream` in order to implement rustls support for rust-postgres. The rust-postgres interface requires a function like this:

```
pub struct Rustls {
    config: Arc<rustls::ClientConfig>
}

struct RustlsStream<'a>(rustls::Stream<'a, rustls::ClientSession, Stream>);

impl TlsHandshake for Rustls {
    fn tls_handshake(&self, domain: &str, underlying_stream: Stream) -> Result<Box<TlsStream>, Box<Error + Sync + Send>> {
        let dns_name = webpki::DNSNameRef::try_from_ascii_str(domain)
                                          .map_err(|_| io::Error::new(io::ErrorKind::Other, "failed to parse hostname"))?;
        let tls_session = rustls::ClientSession::new(&self.config, dns_name);
        Ok(Box::new(RustlsStream(rustls::Stream::new(&mut tls_session, &mut underlying_stream))))
    }
}
```

This clearly doesn't work because `tls_session` and `underlying_stream` don't live long enough. Extending the `RustlsStream` wrapper struct to have owned fields for these doesn't help because a struct can't contain references to one of its own fields.

I started experimenting with the rental and owning_ref crates, but surely such magic should not be needed just to use this class. What am I missing? 😄

**Comment by jbg** [comment]
I ended up reimplementing `Stream` as a struct that owns its session and underlying stream: https://github.com/jbg/rust-postgres-rustls/blob/master/src/lib.rs

I'd love to know if there is a way to implement this using the existing `Stream` implementation.

**Comment by ctz** [comment]
I'd be happy to add a `Stream`-shaped thing which owns dependencies, and can likely do it without much extra code.

**Comment by ctz** [comment]
This is c6af00a.
