### ISSUE TITLE
how to choose a list of supported ciphersuites

### ISSUE THREAD

**Issue by Geal** [ctz/rustls#186]
Hello,
let's say I want to modify the supported ciphersuites list, remove some of them or reorder them, in `ServerConfig`: https://docs.rs/rustls/0.13.0/rustls/struct.ServerConfig.html#structfield.ciphersuites

I could recognize in my configuration file some strings corresponding to the ciphersuites, like "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256".
But it gets weird when I want to transform them to a `SupportedCipherSuite`. They are used in `rustls::ALL_CIPHERSUITES`, and that array and the ciphersuites are defined in the `rustls::suites` module. But the cipher suites are not exported by rustls: https://github.com/ctz/rustls/blob/master/src/lib.rs#L298

So, should I do like https://github.com/ctz/rustls/blob/master/examples/tlsclient.rs#L353-L378 and, for each ciphersuite string, go through `ALL_CIPHERSUITES`, format them to a string and compare that string? Another approach would be to match a string to an index in `ALL_CIPHERSUITES`, but that would probably be very brittle :D

Could we have another way, like exporting the static `SupportedCiphersuite` values?

**Comment by briansmith** [comment]
One issue with whitelisting specific cipher suites is that TLS 1.3 and TLS 1.2 have different notions of what a cipher suite is. `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` is a TLS 1.2 cipher suite; a TLS 1.3 cipher suite for AES-128 GCM mode would be `TLS_AES_128_GCM_SHA256 `. 

Rather than whitelisting the specific cipher suites, you could whitelisting the specific key exchange algorithms and specific bulk algorithms. I submitted PR #178 to enable this approach for the bulk algorithm part.

**Comment by Geal** [comment]
oh, I see, that makes sense

**Comment by ctz** [comment]
I'm happy to export the actual `SupportedCiphersuite` values other than in `ALL_CIPHERSUITES` if that helps.

**Comment by balboah** [comment]
not sure if there was an easier way but I could only figure out one way to modify the list:
```rust
config.ciphersuites = config
        .ciphersuites
        .iter()
        .filter(|s| s.bulk == BulkAlgorithm::AES_128_GCM)
        .map(|s| *s)
        .collect();
```

**Comment by Geobert** [comment]
Hi there, 

Sorry to "high jack" the ticket, but I have a similar need but I'm using rustls indirectly, through `warp`.

I'd like to limit warp server to TLS 1.2 only. I've seen that rustls has https://docs.rs/rustls/0.17.0/rustls/struct.ServerConfig.html to choose which ciphersuite to use, but I can't see a way to use it through warp

Is there anyway to do this?

And if ever somebody has an idea, the issue I'm trying to understand is Server A (coded in Go) is doing a POST request to Server B (this one is in Rust using warp), but I have a "bad record MAC" error.

**Comment by djc** [comment]
Taking a brief look at the warp documentation, it looks like you can't do it with the current public API, but you should probably ask this in the warp project issue tracker rather than here.
