### ISSUE TITLE
RFE: use native-tls as a backend

### ISSUE THREAD

**Issue by ignatenkobrain** [ctz/rustls#188]
In Fedora we do not want to package ring (because one security library should fit everyone). It would be nice if rustls could use native-tls internally so that we could choose which backend to use.

**Comment by ctz** [comment]
> In Fedora we do not want to package ring (because one security library should fit everyone).

That's a great shame.

> It would be nice if rustls could use native-tls internally so that we could choose which backend to use.

This is unlikely to happen.  native-tls provides a TLS-as-a-pipe abstraction similar in scope to rustls, so this would reduce rustls to a shallow API shim. That kind of thing is best done elsewhere, for example [tls-api](https://github.com/stepancheg/rust-tls-api) already does this.
