### ISSUE TITLE
Get a security audit done

### ISSUE THREAD

**Issue by djc** [ctz/rustls#189]
There is a discussion about TLS implementations in the newly spun up networking WG:

https://github.com/rust-lang-nursery/wg-net/issues/40

Given the comments there, I've been thinking that it would be great if the rustls stack (which probably means ring + webpki + rustls) went through a security audit somehow (maybe with a [MOSS grant](https://www.mozilla.org/en-US/moss/secure-open-source/)?).

**Comment by djc** [comment]
At some point (a few months ago by now, I think) I submitted rustls for the security MOSS grant, did you ever hear anything from them?

**Comment by ctz** [comment]
I haven't heard anything from them, no :(

**Comment by faern** [comment]
Any updates on this or anything someone can do to try to get the ball rolling?

`rustls + ring` seems really awesome. But it feels unlikely anyone with some security in mind will switch over until it has been thoroughly reviewed. Which in turn won't happen until someone serious starts using it. So it's a catch 22 basically. One way to escape this is to get an audit done, which will likely make a few notable projects trust it enough to start using it.

So, no single company steps up to fund an audit? Can there be a fund raiser where multiple companies heavily invested in Rust (there are quite a few big, medium and small ones now!) can chip in to make it happen?

**Comment by djc** [comment]
So Baidu is at least pretty seriously into rustls, and so is Cloudflare.

https://twitter.com/BRIAN_____/status/1190355575491698689
https://www.reddit.com/r/rust/comments/b9gd10/mesalink_10_openssl_c_apis_done_with_rust_10m/

@steveklabnik do you think Cloudflare would be interested in helping out with this?

**Comment by steveklabnik** [comment]
I'm not sure! @grittygrease would be a better person to talk to about this.

**Comment by faern** [comment]
> So Baidu is at least pretty seriously into rustls, and so is Cloudflare (well, _ring_ at least).

That's really awesome! I was not able to find any large users from my quick searching around. Would it be possible for `ring` and `rustls` to add some "## Trusted by these projects" section to the readme or similar? Since trust in security software very often simply comes from whether or not other big players trust it or not.

Now I'm slightly off topic, but still on the trust in these crates: If there are chat channels, mail lists, forums, websites or whatever dedicated to `rustls`/`ring` can those be advertised in some "## Community" section of the readme/docs? I have not found anything except the git repos that would classify as a "community" around these crates.

The reason I ask for both the above is that when I proposed we switch a project over to use `rustls+ring` the response was essentially "Evaluate the maturity and strength of the community as well as list current big users. Then we might discuss it".

**Comment by djc** [comment]
BTW, Buoyant's Linkerd (2.0, previously known as Conduit) also uses rustls for the data plane. I seem to remember some blog entry from them talking about it, but I couldn't find it anymore.

**Comment by djc** [comment]
See also https://twitter.com/cra/status/1149483328266838020. I emailed them 6 months ago, didn't get a response. Just followed up with a reminder.

**Comment by Shnatsel** [comment]
Cloudflare sadly appears to be disinterested: https://github.com/cloudflare/quiche/issues/129

What kind of price ranges are we talking about? Is there perhaps a chance to crowdfund this?

**Comment by djc** [comment]
We're currently seeing if Buoyant can get the CNCF to pay for an audit; there seems to be some appetite.

**Comment by programmerjake** [comment]
nlnet might help out with a grant

**Comment by djc** [comment]
@vandenoever do you think this would be a viable option?

**Comment by vandenoever** [comment]
Good cryptography a requirement for privacy on the web. So apply for a PET grant is an option. Make sure there's a European dimension to the project though, e.g. by having a European applying for the grant.

**Comment by djc** [comment]
Looks like this is happening -- stay tuned for a few more months.

**Comment by ctz** [comment]
🥳

**Comment by Shnatsel** [comment]
Excellent! Is a more formal announcement expected in the near future, or should I go ahead and spread the link to the report around?

**Comment by djc** [comment]
http://jbp.io/2020/06/14/rustls-audit.html

This blog post is, in my opinion, underselling the audit's results by quite a bit. Make sure to browse the report's conclusions section for some choice quotes.

**Comment by Shnatsel** [comment]
I've posted to [/r/rust](https://www.reddit.com/r/rust/comments/h8za2s/) and [/r/linux](https://www.reddit.com/r/linux/comments/h8zgvj/) on Reddit

**Comment by faern** [comment]
Under scope it says:
> WP1: Cryptography Review & Code Audit against “rustls v0.1.6” or newer

What does that mean? There is no such version.

**Comment by djc** [comment]
Pretty sure it's a typo for 0.16. We should probably ask them for a corrected version.

**Comment by faern** [comment]
Yes. Knowing exactly what source code was audited and what version of the library tested is key metadata here IMO.

**Comment by ctz** [comment]
I've uploaded a corrected version.
