### ISSUE TITLE
Some early data tests are disabled since the recent BOGO upgrade

### ISSUE THREAD

**Issue by kevinis** [ctz/rustls#190]
These BOGO test cases changed to "UNIMPLEMENTED" since the recent bogo upgrade.  See the build log [here](https://travis-ci.org/ctz/rustls/jobs/410505441).

EarlyData-Client-TLS13Draft28
EarlyData-Reject-Client-TLS13Draft28
EarlyData-HRR-Client-TLS13Draft28
EarlyDataWithoutResume-Client-TLS13Draft28
EarlyDataVersionDowngrade-Client-TLS13Draft28
ServerAcceptsEarlyDataOnHRR-Client-TLS13Draft28
EarlyData-Client-VersionAPI-TLS13Draft28
EarlyData-Client-BadFinished-TLS13Draft28

Perhaps the problem is the "--tls13-variant" argument passed to bogo shim. Please refer to  `examples/internals/bogo_shim.rs`, Line 663.

```rust
"-tls13-variant" => {
                let variant = args.remove(0).parse::<u16>().unwrap();
                if variant != 5 {
                    println!("NYI TLS1.3 variant selection: {:?} {:?}", arg, variant);
                    process::exit(BOGO_NACK);
                }
            }
```

If the variant is not 5, the shim spits BOGO_NACK and the test case becomes unimplemented.

**Comment by ctz** [comment]
Thanks for the sharp eye. Fixed in 5563722
