### ISSUE TITLE
TLS 1.2 issue throu .NET on Windows 7 

### ISSUE THREAD

**Issue by neowutran** [ctz/rustls#193]
Hi, 

I tested rustls throu the actix-web project 
It seems to have an issue with TLS 1.2 throu .NET on Windows 7

-> On windows 10, no issue 
-> If I replace rustls by openssl, no issue  

Code used to reproduce the issue https://github.com/neowutran/ShinraMeter/blob/master/DamageMeter.AutoUpdate/UpdateManager.cs#L59 
Just a ``WebClient`` and setting `` ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;``
Issue can only be reproduced on a windows 7 machine

**Comment by ctz** [comment]
Can I get pcaps of the failure?
