### ISSUE TITLE
Safari, received corrupt message of type Handshake

### ISSUE THREAD

**Issue by pftbest** [ctz/rustls#203]
The code is from `hyper-rustls/examples/server.rs`

Error message: "Safari can’t open the page “https://127.0.0.1:1337/”. The error is: “The server “127.0.0.1” did not accept the certificate.” (NSURLErrorDomain:-1205)"

On server side the error message is: "received corrupt message of type Handshake"

Trace: [safari.pcapng.zip](https://github.com/ctz/rustls/files/2631190/safari.pcapng.zip)

**Comment by ctz** [comment]
Thanks very much for the report.  This is unfortunately a bug in Safari (it's sending an invalid SNI extension) but it seems pretty sharp of rustls to outright reject this -- instead it should continue the handshake and pretend the client didn't offer SNI at all.

**Comment by briansmith** [comment]
> instead it should continue the handshake and pretend the client didn't offer SNI at all.

I disagree. In general I don't think we should guess at what was intended when there was a malformed input. If there is a (business) need for supporting a lax mode then I hope it is configurable and defaults to the strict behavior.

**Comment by pftbest** [comment]
Can you please give a more info about what exactly is wrong in the SNI?

**Comment by ctz** [comment]
@chris-wood is this a known bug in SecureTransport?

(Sorry for the mention out of the blue!)

**Comment by ctz** [comment]
Reported upstream as Apple bug 46899367.

**Comment by chris-wood** [comment]
Thanks, @ctz! I missed your first mention. I hijacked the bug internally and will fix it.

**Comment by ctz** [comment]
Thanks @chris-wood, that's great news.

In the meantime I've added warn-level log output for this case.
