### ISSUE TITLE
IOS - cant connect to ssl server

### ISSUE THREAD

**Issue by Haxy89** [ctz/rustls#204]
Can't connect from mobile Safari
Got this in server logs: [rustls::session][WARN] Sending fatal alert DecodeError
Works fine with Windows 10 + Firefox or Chrome

**Comment by ctz** [comment]
Same as #203 ?

**Comment by Haxy89** [comment]
For me all browser on ios are affected and not localhost but my local server (https://hub.docker.com/r/mprasil/bitwarden/#enabling-https): https://192.168.0.19
Is there any workaround?

**Comment by ctz** [comment]
If you control the DNS server your iOS device uses you could give your server a name and use that. If not 192.168.0.19.xip.io is a public DNS name that resolves to 192.168.0.19 (see http://xip.io for info).

**Comment by Haxy89** [comment]
I use Pihole as a dns in my local network.
Is it enaugh?

**Comment by ctz** [comment]
This is Apple issue number 46899367 and I'm told is fixed in iOS 13.
