### ISSUE TITLE
Determine when a handshake is finished?

### ISSUE THREAD

**Issue by alexcrichton** [ctz/rustls#21]
Hello! In the ongoing quest to add rustls as a backend to tokio-tls, I've got one other question. Right now the bindings for other TLS libraries ([openssl](https://github.com/sfackler/rust-openssl), [secure transport](https://github.com/sfackler/rust-security-framework), [schannel](https://github.com/steffengy/schannel-rs)) support the concept of a "mid handshake tls stream" where there's explicit knowledge that a stream is still in part of the tls handshake.

Would it be possible expose this, perhaps on the `Session` trait? This is used with futures right now in that when you perform a handshake it returns a future of an I/O object that represents when the handshake has successfully completed. Additionally, if the handshake fails, you could perhaps avoid allocating resources you'd only want if you were about to communicate.

Although I guess the other question here is if there's already a way to do this? If so, please feel free to close!

**Comment by ctz** [comment]
There isn't currently a way to do this and it is indeed sensible to want.

**Comment by alexcrichton** [comment]
Thanks!
