### ISSUE TITLE
Consider tagging releases

### ISSUE THREAD

**Issue by jonas-schievink** [ctz/rustls#215]
Using git tags makes it possible to check out the exact commit corresponding to a release on crates.io. Additionally it also allows viewing commits and code diffs between individual releases as well as the current release and master.

**Comment by est31** [comment]
There's been a recent addition in cargo which are `.cargo_vcs_info.json` files. You can use them to get the git commit that a particular version has been published under.

**Comment by est31** [comment]
Relevant links:

* https://github.com/rust-lang/cargo/pull/5886
* https://github.com/rust-lang/cargo/issues/5629

**Comment by jonas-schievink** [comment]
Oh, that's neat! Still, having the info in the repository would be easier and even more useful (perhaps automated with [cargo-release](https://github.com/sunng87/cargo-release)).

**Comment by ctz** [comment]
Yeah, I should've really been doing this all along. I'll write a script to do this for all prior releases on all my crates.

**Comment by ctz** [comment]
https://github.com/ctz/rustls/releases
