### ISSUE TITLE
[Client] SNI cannot be different from the hostname used for certificate verification

### ISSUE THREAD

**Issue by ztaura** [ctz/rustls#219]
It's often a security feature to use a higher-level domain name for SNI, to avoid sending the user's own domain over plaintext. For example, "_username_.example.com" may be indicated as "example.com", if the client has prior knowledge that "example.com" hosts "_username_.example.com".

Rustls uses the hostname passed to `ClientSession::new()` for both certificate verification and SNI. This prevents one from eg. requiring the certificate to match *.example.com while sending example.com as SNI. The only way would be to create a `ClientConfig` for _each hostname_ and manually implement `ServerCertVerified`, which is discouraged.

OpenSSL supports setting SNI _per session_ through [SSL_set_tlsext_host_name](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_servername_type.html). It would be great if Rustls has this too!

**Comment by ctz** [comment]
I've not come across this before. Can you give some examples of deployed services that do this?

**Comment by ztaura** [comment]
@ctz Thanks for the quick reply.

> I've not come across this before. Can you give some examples of deployed services that do this?

For example, less-specific SNI can be used as part of [domain fronting](https://en.wikipedia.org/wiki/Domain_fronting). The wikipedia page indicates that both google and amazon used to support this. SNI can also be a privacy concern, which [ESNI was designed to solve](https://www.eff.org/deeplinks/2018/09/esni-privacy-protecting-upgrade-https), but this offers a pretty good workaround.

In any case, my point is that as a general-purpose TLS library, rustls can and should support this common security feature.

**Comment by ctz** [comment]
I didn't think domain fronting varied what domain is used for certificate validation vs SNI, only the underlying HTTP Host header. This is naturally supported by rustls, because it doesn't care about traffic it carries.

But, aside from that, if that is the behaviour you want you can do additional, post-hoc validation of the certificate after rustls has done the main validation. This would show that the connection was valid both for `username.example.com` as well as `example.com`.

But, as is, I don't think is a reasonable feature for rustls to offer. I think I'd be swayed by an RFC, or a large deployed system.

> as a general-purpose TLS library

rustls is really not trying to be a general purpose TLS library like OpenSSL is. It's more about only implementing common and safe options.

**Comment by ztaura** [comment]
@ctz
> I didn't think domain fronting varied what domain is used for certificate validation vs SNI

Agreed. However, this illustrates that modifying SNI can be a privacy enhancement. If SNI is alright, why do we need ESNI?

> a large deployed system

I'm not sure what you mean by this. If you mean "servers that support less-specific SNI," most servers do support that ([github.io](https://github.io/), for example). If you mean "large deployed clients," unfortunately those large companies don't usually care much about your privacy, but more often you can find it in privacy-centric software. For example, Tor sends gibberish server_name like "www.vc7jlfoj05ds.com" during handshake.

> common and safe options

AFAICT, customizing SNI only makes TLS safer, and it's common practice where people care about it.

-----------------

If you're still not sold on this, could you please at least expose [get_verifier()](https://github.com/ctz/rustls/blob/d766c4d8b6c03a2651aa13a01367232d8e2b14a7/src/client/mod.rs#L168) or, even better, [WebPKIVerifier](https://github.com/ctz/rustls/blob/d766c4d8b6c03a2651aa13a01367232d8e2b14a7/src/verify.rs#L92) when `dangerous_configuration` is on? It makes it possible to implement custom verification logic in-band by wrapping the verifier, and should be "common and safe" even outside the scope of this discussion.

Thanks again for the great library!
