### ISSUE TITLE
Please make `log` an optional dependency

### ISSUE THREAD

**Issue by raphaelcohn** [ctz/rustls#22]
In certain code paths, rustls uses the `log` crate's macros. In and of itself, that's fine. However, in a production environment , the logging is an overhead and isn't particularly useful (the TlsErrors, for example, being far more useful - thank you). More significantly, in many server environments, the `log` crate will either write to files or use syslog, both of which can be abused for a DoS attack (it's a classic - overwhelming application or OS logging, particularly on a gateway device, ssl-based jump in box, or the like).

Would you be open to the idea of making the `log` crate optional?

**Comment by djc** [comment]
According to the documentation for `log`, it would seem that the `log` crate by itself would have *very limited* effect on performance. Only once your application has an actual logging implementation set up you'd see some effect. Even with some log trait implementations, I think you can trivially enable or disable logging per trait.

Have you measured the impact for this?

**Comment by raphaelcohn** [comment]
TLS can be in use for every connection on a server dong 100k connections.
There should be nothing extraneous in the critical path. In general,
libraries should not log.

That aside, the log crate's design is inappropriate. It makes logging
expensive, as it's impossible to disable per target without cost. With your
use of it it is very hard to use it for diagnosis as there is no easy way
to correlate with TCP socket activity or higher level application
protocols. If what you need is debugging then you could use an alternative.

On 10 Sep 2016 8:43 p.m., "Dirkjan Ochtman" <notifications@github.com>
wrote:

According to the documentation for log, it would seem that the log crate by
itself would have *very limited* effect on performance. Only once your
application has an actual logging implementation set up you'd see some
effect. Even with some log trait implementations, I think you can trivially
enable or disable logging per trait.

Have you measured the impact for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ctz/rustls/issues/22#issuecomment-246133224>, or mute
the thread
