### ISSUE TITLE
ETA for a 0.15? 

### ISSUE THREAD

**Issue by erickt** [ctz/rustls#220]
Hello @ctz! I was curious when you thought 0.15 would come out, which adds support for ring 0.14. I also have another library that was hoping to bump it's ring dependency (https://github.com/heartsucker/rust-tuf), but since only [one version of ring can be used in a process](https://github.com/briansmith/ring/pull/619), I can't bump that dependency until rustls also updates.

If you expect it to be some time, would you be interested in a 0.14.1 PR that bumps the ring version?

Thanks!

**Comment by djc** [comment]
https://github.com/ctz/rustls/commit/bb272d89d66997eb57005b6528bb60701f6c2783 suggests it's not too far off. :)

**Comment by ctz** [comment]
Should be today.
