### ISSUE TITLE
Save& restore sessions keys

### ISSUE THREAD

**Issue by ddosoff** [ctz/rustls#223]
Is it possible to save and restore sessions keys?

I want save them before exit and load on start to reduce reconnects CPU load.

**Comment by ctz** [comment]
Implement one of these traits (depending if you're a client or server):

- https://docs.rs/rustls/0.14.0/rustls/trait.StoresClientSessions.html
- https://docs.rs/rustls/0.14.0/rustls/trait.StoresServerSessions.html

There's an example of a file-backed one of the former in `examples/tlsclient.rs`. Note that the contents of that file are extremely sensitive (enough to break all past and future traffic of these sessions) so think about your threat model a bit before doing this.
