### ISSUE TITLE
Implement support for certificate pinning

### ISSUE THREAD

**Issue by djc** [ctz/rustls#227]
Apparently this is preventing some people from using rustls:

https://www.reddit.com/r/rust/comments/aidpmh/quinn_020_quic_protocol_implementation_in_rust/eep09zt/

**Comment by ctz** [comment]
This will require briansmith/webpki/issues/68, I think

**Comment by mleonhard** [comment]
I need this, too.
I found a workaround and shared it: https://crates.io/crates/rustls-pin

**Comment by ctz** [comment]
With the existence of rustls-pin, and [in line with some expert advice](https://twitter.com/sleevi_/status/1370509990398726145) I will close this.
