### ISSUE TITLE
add/remove client certificates at run-time?

### ISSUE THREAD

**Issue by ian-p-cooke** [ctz/rustls#233]
are there any plans to support adding and removing client certificates at runtime?  any rough ideas on how to cleanly implement such a feature?  The application I'm thinking of would have potentially millions of client certificates issued and that could be created and revoked at any time and would want to be able to accept new connections without restarting the service.

**Comment by Ralith** [comment]
Can't this already be accomplished by enabling `dangerous_configuration` and implementing `ClientCertVerifier` yourself?

**Comment by ian-p-cooke** [comment]
I think I see how that would work.  Thanks!
