### ISSUE TITLE
I try connect to beam-pool.beepool.org:9507 with rustls failed, I should how to write code?

### ISSUE THREAD

**Issue by biluohc** [ctz/rustls#234]
I modify `examples/tlsclient.rs` to send this Authentication information. 
Perhaps it is the certificate problem of its server side, but I can connect it by using stunnel to convert ssl to normal tcp.

```rust
        let httpreq = r#"{"method":"login", "api_key":"296b3253e5eb7eb725e96f424f3cbd92caf80a26c9cfe188db2ecdad0a8d6ae48", "id":"login","jsonrpc":"2.0"}\r\n"#;
        tlsclient.write_all(httpreq.as_bytes()).unwrap();
```
```sh
tlsclient  beam-pool.beepool.org -p 9507 --http                                                                             (1)
TLS error: WebPKIError(UnknownIssuer)
Connection closed

tlsclient --insecure  beam-pool.beepool.org -p 9507 --http
TLS error: WebPKIError(InvalidSignatureForPublicKey)
Connection closed
```

**Comment by ctz** [comment]
I'm afraid this library doesn't support 1024-bit RSA keys, and that isn't relaxed by the `--insecure` flag. And unfortunately I wouldn't accept a PR to change or relax this further.

Looks like beam-pool.beepool.org is a cryptocurrency mining pool? I suggest you report this to them as a security bug and I'd hope they'd take this seriously.

**Comment by biluohc** [comment]
Oh， Thanks you for your answer。

**Comment by hpk42** [comment]
@ctz There are regions in this world, where governments/corporations are far from having the resources to crack RSA1024 -- in our case it means we need to tell users in those regions now "you can't use TLS, use cleartext" which does not feel right.  Any chance to give app developers, who want to care for people in such peripheral low-resourced regions,  the choice?

**Comment by Ralith** [comment]
Why can't you use secure encryption?

**Comment by Darkspirit** [comment]
There even exists a [valid 2048 bit RSA Let's Encrypt certificate](https://crt.sh/?id=2140864290) for the affected mail server. The cuban provider just needs to be informed to switch over to it.
>  "you can't use TLS, [use cleartext](https://github.com/deltachat/deltachat-core-rust/pull/1010)"

No. Please accustom to do some advocacy if you want to promote an email-based chat system: Hosting providers are generally thankful to get free competence from outside and often react quickly.

**Comment by hpk42** [comment]
@darkspirit @Ralith It's unfortunately not as easy, i am afraid. message me in case you want to know more.

**Comment by Ralith** [comment]
If I were your users I would be *very* unsettled to see claims that you can't use strong encryption for reasons that you can't share in public.

**Comment by hpk42** [comment]
you are misinterpreting my statements, i am afraid.  We do use strong encryption, do security reviews, implement protections against MITM, and all is open source.  This is not about some hidden conspiracy to sneak in weak encryption but caring about actual people and actual situations.  If i now, say, describe precise situations and activists's endeavours in Hongkong, do you think it would be a pure win for them, in *their* situation?  Would you take responsibility for them and effectively help them if i did?
Happy to take this discussion elsewhere, it's veering off-topic -- don't want to disturb @ctz's work further than i did. thanks all.

**Comment by link2xt** [comment]
@ctz 
> And unfortunately I wouldn't accept a PR to change or relax this further.

Would you accept adding SHA1 without adding it to [`SUPPORTED_SIG_ALGS`](https://github.com/ctz/rustls/blob/cad0305cad7a596a8d0dfbedf6cffada99facad5/rustls/src/verify.rs#L20)? In this case shooting ourselves in the foot would require calling `.danger()` and overriding `ServerCertVerifier`.

**Comment by Darkspirit** [comment]
> Would you accept adding SHA1 without adding it to SUPPORTED_SIG_ALGS?

That's https://github.com/briansmith/webpki/issues/110. Should I reopen it?
Which hostnames are affected and should be contacted by you and me?

**Comment by link2xt** [comment]
> > Would you accept adding SHA1 without adding it to SUPPORTED_SIG_ALGS?
> 
> That's [briansmith/webpki#110](https://github.com/briansmith/webpki/issues/110). Should I reopen it?

Yes please. Deprecating insecure algorithms to avoid downgrade attacks is good, but completely removing the support *from the library* causes compatibility problems. 

> Which hostnames are affected and should be contacted by you and me?

I think @hpk42 already wrote some mail, waiting for reply. It is not about one particular server. Users may resort to "no TLS" option when they encounter this problem and we cannot be aware of all the cases and contact all server operators.
