### ISSUE TITLE
Move away from travis CI

### ISSUE THREAD

**Issue by ctz** [ctz/rustls#238]
Find an alternative and move to it. Then undo all the bodges made to work around travis bugs.

Bonus: find something that can support basic testing on Windows, as well as MacOS and Linux.

**Comment by kevinis** [comment]
Microsoft Azure Pipeline looks like a good alternative. I tried it last month but not yet completed the migration. My azure-pipelines.yml file is [here](https://github.com/mesalock-linux/mesalink/blob/bincat-azure-pipelines/azure-pipelines.yml).

**Comment by ctz** [comment]
Thanks for the pointer, I've been playing with this and it looks great.

**Comment by ctz** [comment]
This is done now; going to run both in parallel for a bit.
