### ISSUE TITLE
TLS decryption

### ISSUE THREAD

**Issue by sharksforarms** [ctz/rustls#242]
Given the keys from a sslkeylog, it would be nice to have access to an API to allow to load these keys and decrypt traffic on the fly

**Comment by ctz** [comment]
I think wireshark has this nicely covered?

**Comment by sharksforarms** [comment]
Yes Wireshark does, but I want to do this programatically

**Comment by ctz** [comment]
You can likely build a crate which does this using rustls's internals, but this isn't one of the goals of this project.
