### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by djc** [ctz/rustls#243]
Hey there, what are your plans for a next release? We're starting to move towards a Quinn 0.3 release and it would be nice to have things like https://github.com/ctz/rustls/commit/6e430e5c30218a6a8da16ec240d1dfeb41036a13 and https://github.com/ctz/rustls/commit/5c360613e6021c16cf46e067ba71db02a4113202 out on crates.io.

**Comment by ctz** [comment]
0.15.2 is published now

**Comment by djc** [comment]
Awesome, thanks!
