### ISSUE TITLE
Server ntp1.glypnod.com:123 works with TLS 1.2 but not 1.3

### ISSUE THREAD

**Issue by wbl** [ctz/rustls#244]
I was writing an NTS client in rust and testing it against servers for interop purposes and I discovered that TLS 1.2 does work, while TLS 1.3 does not for several servers.

There are several other hostnames with this issue: zoo.weinigel.se:4446 for instance.
You may need to set ALPN to ntske/1 to reproduce. I am happy to assist with reproduction should this be insufficient.

**Comment by ctz** [comment]
Just considering ntp1.glypnod.com:123 for the moment: that appears to work for me with both 1.2 and 1.3 (and it does appear to negotiate 1.3).

I'm not sending a valid request, but the stuff I get back broadly looks like it might be valid in the "NTS-KE Record Format" I found in draft-ietf-ntp-using-nts-for-ntp-17?

```
$ echo invalid-request-sorry | ./target/debug/examples/tlsclient --proto ntske/1 --port 123 ntp1.glypnod.com > out

$ xxd out | head
00000000: 8001 0002 0000 0004 0002 000f 0005 0068  ...............h
00000010: 475f 17b2 3cfb 7f09 ccfd 8319 27bb 0568  G_..<.......'..h
00000020: d42f 7eee 5387 1296 7d4f 5555 7064 0585  ./~.S...}OUUpd..
00000030: bfc6 5be4 3024 ad6f aada 9c8c 4485 f2d9  ..[.0$.o....D...
00000040: c701 dd46 98ff 877d cdf6 ccdc 897f 7ad4  ...F...}......z.
00000050: 36c6 77ba e5e9 e91d 61bb 950a ae8e 9923  6.w.....a......#
00000060: 9b69 7250 5c1e ddd6 c45e a51a d7eb 9297  .irP\....^......
00000070: 48be f4f5 598e 7268 0005 0068 475f 17b2  H...Y.rh...hG_..
00000080: bfe4 522c bedb 4d19 3cf8 68b0 da4c 9082  ..R,..M.<.h..L..
00000090: f6f0 228d 9c27 76a3 fae9 5198 9fb9 cef8  .."..'v...Q.....
```
