### ISSUE TITLE
Client config set_single_client_cert error

### ISSUE THREAD

**Issue by madtrapper** [ctz/rustls#246]
The pem and key has been verified by openssl, but always get this error when try call set_single_client_cert.

thread 'main' panicked at 'Invalid private key: ()', src\libcore\result.rs:997:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:385
   8: std::panicking::rust_begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libstd\panicking.rs:312
   9: core::panicking::panic_fmt
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed<()>
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf\src\libcore\macros.rs:17
  11: core::result::Result<alloc::boxed::Box<SigningKey>, ()>::expect<alloc::boxed::Box<SigningKey>,()>

**Comment by ctz** [comment]
Could you generate another key using exactly the same process and paste it here? Thanks

**Comment by madtrapper** [comment]
rustls support : 
     SignatureScheme::RSA_PSS_SHA512,
     SignatureScheme::RSA_PSS_SHA384,
     SignatureScheme::RSA_PSS_SHA256,
     SignatureScheme::RSA_PKCS1_SHA512,
     SignatureScheme::RSA_PKCS1_SHA384,
     SignatureScheme::RSA_PKCS1_SHA256,

So it does not support RSA 1024 bit

**Comment by madtrapper** [comment]
It is my mistake, SHA1 cer
