### ISSUE TITLE
Handshake failure with a TLS 1.2-only site

### ISSUE THREAD

**Issue by pustaczek** [ctz/rustls#259]
Handshake errors on some sites which do not have TLS 1.3 enabled, but do have TLS 1.2 enabled(so I presume they should be supported). Specifically, I have encountered the problem with the https://www.spoj.com site while trying to query it using reqwest.

To reproduce the issue, enter rustls-mio/ directory and run `cargo run --example tlsclient -- --http www.spoj.com`. The command will fail, printing:
```
TLS error: AlertReceived(HandshakeFailure)
Connection closed
```

However, OpenSSL is able to connect and reports using "TLSv1.2, Cipher is DHE-RSA-AES256-GCM-SHA384" protocol(run `openssl s_client -connect www.spoj.com:443`). Trying to run it with a -tls1_3 flag results in an error very similar to the rustls one.

**Comment by Darkspirit** [comment]
I think DHE is not supported by Rustls because of worse performance and widespread [misconfiguration](https://www.ssllabs.com/ssltest/analyze.html?d=www.spoj.com).

This polish website processes personal data (at least over this contact form), therefore its TLS configuration is a clear GDPR violation:
https://www.spoj.com/info/
> Newcomers to the site are requested to provide some more information about themselves (full name, institution, country of residence, type of planned activities at SPOJ).

**Comment by pustaczek** [comment]
Thank you for the explanation, though it is a little bit unfortunate since it means I can't use rustls.

**Comment by briansmith** [comment]
@pustaczek I would try asking the site administrator to enable different cipher suites that use elliptic curves instead. I often have good success with that.

Note that https://github.com/ctz/rustls#non-features lists FFDH as a explicit non-feature for Rustls.
