### ISSUE TITLE
Add flag to ignore invalid and self signed certificates

### ISSUE THREAD

**Issue by shockron22** [ctz/rustls#261]
I would love to be able to use rustls to pull from a service with a self signed certificate.

**Comment by Ralith** [comment]
This is already supported. If you need to talk to that specific service, the easiest approach is to explicitly trust it by adding it to your [ClientConfig](https://docs.rs/rustls/0.15.2/rustls/struct.ClientConfig.html)'s root_store. If you really absolutely positively need to undermine the security guarantees and accept *any* certificate, you can do so by enabling the `dangerous_configuration` feature and supplying a custom certificate validation procedure.
