### ISSUE TITLE
Replace OpenSSL?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [ctz/rustls#263]
# Title says it all
I'm wondering if rustls is meant to be able to replace OpenSSL and if a linux distro could replace OpenSSL with rustls the way [Void Linux](https://voidlinux.org/) replaced it with LibreSSL.

**Comment by ctz** [comment]
This is the purpose of mesalink, a C binding for rustls:

https://mesalink.io/
https://github.com/mesalock-linux/mesalink

**Comment by Th3Whit3Wolf** [comment]
This is awesome thank you!
