### ISSUE TITLE
Upgrade to *ring* 0.16

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#266]
Here I will leave some tips for upgrading to *ring* 0.15, which implements a new AEAD API, a new HKDF API, and an extended `ring::rand` API. I'll describe how Rustls can use the new features in this issue.

**Comment by briansmith** [comment]
I noticed all the callers of random_vec generate a 32-byte random. Thus, you can replace this:

```rust
let x: Vec<u8> = random_vec(32);
```
with
```rust
let x: Random<[u8; 32]> = rand::generate(rng)?;
```
or
```rust
let x: [u8; 32] = rand::generate(rng)?.expose();
```

Here's a new implementation of random_u32:
```rust
pub fn random_u32(rng: &rand::SecureRandom) -> Result<u32, error::Unspecified> {
    rand::generate(rng)?.map(|bytes| u32::from_be_bytes(bytes.expose))
}
```

In many cases, this will reduce lines of code and/or heap allocations.

**Comment by briansmith** [comment]
Regarding the new *ring* AEAD API: Now we have a concept of `UnboundKey` vs. `Key`. An `UnboundKey` is just the raw key material + algorithm. A `Key` can be constructed from an `UnboundKey` and a `NonceSequence`. For outbound TLS 1.2 and TLS 1.3 in both directions, implement a `MaskedCounterNonceSequence` yourself as a counter that's masked by a random (TLS 1.2) or handshake-provided (TLS 1.3) mask.

In the case of receiving TLS 1.2 packets with an explicit nonce,  you need to implement a special `ExplicitNonceSequence` that allows the next nonce to be set prior to calling `open_in_place()`.

**Comment by briansmith** [comment]
In the case of the HKDF API, please let me know if you have any trouble; it is designed to be more automatic and less error-prone, but I don't know if people will get it. If we can get the dependencies of Rustls updated to *ring* 0.15 I can contribute a new implementation of the key schedule that uses the new HKDF API.

**Comment by briansmith** [comment]
Also, in this version there is no longer supposed to be any use of `untrusted` in the public API of *ring*. If you find you're not able to remove the `untrusted` dependency during this update, please let me know.

**Comment by ctz** [comment]
I had a look at this this morning. It's going to take a while and quite a lot of refactoring to make this work nicely, and I'm just about to pack away my computer for several weeks :(

> AEAD

It's a shame that all the types that represent having done a key schedule now have mutable state (`Key`) or single-use (`UnboundKey`). This scuppers my future plans to use rayon to encrypt/decrypt sequential messages in parallel.

I can see what the intention of `NonceSequence` is, but in practice the message encryption/decryption functions still need to take a sequence number (for the AAD in TLS12) and I don't want two bits of code (one for sequence numbers, one for the nonce) responsible for the same data. This leaves a remaining option of moving all the sequence numbers into the `NonceSequence` which seems like the best idea, but means this thing will need to be able to signal when the sequence space is running out.

> HKDF

Yes, I couldn't really make this work without *ring* types leaking out of `KeySchedule` to make `derive_traffic_key` (etc.) work.

**Comment by briansmith** [comment]
> It's a shame that all the types that represent having done a key schedule now have mutable state (`Key`) or single-use (`UnboundKey`).

Today I will add back an interface similar to the previous one, that doesn't require the use of `NonceSequence`.

**Comment by briansmith** [comment]
> Yes, I couldn't really make this work without _ring_ types leaking out of `KeySchedule` to make `derive_traffic_key` (etc.) work.

`KeyType` is not a sealed trait, so you can wrap all the *ring* `Algorithm` types in your own type that implements `KeyType` by delegating to the *ring* type, if you want.

**Comment by briansmith** [comment]
> This leaves a remaining option of moving all the sequence numbers into the `NonceSequence` which seems like the best idea,

Yes, that's exactly what I was (am) expecting people to do, for TLS 1.3 opening and sealing, and for TLS 1.2 sealing. I agree that it's weird for things like TLS 1.2 opening and so I'll add a less guided API today for that, which could also be used for TLS 1.3 opening/sealing and TLS 1.2 sealing.

> but means this thing will need to be able to signal when the sequence space is running out.

In your `fn advance(&mut self) -> Result<Nonce, error::Unspecified>` implementation, return `Err(error::Unspecified)` when the nonce sequence is exhausted.

**Comment by briansmith** [comment]
> Today I will add back an interface similar to the previous one, that doesn't require the use of `NonceSequence`.

This was done in https://github.com/briansmith/ring/pull/872, which was incorporated into *ring* 
0.15.0-alpha5. I also published webpki v0.20.0-alpha5 based on *ring* 0.15.0-alpha5.

**Comment by briansmith** [comment]
> This was done in [briansmith/ring#872](https://github.com/briansmith/ring/pull/872), which was incorporated into _ring_
> 0.15.0-alpha5. I also published webpki v0.20.0-alpha5 based on _ring_ 0.15.0-alpha5.

0.15.0-alpha6 and webpki 0.20.0-alpha6, that is.

**Comment by briansmith** [comment]
The changes to crypto-bench demonstrate the kinds of changes needed to deal with the *ring* API changes: https://github.com/briansmith/crypto-bench/commit/679925d52c1bb2586bfbe3c66d0793fc71692242.

**Comment by ctz** [comment]
> Today I will add back an interface similar to the previous one, that doesn't require the use of `NonceSequence`.

Thanks. I've pushed https://github.com/ctz/rustls/tree/jbp-ring-0.15 which has absolutely minimal changes to build and pass tests with ring 0.15. Before merging that I plan to:

- use the new AEAD API in ticketer.rs
- use the new HKDF API in key_schedule.rs

**Comment by briansmith** [comment]
Thanks for the update. I just published *ring* 0.15.0 and webpki 0.20.0.

**Comment by briansmith** [comment]
:sigh: I will release 0.16.0 and webpki 0.21.0 soon, which will fix some API issues. In particular, webpki 0.21.0 will remove `untrusted` from its public API, and *ring* 0.16.0 will remove the last use of `untrusted` from its public API. Also *ring* won't enable its `std` feature by default.

**Comment by briansmith** [comment]
*ring* 0.16.0 will have a new API:

Old:
```rust
        let plain_len = self.dec_key.open_in_place(nonce,
                                                   aad,
                                                   GCM_EXPLICIT_NONCE_LEN,
                                                   &mut buf)
```
New:
```rust
        // Note the name of the function and that `in_prefix_len` was
        // replaced by a range `in_prefix_len..`.
        let plain_len = self.dec_key.open_within(nonce,
                                                 aad,
                                                 &mut buf,
                                                 GCM_EXPLICIT_NONCE_LEN..)
```

Old:
```rust
        let plain_len = self.dec_key.open_in_place(nonce, aad, 0, &mut buf)
            .map_err(|_| TLSError::DecryptError)?
            .len();
```

New:
```rust
        // Now `open_in_place` has `in_prefix_len` implicitly as 0.
        let plain_len = self.dec_key.open_in_place(nonce, aad, &mut buf)
            .map_err(|_| TLSError::DecryptError)?
            .len();
```

Old:
```rust
        let tag_len = self.alg.tag_len();
        let total_len = 8 + msg.payload.len() + tag_len;
        let mut buf = Vec::with_capacity(total_len);
        buf.extend_from_slice(&nonce.as_ref()[4..]);
        buf.extend_from_slice(msg.payload);
        buf.resize(total_len, 0u8);

        self.enc_key.seal_in_place(nonce, aad, &mut buf[8..], tag_len)
            .map_err(|_| TLSError::General("encrypt failed".to_string()))?;
```

New:
```rust
        let tag_len = self.alg.tag_len();
        let total_len = 8 + msg.payload.len() + tag_len;
        let mut buf = Vec::with_capacity(total_len);
        buf.extend_from_slice(&nonce.as_ref()[4..]);
        buf.extend_from_slice(msg.payload);

        // `seal_in_place` will append the tag using `Extend::extend`.
        self.enc_key.seal_in_place(nonce, aad, &mut buf)
            .map_err(|_| TLSError::General("encrypt failed".to_string()))?;
```

**Comment by briansmith** [comment]
*ring* 0.16.0 and webpki 0.21.0 are released.

**Comment by jbg** [comment]
Here's a branch that builds and passes tests with *ring* 0.16.0:

https://github.com/jbg/rustls/tree/jbg/ring-0.16

It depends on my forks of *webpki-roots* and *sct.rs*, each of which have also been updated for *ring* 0.16.0.

**Comment by ctz** [comment]
Thank you @jbg. I've published new sct.rs/webpki-roots/ct-logs based on your changes and pushed https://github.com/ctz/rustls/tree/jbp-ring0.16 for further in-progress changes.

**Comment by lucab** [comment]
I think this was fixed by https://github.com/ctz/rustls/pull/272 and ca be closed.

@ctz can you maybe tag a new `rustls` release at this point? That would unblock a bunch of updates on hyper-rustls, see https://github.com/ctz/hyper-rustls/pull/71#issuecomment-517984760.

**Comment by djc** [comment]
Probably waiting for #282, and it would be nice to get #267 and #274 in, too.

**Comment by est31** [comment]
With those PRs all merged now, will we get a new release on the weekend?

**Comment by ctz** [comment]
0.16 is released now. Thanks for everyone's patience and especially @briansmith for doing the majority of the work here.
