### ISSUE TITLE
Dropping data from closed connection

### ISSUE THREAD

**Issue by wbl** [ctz/rustls#273]
I am trying to connect via tls to nts-test.strangled.org on port 443 (which implements nts-ke, so you need an ALPN string to make it work). The server sends a blob of data, then reads the client response, then closes the connection. When my client tries to read the blob of data it fails with an error "Connection Reset By Peer".  If this was a pure TCP connection the reads of the sent data would have succeeded even after the connection was closed. I suspect this is some over-eager error propagation in the library.

**Comment by ctz** [comment]
Could you post some repro code? There are tests precisely for this behaviour (that closure alerts do not overtake prior application data) see: https://github.com/ctz/rustls/blob/master/tests/api.rs#L268

**Comment by wbl** [comment]
Server went back down (interop testing ended), so there is no way to repo. I'll open again if I have code that reproduces.
