### ISSUE TITLE
Ensure that all contributors from before when license was added are OK with current license

### ISSUE THREAD

**Issue by DemiMarie** [ctz/rustls#28]
Licenses of code cannot be changed without permission of the copyright owner.  So it is necessary to ensure that copyright holders of all code from before when the current license was added give permission to use their code under the current license.

**Comment by ctz** [comment]
Thanks for pointing this out.

The adoption of the current license happened at 3934f255f92bfa31f4ec0ae26df611e5e366c23f.  Before that there was only one commit not by me, f6b270140809edff979b34cd89793f46e68c0823, fixing a one character typo in the readme. So I think this is OK.

**Comment by DemiMarie** [comment]
Got it.  The typo fix is clearly not relevant for copyright, and you can
add a license to your own work, so this issue can be closed.
