### ISSUE TITLE
Large memory consumption

### ISSUE THREAD

**Issue by Vbozovic** [ctz/rustls#280]
Hello,

I am using rustls (14.0 version because of ring issues with other dependencies) along with the server from [here](https://github.com/ctz/rustls/blob/master/rustls-mio/examples/tlsserver.rs) in an embedded environment with memory constraints.

I am trying to send large files and keep memory usage to a minimum in doing so. This is accomplished by chunking the file and sending those chunks:
```
fn send_chunk(&mut self,chunk: &[u8]){
     self.tls_session.write_all(chunk).unwrap();
}
```
i have also tried this approach:
```
fn send_chunk(&mut self,chunk: &[u8]){
     self.tls_session.write(chunk).unwrap();
     self.tls_session.flush().unwrap();
     self.tls_write();
}
```
Both of these approaches result in the file ending up in memory in it's entirety. I underestand that the internals have an unlimited buffer size ? Hence i tried to limit that buffer size:
```
let mut connection = Connection::new(socket, token, mode, tls_session);
//Doesn't work
connection.tls_session.set_buffer_limit(2*FILE_CHUNK_LIMIT);
```
Which doesn't work because the requesting side is not getting the entire file.

Is there a way to send the chunks directly without them being buffered ?

**Comment by ctz** [comment]
`std::io::Write::write` returns the number of bytes written -- when `set_buffer_limit` is in use this will likely be less than the number of bytes in `chunk`. So your `send_chunk` function should either return that, or loop (with intervening `tls_write` calls, which I assume are blocking?) until the whole chunk is done.

**Comment by Vbozovic** [comment]
the `send_chunk()` is already in an iterator (didn't include it) that is chunking the file and passing the chunk slices to the function. The tls_write calls are blocking (i think... that is the part of the example tlsserver).

**Comment by jbg** [comment]
@Vbozovic I've been using rustls in resource-constrained environments for a while, and haven’t had no trouble keeping memory usage small. If you can share more of your code I’m happy to help you work out what’s going wrong.
