### ISSUE TITLE
QUIC API shouldn't expose HKDF PRKs

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#287]
Instead of exposing the raw PRKs, the QUIC API should expose an API that limits which HKDF info is allowed to be used for each key. In particular, it the API should prevent non-QUIC labels from being used. I suggest in particular that for each type of key that needs to be derived for QUIC use, there should be a function which hard-codes the parameters to the HKDF expansion.

This would help make it clearer that non-QUIC keys won't be leaked from Rustls when no key log is being used.

**Comment by Ralith** [comment]
Would it make sense to retain the secrets internally, and expose `aead::SealingKey`/`OpeningKey`s to the QUIC implementation instead? I think that might be workable, and perhaps even simplify our side of things.

**Comment by briansmith** [comment]
That sounds better to me.

**Comment by Ralith** [comment]
Fix in #362.
