### ISSUE TITLE
How to complie examples is undocumented

### ISSUE THREAD

**Issue by tomato42** [ctz/rustls#289]
after edf98927dc419f75f the examples are not built automatically, and the obvious `cargo build` in `rustls-mio` doesn't build them either

**Comment by Darkspirit** [comment]
cd rustls-mio; cargo build --examples
cd rustls-mio; cargo run --example tlsclient --release

**Comment by ctz** [comment]
It's a fair point. I'll look into using cargo workspaces to fix this.

**Comment by ctz** [comment]
Thanks for the report. This is now done on master, and the sample runs in the README work whether or not the crate has been built previously. So `cargo run --example tlsclient -- <args>` should be all your need.

**Comment by tomato42** [comment]
looks good, thanks
