### ISSUE TITLE
Sending raw bytes in Tcp Stream after sending the TLS encypted data

### ISSUE THREAD

**Issue by ivanceras** [ctz/rustls#298]
I'm trying to look for that specific function where I can send a custom data byte stream right after sending the TLS encypted data, without messing the TLS/security metadata/checksum.
The TLS connection is passed in a proxy server, (where the extra custom data byte stream is strip and removed)  without messing with the rest of the TLS encypted data.
I tried writing my custom data on this line [SessionCommon](https://github.com/ctz/rustls/blob/56c0daf17cb51c0c39f54b5a607634591609826c/rustls/src/session.rs#L681)

```rust
pub fn writev_tls(&mut self, wr: &mut dyn WriteV) -> io::Result<usize> {
        self.sendable_tls.append(b">WRITING MY CUSTOM DATA HERE".to_vec());
        self.sendable_tls.writev_to(wr)
}
 ```
I can see the custom data in transit using wireshark but the TLS session will become an error in the browser. It would be nice if somebody familiar with rustls can pinpoint which funtion I should try to hook it next?

**Comment by ctz** [comment]
The way rustls does IO means ultimately your program is in total control of what appears at the TCP level. You retain the underlying socket, so can write it at will. eg, in your program

```
rustls_session.write_tls(&mut some_socket)?;
some_socket.write_all(b"whatever you like")?;
```

What you're doing sounds quite weird though.
