### ISSUE TITLE
Provide ClientHello ALPN protocols to ResolvesServerCert

### ISSUE THREAD

**Issue by jeromegn** [ctz/rustls#299]
Useful information for implementing the [ACME TLS ALPN Challenge](https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-05) response.

Unsure how to expose this without introducing a breaking change.

IMO, it would be better (for future-proofness) to provide a _slightly_ parsed `ClientHelloPayload` to `ResolvesServerCert::resolve` so that things can be added to that struct later on without introducing a breaking change. This is what I did in my fork (well, I'm sending the raw client hello payload).

**Comment by ctz** [comment]
pr #301 addresses this

**Comment by jeromegn** [comment]
Oh! That’s speedy! Thanks

I’ve been wondering if it would be simpler to only pass a single struct to
that function. Since this is a breaking change, sounds like a good time to
do it. A struct with methods that return the server name, supported
signatures, alpns and other things. Maybe as a wrapper around the
ClientHelloPayload?

I feel like that would make it simpler to extend later without introducing
breaking changes.

**Comment by jeromegn** [comment]
I'm happy to work on a PR that changes the API a bit like I described if you think it's worthwhile.
