### ISSUE TITLE
Is it possible to create self-signed certificates using just rustls?

### ISSUE THREAD

**Issue by svenstaro** [ctz/rustls#302]
I realize this might be a stupid question but I didn't find anything in the non-goals and no issues asking about this.

Basically, I want to create ad-hoc self-signed TLS certificates for integration tests. I do not care about the bad security implications of doing this, it's for testing server behavior against "invalid"/self-signed TLS certificates. Can I use rustls to generate these? I didn't find anything in the API that would allow for that.

**Comment by Ralith** [comment]
See [rcgen](https://crates.io/crates/rcgen).

**Comment by ctz** [comment]
Yeah rcgen is the recommended way to do this.

**Comment by svenstaro** [comment]
Ok cool, thanks.
