### ISSUE TITLE
Make ring/webpki Optional

### ISSUE THREAD

**Issue by TheBlueMatt** [ctz/rustls#303]
For my use-case (using rustls as an optional bit in a larger application where the failure mode *must* be a panic resulting in only that thread being taken down, ie no C/asm dependencies, not to mention supporting a wider set of platforms than ring supports, see #247), it would be nice to make ring optional. Sadly this means making webpki also optional given it depends on ring.

I took a brief glance and it looks like optionally disabling the PKI stuff should be pretty doable (this is doubly nice for use-cases that are essentially just "pin cert to X, cause I know what I'm connecting to).

(Optionally) swaping out ring for something more Rust-y may be a bit more involved, but doing so by falling back to eg *only* supporting AES variants and something like ed25519 (via dalek) should also be pretty doable.

I'm more than happy to take a crack at working on this (starting with optionally removing PKI support, for users who want to pin a cert anyway) on this, if it'll eventually make its way upstream.

**Comment by dignifiedquire** [comment]
I would like to second this, forcing the C toolchain here is quite unfortunate, especially when trying to use ring in a setting where one is trying to avoid exactly that.

**Comment by Darkspirit** [comment]
Could someone commercially interested in this please help funding further transition to Rust and adding at least a limited Rust-only feature flag? The whole ecosystem would benefit from it. Thank you!
https://github.com/briansmith/ring/issues/785
https://github.com/briansmith/ring/issues/626

**Comment by TheBlueMatt** [comment]
Don’t see why it needs to be commercial...I offered to look into it here but it seems the crate author is busy with other things and rustls isn’t getting love atm.

**Comment by Darkspirit** [comment]
I tried to make an argument on why this issue should be closed since ongoing work on ring only needs to be completed.

**Comment by TheBlueMatt** [comment]
Or we could just fix it here by working around ring, which seems like a much easier approach (and would massively reduce the trusted base, for applications where that is important) :).

**Comment by Darkspirit** [comment]
> massively reduce the trusted base, for applications where that is important

That's the whole point of the [ring](https://github.com/briansmith/ring#ring) - [rustls](https://github.com/ctz/rustls#approach) - [webpki](https://github.com/briansmith/webpki#what-is-webpki) triplet. 
Ring obviously needs sth. like a "pure Rust" feature flag and rustls needs DTLS support for WebRTC.
In contrast, OpenSSL, WolfSSL, etc. already have paid key members..

**Comment by TheBlueMatt** [comment]
Sure, money would be nice, but here I am offering to do work for free to make my use-case work.... responding with “we need corporate backers” is a bit of a weird response.

**Comment by ctz** [comment]
Honestly the goals of rustls were to be a "batteries included" library (including, built in certificate verification for web use and software crypto). I'm not super interested in changing that at this point, but I a) totally support efforts in ring to reduce the amount of non-rust code and b) would not object to  forks which go in a different direction for different tradeoffs.

**Comment by TheBlueMatt** [comment]
Fair enough, if its not the goals of the project, its not the goals. Don't think I have the resources to maintain a fork, sadly.
