### ISSUE TITLE
Module `pemfile` is private

### ISSUE THREAD

**Issue by ctron** [ctz/rustls#310]
It seems the `pemfile` module is no longer "internal", but it also isn't marked as public.

At least when I try to use it, get the following error:

~~~
error[E0603]: module `pemfile` is private
~~~

**Comment by ctz** [comment]
This is available at `rustls::internal::pemfile`, but there's also `rustls::pemfile` which is indeed private. Realistically these functions either belong in another crate, but I don't want to inflict a trivial dependency on rustls consumers.
