### ISSUE TITLE
Expose certificate chain to applications

### ISSUE THREAD

**Issue by royneary** [ctz/rustls#328]
I would like to access the client's certificate chain in an established session and then use the client's certificate for authorization. I saw that ``ServerSession`` implements the method ``get_peer_certificates``, but it is private. Is there a reason for that? I would love to see it becoming public.

The same is valid for ``ClientSession::get_peer_certificates``.

**Comment by ctz** [comment]
[`get_peer_certificates`](https://docs.rs/rustls/0.16.0/rustls/trait.Session.html#tymethod.get_peer_certificates) is a member of the trait `Session` that is implemented for both ServerSession and ClientSession.

**Comment by royneary** [comment]
Thanks. I was confused by a compiler error. ``use rustls::session::Session;`` works.
