### ISSUE TITLE
Support for fully user-defined certificate verification

### ISSUE THREAD

**Issue by DemiMarie-parity** [ctz/rustls#329]
libp2p needs to be able to verify certificates that would normally be considered invalid (they contain a critical extension that webpki does not, and should not, know about).  It also needs to return data from this process to the application.  The easiest way to do this is for rustls to not even try to parse the certificate itself.  Instead, it should just treat it as bytes.

**Comment by Ralith** [comment]
Have you looked at [`ClientCertVerifier` and `ServerCertVerifier`](https://github.com/ctz/rustls/blob/master/rustls/src/verify.rs#L61-L91), exposed when the [`dangerous_configuration`](https://github.com/ctz/rustls/blob/master/rustls/src/lib.rs#L298) option is enabled?

**Comment by DemiMarie-parity** [comment]
I have.  However, webpki is still used to verify the peer’s signature.

**Comment by DemiMarie-parity** [comment]
@Ralith @ctz The basic problem is described in https://github.com/libp2p/specs/issues/241: WebPKI rejects the certificate because there is a critical extension it is not aware of.  This is really a WebPKI bug.

**Comment by briansmith** [comment]
> WebPKI rejects the certificate because there is a critical extension it is not aware of. This is really a WebPKI bug.

The webpki crate is doing what it is designed to do.

> webpki is still used to verify the peer’s signature.

My intent going forward is to allow extracting the public key from *valid* certificates (end entity certificate is valid at the current time and chains to a trust anchor successfully) in webpki.

If you need to use the key from a certificate that isn't a "Web PKI" certificate, then it would be better to avoid webpki completely for that.

**Comment by Ralith** [comment]
Definitely wouldn't want to allow processing of certificates with unknown critical extensions, after all. The corollary being that insofar as that rustls wants to support non-web use cases, it should allow validation without involving webpki.

**Comment by DemiMarie-parity** [comment]
@Ralith Exactly.  @ctz would you be open to this?  I will make a PR.

**Comment by ctz** [comment]
> I have. However, webpki is still used to verify the peer’s signature.

I plan to fix this shortly. This will take the form of widening `ServerCertVerifier`/`ClientCertVerifier` to encompass signature validation too. That'll mean the code you have in #350 will still be useful, but inside your implementation of that trait. A full implementation of those traits will mean certificates do not touch webpki.

**Comment by DemiMarie-parity** [comment]
> > I have. However, webpki is still used to verify the peer’s signature.
> 
> I plan to fix this shortly. This will take the form of widening `ServerCertVerifier`/`ClientCertVerifier` to encompass signature validation too. That'll mean the code you have in #350 will still be useful, but inside your implementation of that trait. A full implementation of those traits will mean certificates do not touch webpki.

Thank you!  Do you plan to make the webpki dependency optional?

I agree that merging #350 could cause problems: it breaks the guarantee that certificates passed to `ServerCertVerifier`/`ClientCertVerifier` can be parsed by webpki.  I suspect some code in the wild panics if webpki can’t parse a certificate passed to `ServerCertVerifier`/`ClientCertVerifier`, and merging #350 would silently make this code vulnerable to denial of service.

**Comment by DemiMarie-parity** [comment]
@ctz will you be able to implement this soon?  If not, I can implement it and make a PR.

**Comment by ctz** [comment]
Yes, I have this mostly done.

**Comment by ctz** [comment]
> Thank you! Do you plan to make the webpki dependency optional?

webpki types will still appear in the public API -- I don't plan in the short term to change this.

**Comment by DemiMarie-parity** [comment]
@ctz is there a way I could help?  This is blocking libp2p-quic so it is important that it be fixed quickly, and I am more than willing to help with it.

**Comment by ctz** [comment]
I have this done, I am just working on testing the new API which has uncovered some minor defects that want fixing.

**Comment by DemiMarie-parity** [comment]
> I have this done, I am just working on testing the new API which has uncovered some minor defects that want fixing.

@ctz would you mind pushing this to a public branch, so that I can start testing the new API?

**Comment by ctz** [comment]
Sure: https://github.com/ctz/rustls/tree/jbp-custom-sigverify

**Comment by DemiMarie-parity** [comment]
That looks fantastic!  I can try getting it to work with libp2p-quic and report back.

**Comment by sehz** [comment]
Is branched merged?

**Comment by sehz** [comment]
@ctz is there progress on this?

**Comment by djc** [comment]
It looks like this went into 0.18.0 as 1e98fa2eb1004b0ddbf68bdbcbf960891667e10b.
