### ISSUE TITLE
Duplicated Code

### ISSUE THREAD

**Issue by TimonPost** [ctz/rustls#330]
Hi, when I was browsing through the code base, my IDE showed a lot of duplicated code.

![image](https://user-images.githubusercontent.com/19969910/71710066-b2057f00-2dfa-11ea-9f94-946891483009.png)

Is this intentional?

**Comment by TimonPost** [comment]
[inspections.zip](https://github.com/ctz/rustls/files/4018276/inspections.zip)

**Comment by ctz** [comment]
This tool seems to be complaining that different types have similar behaviours. Factoring that out would make the code more complex, not less, though.
