### ISSUE TITLE
How to disable certificate validation on Client side

### ISSUE THREAD

**Issue by Lauriethefish** [ctz/rustls#334]
Hello, I wanted to use this library to secure a previously made application with TLS. This didn't seem to difficult, until it got to testing. In order to test, I use a self-signed cert. So I need to disable certificate validation. I saw [This Post](https://github.com/ctz/rustls/issues/68) saying that you needed to enable the dangerous_configuration feature and then use (ClientConfig).dangerous().set_certificate_verifier().

I got to this point fine, but I couldn't work out how to make a ServerCertVerifier that does not require a certificate to be valid.

How do I do this? Or is there a better way

**Comment by Ralith** [comment]
Verifiers can indicate validity based on any logic they like, but for testing, you should just add your test certificate to the test client's root store.

**Comment by Lauriethefish** [comment]
OK, thanks

**Comment by Lauriethefish** [comment]
Ok, I'll see if I can figure that out

**Comment by Lauriethefish** [comment]
Ok, so I actually made a proper certificate and used that. (I have verified that it is valid) But now rustls is saying that this is also invalid. (Error: UnknownIssuer)

This is my client code

```
// Making config
let mut config = ClientConfig::new();
config.root_store.add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);
let config = Arc::new(config);

// Connecting
let mut stream = TcpStream::connect(address.to_owned() + ":" + port)?; // Connect to the server
let mut session = ClientSession::new(&config, DNSNameRef::try_from_ascii_str(address).unwrap());
let mut stream = Stream::new(&mut session, &mut stream);
```

This is my server code

```
// This is from the function where I initialise TLS
// Generate a TLS config with no client authentication required
let mut config = rustls::ServerConfig::new(NoClientAuth::new());
    
// Load the two files for our cert and key
let cert_file = &mut BufReader::new(File::open("cert.pem").unwrap());
let key_file = &mut BufReader::new(File::open("privkey.pem").unwrap());

// Load the public and private keys
let cert_chain = certs(cert_file).unwrap();
let mut keys = pkcs8_private_keys(key_file).unwrap(); // Changed from rsa_private_keys

// Enable the SSL certs
config.set_single_cert(cert_chain, keys.remove(0)).unwrap();
return config;

// This is where I handle my clients
// Authenticate the client with TLS, this is done automatically in server session
let mut session = rustls::ServerSession::new(&tls_config);
let mut stream = rustls::Stream::new(&mut session, &mut client); // Make an SSL stream for automatic encryption

```

**Comment by Darkspirit** [comment]
Does cert.pem contain both the end-entity certificate and the intermediate CA certificate?

**Comment by Lauriethefish** [comment]
No it only contains the CA certificate. But this seems to be OK when using it for other purposes. It is from letsencrypt

**Comment by Darkspirit** [comment]
That sounds wrong. /etc/letsencrypt/live/yourdomain.tld/**fullchain.pem** must be used with any web- or mail server. It contains the end-entity certificate of your domain plus "Let's Encrypt Authority X3" intermediate CA. Browsers can try to fetch and cache missing intermediate CA certs, but it's better to serve them along the website certificate. (As ISRG Root X1 - which signed Let's Encrypt Authority X3 - is already known client-side, it's not part of fullchain.pem.)

**Comment by Lauriethefish** [comment]
Ok, I'll try fullchain.pem to see if that works

**Comment by Lauriethefish** [comment]
Thank you so much. That worked, I don't know much about TLS and certificates, so thanks for explaining to me.
