### ISSUE TITLE
client connection keep-alive issue

### ISSUE THREAD

**Issue by jeonsy92** [ctz/rustls#336]
I tried to connect 3rd party api using tls connection.
But if I change Connection : close  -> keep-alive, it doesn't work.
I don't want to do cold start every time I request.
I just want to keep connection and request same data.
how to do this? I couldn't find any examples using keep-alive.

This is my codes. 

env_logger::init();
let mut config = rustls::ClientConfig::new();
config
    .root_store
    .add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);
let config = Arc::new(config);
let tick = schedule_recv::periodic_ms(1000);
loop {
    tick.recv().unwrap();
    let a = time::now();  
    let domain_name = "api.binance.com";
    let dns_name = webpki::DNSNameRef::try_from_ascii_str(domain_name).unwrap();
    let mut sess = rustls::ClientSession::new(&config, dns_name);
    let mut sock = TcpStream::connect(format!("{}:443", domain_name)).unwrap();
    let request = format!(
        "GET /api/v3/time HTTP/1.1\r\n\
            Host: {}\r\n\
            connection: close\r\n\r\n",
        domain_name
    );
    let mut stream = rustls::Stream::new(&mut sess, &mut sock);
    stream.write_all(request.as_bytes()).unwrap();        
    stream.flush().unwrap();
    let mut res = vec![];
    stream.read_to_end(&mut res);
    println!("{}", String::from_utf8_lossy(&res));
    println!("{}", a.strftime("%H:%M:%S.%f").unwrap());
}

**Comment by Ralith** [comment]
rustls is not a HTTP implementation. You might be looking for [`reqwest`](https://crates.io/crates/reqwest).

**Comment by jeonsy92** [comment]
it's for TLS connection isn't it?

**Comment by jeonsy92** [comment]
rustls is for TLS connection. Isn't it?

**Comment by Darkspirit** [comment]
[net2](https://crates.io/crates/net2) extends [std::net::TcpStream](https://doc.rust-lang.org/std/net/struct.TcpStream.html) with set_keepalive(): https://docs.rs/net2/0.2.33/net2/trait.TcpStreamExt.html#tymethod.set_keepalive
Async tokio also has it: https://docs.rs/tokio/0.2.11/tokio/net/struct.TcpStream.html#method.set_keepalive

But [hyper](https://crates.io/crates/hyper) has a connection [pool](https://github.com/hyperium/hyper/blob/ba2a144f8b81042247088215425f91760d8694a1/src/client/mod.rs#L15) and should reuse existing connections. I would use [hyper-rustls](https://crates.io/crates/hyper-rustls):
https://github.com/ctz/hyper-rustls/blob/34adf9a18f50327ada110a0ca36a2b01436b420d/examples/client.rs#L47-L48
If you need, you could call `http.set_keepalive(Some(std::time::Duration::from_secs(600)));`.
https://docs.rs/hyper/0.13.1/hyper/client/struct.HttpConnector.html#method.set_keepalive
