### ISSUE TITLE
rustls panics when loading a bad cert

### ISSUE THREAD

**Issue by Nokel81** [ctz/rustls#337]
This might not be covered by the release stability but I find it odd nonetheless.

If you manually load a `rustls::Certificate` and then call `ClientConfig::set_single_client_cert` and that certificate is bad it panics with `"Invalid private key"`.

I think that loading a invalid private key should result in a `InvalidData` `io::Error` instead.

**Comment by Ralith** [comment]
`io::Error` doesn't make sense here since there are no syscalls being made, but returning an error from `set_single_cert`, or better yet from `Certificate` construction, would make a lot of sense.

**Comment by ctz** [comment]
Yeah, this is really a bug. Compare, for instance, these two:

- https://github.com/ctz/rustls/blob/a0ed806d10a8bad604eff050959ef3a5dac1d538/rustls/src/client/handy.rs#L83
- https://github.com/ctz/rustls/blob/a0ed806d10a8bad604eff050959ef3a5dac1d538/rustls/src/server/handy.rs#L106

**Comment by ctz** [comment]
Fixed in 8a9fd05
