### ISSUE TITLE
crate `rustls` required to be available in rlib format, but was not found in this form

### ISSUE THREAD

**Issue by nitsuga5124** [ctz/rustls#339]
Error occurs when compiling a serenity based discord bot on a RaspberryPI 3b with the target `stable-armv7-unknown-linux-gnueabihf`

This error does not occur when using `cross` as the compiler on an intel x86_64 machine.

https://gitlab.com/nitsuga5124/robo-arc commit `33a04826039036e3968910fc59baebd92bfbdf19` 
Source code of the bot for possible error recreation purposes.

```
error: crate `rustls` required to be available in rlib format, but was not found in this form

error: aborting due to previous error

error: could not compile `discord_bot`.
```

**Comment by ctz** [comment]
I think this is a cargo bug, see also:

* https://github.com/tikv/tikv/issues/5130
* https://github.com/rust-lang/cargo/issues/6993
* https://github.com/rust-lang/cargo/pull/7008
