### ISSUE TITLE
Peer certificates access performance and documentation

### ISSUE THREAD

**Issue by Ten0** [ctz/rustls#342]
I find the current implementation of `get_peer_certificates` to be limiting in several ways:
1. #169 lacks documentation
2. The current implementation (basically still https://github.com/ctz/rustls/commit/7b73a0b8531551af82d52090cada04ae054fae6a) is far from being as performant as it could be:
    - The returned Vec is initialized without capacity, hence reallocated multiple times.
    - This function could return a slice and let the end user clone the content *if needed* (in particular, re-parsing through `webpki` would not require owned data).
3. This may be more of a call for help (or documentation?), but I can't find a way to access parsed information about the certificate (CN, SAN...) without re-parsing the entire certificate, nor can I find the documentation on how to parse it, identify which certificate of the chain is the right one to extract the information from, etc...

When https://github.com/briansmith/webpki/pull/103 lands, we will have access to that information from the [`EndEntityCert`](https://docs.rs/webpki/0.21.2/webpki/struct.EndEntityCert.html) structure.
I feel like the ideal solution would be to provide access to the parsed [`EndEntityCert`](https://docs.rs/webpki/0.21.2/webpki/struct.EndEntityCert.html) in the [`Session`](https://docs.rs/rustls/0.16.0/rustls/trait.Session.html) trait. This would automatically provide access to relevant data once the previously mentioned PR is merged while incurring zero additional parsing/verification cost, and allow for more validation implementations for the end user. For instance, https://github.com/hyperium/tonic/pull/228 could propagate that access to the common name of the clients, which the server could validate on. (I suspect there may be some issues with self-referencing due do [`EndEntityCert`](https://docs.rs/webpki/0.21.2/webpki/struct.EndEntityCert.html) not owning its data. They could maybe  be solved using [pinning](https://doc.rust-lang.org/std/pin/#example-self-referential-struct) or [`rental`](https://crates.io/crates/rental), though I'm surprised Rust does not provide a safe abstraction for precisely this yet, maybe this will happen eventually, any reference?)

**Comment by ericseppanen** [comment]
It would be most helpful if `EndEntityCert` gave access to _everything_ in the certificate, not just the DNS names.  For example, a client certificate may identify a specific user (via subjectAlternativeName containing an email, [directory name](https://access.redhat.com/documentation/en-us/red_hat_certificate_system/9/html/administration_guide/managing_subject_names_and_subject_alternative_names#Populating_Certificates_with_Directory_Attributes), [principal name](https://docs.microsoft.com/en-us/azure/active-directory/authentication/active-directory-certificate-based-authentication-get-started#requirements), URI, etc.) or role (e.g. the "User roles" extension is [used by spinnaker](https://spinnaker.io/setup/security/authentication/x509/#encoding-role-information-in-x509-extensions)).

Unfortunately, webpki does not seem friendly to the idea of being a comprehensive parser of x509 fields/extensions. (See [issue 116](https://github.com/briansmith/webpki/issues/116), [issue 119](https://github.com/briansmith/webpki/issues/119) ). If webpki views its role as "only implement PKI as implemented between web browsers and public web servers", maybe that's a reasonable trade-off to keep their code simple-- but it makes rustls-based client authentication significantly harder.

If webpki can't handle these use cases, and rustls can only use webpki as its certificate parser, then I think that anyone wanting to do client authentication (where the user/role is carried in the SAN or extensions) will basically be forced to re-parse the certificate themselves.

**Comment by ericseppanen** [comment]
> Is that so bad? 

It's not the end of the world.  The purposes of my comment are:
1. Describe the client auth situation as I see it (and see if someone points out that I've missed something important), to possibly answer the question for anyone else wondering how to do client certificate based authentication.
2. Link to some in-the-wild uses of client authentication certificates to make the point that this isn't just theoretical.
3. Find out if everyone is happy with the current state of things, or if there's a desire to handle this case a bit better.

> Decoupling those complex and application-specific features from rustls will help reduce breaking changes/improve flexibility in applications that need them.
The thing that seems most It's unfortunate that certificate parsing has to start over from scratch.

I could imagine an alternate universe where the x509 certificate parser can parse everything in the certificate; webpki can choose to ignore much of that; and rustls can choose to rely on webpki's defaults. Then we'd just need a way to access the certificate (as structured data) to implement proper client authentication. That seems sufficiently decoupled to me...?

**Comment by sehz** [comment]
Maybe alternative is to decouple Rustls from webpki  so we could have alternative implementations?

**Comment by jadamcrain** [comment]
This is also related to #331. In my application I need to be able to authenticate both client and server on a non-domain name `CN`, and the server needs to be able to extract a role from a custom extension. This is pretty common when applying TLS in industrial control systems.

**Comment by Ten0** [comment]
> > Unfortunately, webpki does not seem friendly to the idea of being a comprehensive parser of x509 fields/extensions
> 
> Is that so bad? Decoupling those complex and application-specific features from rustls will help reduce breaking changes/improve flexibility in applications that need them.

I agree we should not over-complexify the interface of rustls to export additional information that may not be needed by rustls nor the end user.
However I don't think exporting what was rightly parsed, because needed and used in any case, would hurt.

On the contrary, this would allow users to easily extract the very basic information that was already used to perform the authentication (e.g. [`DNSName`](https://docs.rs/webpki/0.21.3/webpki/struct.DNSName.html)) without paying the cost of re-computing everything, which will be enough for a large part of the cases (like mine or that of @jadamcrain).

**Comment by ctz** [comment]
Going to close this, as the main ask (not returning a copy of the certificate chain) is now done.
