### ISSUE TITLE
Help: How to correctly convert openssl::pkey::PKeyRef into rustls::PrivateKey

### ISSUE THREAD

**Issue by Ben-Lichtman** [ctz/rustls#345]
I am planning on using both openssl and rustls for a project, however I am encountering some difficulties when trying to move keys and certificates generated by openssl into rustls.

The `rustls::PrivateKey` documentation mentions that the data must be in "DER-encoded ASN.1 in either PKCS#8 or PKCS#1 format". does this mean that the bytes stored within the internal Vec<u8> are in ascii armoured PKCS8 format, or raw ASN.1 bytes?

The `openssl::pkey::PKeyRef` struct gives the methods `private_key_to_pem_pkcs8` and `private_key_to_der`. The _to_pem_pkcs8 method outputs the familliar ascii armoured text with --header-- and --footer--. The _to_der method outputs bytes.

However, when I output the pkcs8 output to file, then read it back in using `rustls::internal::pemfile::pkcs8_private_keys`, then look at the internal `Vec<u8>` in the `rustls::PrivateKey`, it is different to the _to_der output.

So which way is the correct one? should I be outputting then parsing the pem_pkcs8 file, or should I be using the der directly?

**Comment by Ben-Lichtman** [comment]
Code to reproduce: `privkey` is a valid private key
`	let a = privkey.private_key_to_pem_pkcs8().unwrap();
	println!("{:?}", &a[..20]);
	let b = privkey.private_key_to_der().unwrap();
	println!("{:?}", &b[..20]);

	let mut f = File::create("test.pem").unwrap();
	use std::io::Write;
	f.write(&a).unwrap();

	drop(f);

	let f = File::open("test.pem").unwrap();
	let mut rd = std::io::BufReader::new(f);
	let k = rustls::internal::pemfile::pkcs8_private_keys(&mut rd).unwrap();

	let PrivateKey(x) = &k[0];
	println!("{:?}", &x[..20]);`

**Comment by djc** [comment]
Might be useful to show the actual DER contents for both methods (from a freshly generated private key that doesn't need to stay private, of course). In my understanding, writing out and then reading back PKCS8 PEM should result in (roughly?) the same result as moving the DER along directly. (You can also use something like https://lapo.it/asn1js/ to get a better understanding of the PEM/DER contents and if/how they are different.)

**Comment by Ben-Lichtman** [comment]
@djc wow that's a great website! thanks. I have found out since I posted this that pkcs8 is a layer of additional metadata wrapping the DER data which describes what it is, so the formats are incompatible for rustls purposes.

I'm closing this issue as i think I have figured it out.
