### ISSUE TITLE
ECDSA authentication for Clients.

### ISSUE THREAD

**Issue by amrx101** [ctz/rustls#349]
I was under assumption that `ECDSA` auth for client is supported but then I stumbled upon this piece of code

    
        // We only support RSA signing at the moment.  If you don't support that,
        // we're not doing client auth.
        if !certreq.certtypes.contains(&ClientCertificateType::RSASign) {
            warn!("Server asked for client auth but without RSASign");
            return Ok(self.into_expect_server_done(client_auth));
        }

Why do we skip client-auth for non RSA signing? We can have a `signer` trait implemented for `client` which can be invoked here.

**Comment by Voker57** [comment]
Moreover, rusttls description says "ECDSA or RSA server authentication by servers.", so if implementing is hard then at least that line should be corrected.

**Comment by amrx101** [comment]
@Voker57 , Yes. I don't know what to believe, the documentation or the code.

**Comment by amrx101** [comment]
@briansmith , can you please provide some info on this.

**Comment by ctz** [comment]
This is a bit of an oversight from the time RSA was the only supported algorithm for this. It looks like this was missed because that field is not well used: openssl sets it (effectively) at compile time (not based on the keys available), and boringssl defaults to RSASign+ECDSASign.

**Comment by ctz** [comment]
Fixed in 63584de
