### ISSUE TITLE
Allow omitting SNI

### ISSUE THREAD

**Issue by Demi-Marie** [ctz/rustls#351]
libp2p forbids sending SNI.  To quote [the current spec]:

> In order to keep this flexibility for future versions, clients that only support the version of the handshake defined in this document MUST NOT send any value in the Server Name Indication. Servers that support only this version MUST ignore this field if present.

[the current spec]: /libp2p/specs/blob/7f4de9bb07c89015aa84d7b605153e45102b55c3/tls/tls.md

**Comment by Darkspirit** [comment]
> Future versions of this handshake protocol MAY use the Server Name Indication (SNI) in the ClientHello as defined in RFC 6066, section 3 to announce their support for other versions.
> 
> In order to keep this flexibility for future versions, clients that only support the version of the handshake defined in this document MUST NOT send any value in the Server Name Indication. Servers that support only this version MUST ignore this field if present.

It sounds like a dirty hack to me. ALPN should be used (https://github.com/libp2p/go-libp2p-tls/issues/10).

**Comment by gandaro** [comment]
Is there a reason why you cannot use the `enable_sni` flag of the `ClientConfig` struct?

**Comment by Demi-Marie** [comment]
I wasn’t aware of that.  Closing.
