### ISSUE TITLE
cert with DigiCert root does not validate

### ISSUE THREAD

**Issue by bluejekyll** [ctz/rustls#352]
domain: `help.northernbeaches.nsw.gov.au` gets `UnknownIssuer`

I've tried both `webpki-roots` as well as `rustls-native-certs` independently, with no luck. I did verify the root cert is in webpki-roots. Firefox does validate the cert.

Here's the chain:

-----BEGIN CERTIFICATE-----
MIIG6jCCBdKgAwIBAgIQCr2z6fUO60xYIRU/ybHfoDANBgkqhkiG9w0BAQsFADBNMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMScwJQYDVQQDEx5EaWdpQ2VydCBTSEEyIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMTkwNzI1MDAwMDAwWhcNMjEwNzI4MTIwMDAwWjCBhDELMAkGA1UEBhMCQVUxGDAWBgNVBAgTD05ldyBTb3V0aCBXYWxlczEOMAwGA1UEBxMFTWFubHkxITAfBgNVBAoTGE5vcnRoZXJuIEJlYWNoZXMgQ291bmNpbDEoMCYGA1UEAxMfaGVscC5ub3J0aGVybmJlYWNoZXMubnN3Lmdvdi5hdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANTw3eneBKANdAAUu0WTqYbAjhs0nzN8TTd2uZLVqUuHlX91b8snS1DOcyNi1x655esW8i49iDQdUPUyDOexqbnPPKe0LXwknJvuKDN8NgYQY7iFAZ+61XRawL9nBEh2JhP2nHJAGxuqqeflhX+HXMv5B0tm0dNANevREJ4cI1wOpEDFvjJisPB8Casf0SGKXd6ieJqNfE+At7sgPS5YgSLu6dE/yQC1f4bVRGduGHB8uM9CYUtxd3Wb//MJU29NvDpHfzyyI0QQQHQkTdQ8XMh6byZFqnG4WsRBLOXWBZ7k5PDwLRp5aLC17E+ZBSTDOChcqkcKx2DPbA7oy5KVWikCAwEAAaOCA4wwggOIMB8GA1UdIwQYMBaAFA+AYRyCMWHVLyjnjUY4tCzhxtniMB0GA1UdDgQWBBRSiORxlJqtSY1VH9PlRfzx9IRR9jBPBgNVHREESDBGgh9oZWxwLm5vcnRoZXJuYmVhY2hlcy5uc3cuZ292LmF1giN3d3cuaGVscC5ub3J0aGVybmJlYWNoZXMubnN3Lmdvdi5hdTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMGsGA1UdHwRkMGIwL6AtoCuGKWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9zc2NhLXNoYTItZzYuY3JsMC+gLaArhilodHRwOi8vY3JsNC5kaWdpY2VydC5jb20vc3NjYS1zaGEyLWc2LmNybDBMBgNVHSAERTBDMDcGCWCGSAGG/WwBATAqMCgGCCsGAQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAgGBmeBDAECAjB8BggrBgEFBQcBAQRwMG4wJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBGBggrBgEFBQcwAoY6aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0U0hBMlNlY3VyZVNlcnZlckNBLmNydDAMBgNVHRMBAf8EAjAAMIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdQC72d+8H4pxtZOUI5eqkntHOFeVCqtS6BqQlmQ2jh7RhQAAAWwmypUgAAAEAwBGMEQCIEDE5vyxcKlXz9TWswX8CpMKQw0CKRggfXQ1j/x0gv4LAiBHnZfK95Sxbr+ryW0hlyzd2j3ObxyOP+WtgrNKShj5jAB3AId1v+dZfPiMQ5lfvfNu/1aNR1Y2/0q1YMG06v9eoIMPAAABbCbKlWIAAAQDAEgwRgIhAN5iQRt/UpBxqmfNNlEZAabfJ/OXAqLWG1xB2+cYXly5AiEAxHTsjrTj4Wn/FVNO+9/FxeOTgztLPJMHBqhjK7Xp8hUAdQBElGUusO7Or8RAB9io/ijA2uaCvtjLMbU/0zOWtbaBqAAAAWwmypRjAAAEAwBGMEQCIBvOEJWkM0rcRl72PNhuSpy+NXnVVpRBkHDxfnM1m9nuAiAdANfWPIrEjs62jL0TsXA/s2/ZXCtLW/+aiL5QHHNZ6jANBgkqhkiG9w0BAQsFAAOCAQEAnvCR2u8+P+16HOoEo2pGFxi29t+D18hb6VNEzZJKE6sygVPvm+JtzC5SdLiPIyuquVChqTPg7v3E/b9m8yLRLWVdPzjXqDQKsi7JKgsDnO8IsjatLQ818dKaqSdIft+7XITJjfHHA7uO5l/rQ61vwnuUPPJG7SQ+iJyw6mfdB8nlyT0rilC7KnDvoL1Y4gTyWmbHXEr99eUUuGAmXmsQBX6SFgpi541QKVMU+sQi8mohtkP48s/gvADWmB23eMbrd7pjSEetAW2+6GNeP4PDygrw/uZWvGI7Cwlx+Z1A8rWs8unukajGGLoAtyGD1LN3DRSzqHgyJgGC2xvflzPd5g==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIElDCCA3ygAwIBAgIQAf2j627KdciIQ4tyS8+8kTANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQTAeFw0xMzAzMDgxMjAwMDBaFw0yMzAzMDgxMjAwMDBaME0xCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJzAlBgNVBAMTHkRpZ2lDZXJ0IFNIQTIgU2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANyuWJBNwcQwFZA1W248ghX1LFy949v/cUP6ZCWA1O4Yok3wZtAKc24RmDYXZK83nf36QYSvx6+M/hpzTc8zl5CilodTgyu5pnVILR1WN3vaMTIa16yrBvSqXUu3R0bdKpPDkC55gIDvEwRqFDu1m5K+wgdlTvza/P96rtxcflUxDOg5B6TXvi/TC2rSsd9f/ld0Uzs1gN2ujkSYs58O09rg1/RrKatEp0tYhG2SS4HD2nOLEpdIkARFdRrdNzGXkujNVA075ME/OV4uuPNcfhCOhkEAjUVmR7ChZc6gqikJTvOX6+guqw9ypzAO+sf0/RR3w6RbKFfCs/mC/bdFWJsCAwEAAaOCAVowggFWMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMHsGA1UdHwR0MHIwN6A1oDOGMWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwN6A1oDOGMWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwPQYDVR0gBDYwNDAyBgRVHSAAMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwHQYDVR0OBBYEFA+AYRyCMWHVLyjnjUY4tCzhxtniMB8GA1UdIwQYMBaAFAPeUDVW0Uy7ZvCj4hsbw5eyPdFVMA0GCSqGSIb3DQEBCwUAA4IBAQAjPt9L0jFCpbZ+QlwaRMxp0Wi0XUvgBCFsS+JtzLHgl4+mUwnNqipl5TlPHoOlblyYoiQm5vuh7ZPHLgLGTUq/sELfeNqzqPlt/yGFUzZgTHbO7Djc1lGA8MXW5dRNJ2Srm8c+cftIl7gzbckTB+6WohsYFfZcTEDts8Ls/3HB40f/1LkAtDdC2iDJ6m6K7hQGrn2iWZiIqBtvLfTyyRRfJs8sjX7tN8Cp1Tm5gr8ZDOo0rwAhaPitc+LJMto4JQtV05od8GiG7S5BNO98pVAdvzr508EIDObtHopYJeS4d60tbvVS3bR0j6tJLp07kzQoH3jOlOrHvdPJbRzeXDLz
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsBCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7PT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbRTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUwDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/EsrhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJFPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0lsYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQkCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
-----END CERTIFICATE-----

**Comment by ctz** [comment]
This server is unfortunately misconfigured -- it does not send a certificate chain but only a single certificate. Firefox works because it implements "AIA fetching" where it collects the intermediates on demand -- rustls/webpki doesn't implement this.

**Comment by bluejekyll** [comment]
Ah, I see, thank you for your help! Is this a feature that is planned in rustls, or something we don't plan to support?

**Comment by ctz** [comment]
It's a quite tricky feature to implement, since it requires some way of rustls/webpki potentially making several HTTP requests during a handshake :(

**Comment by bluejekyll** [comment]
Yes, that would require additional sockets during that procedure. I see the issue. Thanks again for looking into this, I'll see about reporting the issue to that site and fixing it.

**Comment by Ralith** [comment]
> It's a quite tricky feature to implement, since it requires some way of rustls/webpki potentially making several HTTP requests during a handshake :(

I think this would become very natural if certificate handling becomes asynchronous, as discussed some in https://github.com/ctz/rustls/issues/89.

**Comment by briansmith** [comment]
> . Firefox works because it implements "AIA fetching" where it collects the intermediates on demand -- rustls/webpki doesn't implement this.

Does Firefox really implement AIA fetching? Last I checked their plan was to preload a bunch of intermediate certificates for their roots and avoid AIA fetching. Firefox has been anti-AIA since before I worked on its certificate validation, especially during my time working on it, and afterward. See https://bugzilla.mozilla.org/show_bug.cgi?id=399324.

**Comment by Darkspirit** [comment]
https://wiki.mozilla.org/Security/CryptoEngineering/Intermediate_Preloading#Intermediate_CA_Preloading
https://bugzilla.mozilla.org/show_bug.cgi?id=1603834#c2

**Comment by briansmith** [comment]
In that case, it probably works in Firefox because you visited a site that sent the missing intermediate, and Firefox saved it. After Firefox's intermediate CA certificate actually ships in production, they will (I hope) remove the caching of intermediate certificates from visited sites, making Firefox's behavior (mostly) deterministic. (FWIW, you can implement intermediate certificate preloading with the webpki crate already.)
