### ISSUE TITLE
MessageDeframer::deframe_one() unwraps Message::read() which terminates on an invalid message

### ISSUE THREAD

**Issue by cytrinox** [ctz/rustls#366]
During code review, I came across the MessageDeframer code:
https://github.com/ctz/rustls/blob/616392f4d85c08aec7e8f2c49754f079a167ddd7/rustls/src/msgs/deframer.rs#L128

From my understanding, if the Codec implementation fails at any point decoding a (invalid) message, the unwrap() call would terminate the whole client or server application.

Please have a look if this is by intention or should be catched.

**Comment by ctz** [comment]
Thanks for the report!

I think this is harmless, but that I needed to check the code carefully to convince myself of that really indicates that the code here should be improved. So I'll leave this open until I do that.

`Message::read` returns `None` only if the passed-in buffer doesn't contain a whole message (ie, either the buffer is too small to contain a header, or the length in the header is too long for the overall buffer). But these conditions are guaranteed false when `buf_contains_message` yields `BufferContents::Valid`

**Comment by briansmith** [comment]
I hope there's a way to restructure the code a bit to get rid of the `unwrap()` in a way that reflects what you described.

**Comment by ctz** [comment]
Refactored in f07f8b1
