### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by DemiMarie-parity** [ctz/rustls#368]
Would it be possible to make a new release to incorporate custom signature verification?

**Comment by Ralith** [comment]
I'd like to be sure #367 is included, as it's required for the current QUIC draft. I also need to finish investigating a key update interop failure in Quinn which may be related to the recent refactoring.

**Comment by DemiMarie-parity** [comment]
@Ralith when do you believe this will be done?

**Comment by Ralith** [comment]
Hopefully this weekend? I just discovered it.

**Comment by Ralith** [comment]
Added the bugfix to the open PR, I'm good to go!

**Comment by djc** [comment]
The audit will start as of next week, so might make sense to hold off until after it has completed.

**Comment by ctz** [comment]
I think any major audit findings will want backporting to commonly-used versions, so it doesn't stop a release per-se.

But I have [a few things I want to get in](https://github.com/ctz/rustls/projects/1) prior to the next release, and I'm trying to keep master as still as possible for the next couple of weeks so folks aren't auditing a moving target.

**Comment by DemiMarie-parity** [comment]
It would be nice to see at least the ed25519 (#340) integration be part of the audit, as it will almost certainly be heavily used and affects critical parts of the code.

**Comment by tomaka** [comment]
Sorry to be a pain, but do you have some vague estimate for a new version? More like weeks, or more like months?

**Comment by nviennot** [comment]
Hello Joseph,
I wanted to say that a new release would be very helpful for us as well.
Thank you
Nico

**Comment by Keruspe** [comment]
It would also allow for dependents to stop carrying two version of base64

**Comment by djc** [comment]
@tomaka since ed25519 and link-time cipher removal have been merged, my guess is a release will be forthcoming within one or two weeks. Please stop piling on and just wait while @ctz uses his spare time to move things forward.

**Comment by ctz** [comment]
0.18.0 is out. Sorry for the delays in getting here.

**Comment by nviennot** [comment]
Thank you ✨❤️

**Comment by DemiMarie-parity** [comment]
Thank you @ctz!!!
