### ISSUE TITLE
Obtaining client_random and secret bytes directly

### ISSUE THREAD

**Issue by DrDinosaur** [ctz/rustls#369]
Hi, I know I can obtain the client_random and secret bytes in a file with https://docs.rs/rustls/0.17.0/rustls/struct.KeyLogFile.html and https://docs.rs/rustls/0.17.0/rustls/trait.KeyLog.html but I would like to obtain the bytes directly (put them in my own u8 array) as I want to work with them as an array (I know this is strange).  

I looked at the documentation and source of the links above, but I'm not sure how I can do this. I'm not sure if maybe [this function](https://docs.rs/rustls/0.17.0/rustls/trait.Session.html#tymethod.export_keying_material) can do it or how it differs from the KeyLog feature above. 

Additionally, if I'm running something like Rocket which uses rustls, would I still be able to do this, or would I need to interact rustls at a lower level, one that's not abstracted away by Rocket? In other words, could I do this in my Rocket application, or would I have to add code to do this in Rocket itself?

Thanks.

**Comment by ctz** [comment]
Yes, this is possible: you need to provide your own implementation of the KeyLog trait that you mentioned, and then give it to your ClientConfig/ServerConfig in the `key_log` field.

**Comment by DrDinosaur** [comment]
How long are the client_random and secret bytes valid for? Would they last for an entire session?

**Comment by ctz** [comment]
They last only as long as the `log()` call, so you would need to take your own copy if you need them longer than that.
