### ISSUE TITLE
Get "alert decode error" when client connects

### ISSUE THREAD

**Issue by violetasuwu** [ctz/rustls#372]
Hello, recently I decided I was going to implement a Gemini client in Rust and I decided to use rustls as it seemed quite cool. However, when a client connects to the server, I get the error
`error:1400441A:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert decode error:ssl_pkt.c:1200:SSL alert number 50`
I've tried to look into it myself but found nothing. 

The code in question is here: https://gist.github.com/violetasuwu/68cf7fdb8d171817cdbf6a0af8b0aeaf

Thank you so much in advance.

**Comment by oboforty** [comment]
You're welcome!

**Comment by ctz** [comment]
Would you be able to take a packet capture and post it here?
