### ISSUE TITLE
Is dangerous() broken?

### ISSUE THREAD

**Issue by emabee** [ctz/rustls#373]
For a db-client (hdbconnect) I'm proudly using rustls for TLS. 
There are a couple of tools that use this db-client. 
Some tools are used for internal purposes where omitting the server certificate check is highly desired (e.g. when dealing with frequently changed test landscapes).
It was working some months back, but unfortunately, after some dependency updates, I don't get it working anymore :-( 

The db client is now using rustls 0.17.0.

I try to inhibit the server certificate check by calling
```rust
    let mut config = ClientConfig::new();
    config
        .dangerous()
        .set_certificate_verifier(Arc::new(NoCertificateVerification {}));
```
where
 
```rust
struct NoCertificateVerification {}
impl rustls::ServerCertVerifier for NoCertificateVerification {
    fn verify_server_cert(
        &self,
        _roots: &rustls::RootCertStore,
        _presented_certs: &[rustls::Certificate],
        _dns_name: webpki::DNSNameRef<'_>,
        _ocsp: &[u8],
    ) -> Result<rustls::ServerCertVerified, rustls::TLSError> {
        Ok(rustls::ServerCertVerified::assertion())
    }
}
```

but I now get a `WebPKIError(BadDER)` when trying to use the connection. Am I doing sth wrong here, or is sth missing?

**Comment by emabee** [comment]
I should add that when I use the latest master branch of rustls, and add the following methods to NoCertificateVerification, 

```rust
    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &rustls::Certificate,
        _dss: &rustls::internal::msgs::handshake::DigitallySignedStruct,
    ) -> Result<rustls::HandshakeSignatureValid, rustls::TLSError> {
        Ok(rustls::HandshakeSignatureValid::assertion())
    }

    fn verify_tls13_signature(
        &self,
        _message: &[u8],
        _cert: &rustls::Certificate,
        _dss: &rustls::internal::msgs::handshake::DigitallySignedStruct,
    ) -> Result<rustls::HandshakeSignatureValid, rustls::TLSError> {
        Ok(rustls::HandshakeSignatureValid::assertion())
    }

```

then it works again.

But of course I would strongly prefer using a rustls version from `crates.io` .

**Comment by Ralith** [comment]
Most likely webpki is unhappy because the certificate is missing the subjectAltName extension, which is a somewhat common mistake.

**Comment by ctz** [comment]
Yes, I imagine your certificates have changed. dangerous() and the related APIs haven't changed in quite a long time (in released versions).

**Comment by emabee** [comment]
OK, thanks for the support! I also found the related issue [90](https://github.com/briansmith/webpki/issues/90) on webpki .
