### ISSUE TITLE
assertion that X.509 name is shorter than 64KB should be replaced with non-panicking error handling

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#374]
In 227d9a2aff4bc8a2fdf8bbbf6270a618509f9a10 an assertion was added that checks that a trusted root's subject name (IIUC) is not larger than 64KB. However, either:

* The assertion is dead code. Maybe it's not possible to actually add a trust anchor with such a long name (this would be true, I think, in any case where the trust anchor added is first filtered through a webpki function). If it is dead code then the reason we expect this assertion to never be reached should be documented. The `unreachable!()` macro should be used instead of `assert!()` for additional clarity

* The assertion is not dead code. Then (1) There should be a test that actually adds a certificate to the root store with such a long name, (2) the API for adding trust anchors should reject such big names at the time the trust anchor is added with non-panic-based error reporting, so that this code does become dead code, in which case we should do what I said in the previous bullet point. Or, if (2) isn't practical, then the assertion should be replaced with non-panicking error handling.

This probably requires changing the public API.

**Comment by ctz** [comment]
I've replaced this with something that will produce correct output for all lengths of input, 0..usize::MAX..
