### ISSUE TITLE
visibility of OwnedTrustAnchor 

### ISSUE THREAD

**Issue by dingelish** [ctz/rustls#377]
Hi ctz,

Our team is using rustls to terminate TLS connections under the [spiffe](https://spiffe.io/) framework. rustls works pretty well and we all like it! The only problem in our implementation is that we have to use `OwnedTrustAnchor::to_trust_anchor` to verify certificates, while `OwnedTrustAnchor` is not a `pub`ed structure. We're using an internal fork of rustls and wonder if you can make it public. It'll be the best if we can use it directly from crates.io and we don't mind feature gating. Really appreciate your help. Thanks!

Best,
Yu

**Comment by ctz** [comment]
I've added a test in 1b99071 that checks that this is usable outside the crate already -- could you look at the test and tell me if I've misunderstood what you're asking for?

**Comment by teozkr** [comment]
@ctz Both the struct and method are `pub`, but the struct is unreachable (since the `anchors` module isn't `pub`, and `OwnedTrustAnchor` isn't covered by the same `pub use` as `RootCertStore`.

**Comment by blaggacao** [comment]
@ctz @dingelish Would it be conceivable to add yours as a sort of _contrib_ implementation of the SPIFFE protocol to _rustls_?

**Comment by dingelish** [comment]
> @ctz @dingelish Would it be conceivable to add yours as a sort of _contrib_ implementation of the SPIFFE protocol to _rustls_?

@blaggacao  sgtm. thanks!

**Comment by blaggacao** [comment]
Breadcrumb trail &mdash; See also: https://www.mail-archive.com/openssl-users@openssl.org/msg88596.html
