### ISSUE TITLE
Will rustls support AES128-SHA?

### ISSUE THREAD

**Issue by jacobgc** [ctz/rustls#381]
Attempting to connect to a server that only supports AES128-SHA with deno fails. This cipher is used by the europa.eu website and its unlikely to change. Is there any chance this cipher suite will be supported at some point?

See more: https://github.com/denoland/deno/issues/6427

**Comment by ctz** [comment]
From here I see europa.eu negotiate `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` with rustls and everything works:

```
$ ./target/debug/examples/tlsclient --http europa.eu --verbose 2>&1 | grep -E '<title>|Using cipher'
[2020-07-02T11:34:06Z DEBUG rustls::client::hs] Using ciphersuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        <title>EUROPA - European Union website, the official EU website</title>
```

There aren't any plans for support of `TLS_RSA_WITH_AES_128_CBC_SHA`, though. The reasons are documented here: https://docs.rs/rustls/0.17.0/rustls/manual/_02_tls_vulnerabilities/index.html#cbc-mac-then-encrypt-ciphersuites

**Comment by jacobgc** [comment]
Cheers ctz, 

I'm currently behind a proxy stopping me from using the tlsclient :( any chance you could test this subdomain for me, might rule out rustls and pin the issue on deno if it negotiates the same certificate: copernicus.discomap.eea.europa.eu

Thanks

**Comment by ctz** [comment]
Right, yes that server doesn't work with rustls. It looks like it's an old version of IIS10.
