### ISSUE TITLE
How do I load private keys from ring?

### ISSUE THREAD

**Issue by Andrew-Shay** [ctz/rustls#383]
# Problem

I'm having trouble loading keys that were generated with ring.
How do I load them properly?

# Generate keys with ring

I can successfully read these and sign a message in ring, so I think this is correct.
```rust
    // Generate a key pair in PKCS#8 (v2) format.
    let rng = rand::SystemRandom::new();
    let pkcs8_bytes = signature::Ed25519KeyPair::generate_pkcs8(&rng).unwrap();

    // Write key
    let mut key_pairf = File::create("F:\\rust_projects\\andrew-testing\\andrew.keypair").unwrap();
    key_pairf.write_all(pkcs8_bytes.as_ref()).unwrap();
```

# Attempt to load in rustls

```rust
    let mut key_pairf = File::open("F:\\rust_projects\\andrew-testing\\andrew.keypair").unwrap();
    let mut bufkey = io::BufReader::new(key_pairf);

    let keypair = rustls::internal::pemfile::pkcs8_private_keys(&mut bufkey).unwrap();
    println!("{:?}", keypair);
```
It just prints `[]` though :(
How do I properly load the keys in rustls?

**Comment by Ralith** [comment]
There's more to a TLS certificate than a key. rustls is not responsible for constructing valid certificates; you might be interested in [rcgen](https://crates.io/crates/rcgen).

**Comment by ctz** [comment]
> Generate keys with ring

This leaves andrew.keypair containing a DER encoding.

> Attempt to load in rustls

This expects a PEM-encoded file. If you have a DER-encoded file, you can load bytes out of it and put them straight into in a `rustls::PrivateKey`.

But I'd echo the use of rcgen for this purpose.

**Comment by Andrew-Shay** [comment]
Thanks, will do
