### ISSUE TITLE
More-specific error type for pemfile module

### ISSUE THREAD

**Issue by clarfonthey** [ctz/rustls#385]
Right now, all of the methods in the `internal::pemfile` module return errors of type `()`. It would be nice if these at least forwarded the `io::Error`s from their readers, although a custom error type could also be useful.

**Comment by ctz** [comment]
I plan to split internal::pemfile into a separate crate; wherein I'll be sure to change the interface to take more care in error handling.

**Comment by ctz** [comment]
This was done; see https://docs.rs/rustls-pemfile/0.2.0/rustls_pemfile/
