### ISSUE TITLE
A certificate is always required even for DH_anon ciphersuites

### ISSUE THREAD

**Issue by RipleyTom** [ctz/rustls#387]
I'm trying to use rustls to add a cryptography layer to transmissions between a client and a server and I tried to use DH_anon ciphersuites as server/client authentification is not a concern for me(yes I'm aware of the mitm implications).

But rustls seems to always require a certificate no matter the ciphersuite:
https://github.com/ctz/rustls/blob/881bdcb5f62da6128d51021d457129627aff3ff1/rustls/src/server/hs.rs#L627

I'm unsure if it's a limitation of rustls or if I'm missing something.

**Comment by Ralith** [comment]
Likely this just isn't a use case anyone else has thought about yet. Maybe you wouldn't need to change much to get it working?

**Comment by ctz** [comment]
rustls doesn't support this, and won't in the future -- for the same reasons that support for unauthenticated connections was dropped in the TLS1.3 standard. I'd suggest you follow the guidance here: https://tools.ietf.org/html/rfc8446#appendix-C.5
