### ISSUE TITLE
TLS error if message size >= `4*1024`.

### ISSUE THREAD

**Issue by amrx101** [ctz/rustls#388]
Set up.

On `2 way TLS` with self signed certs for broker and client. Whenever message size increases to 4096B, we get the following error.

 ```ERROR rustls::session > TLS alert received: Message {
    typ: Alert,
    version: TLSv1_3,
    payload: Alert(
        AlertMessagePayload {
            level: Fatal,
            description: InternalError,
        },
    ),
}```

On initial investigation it seems that error originates from [here](https://github.com/ctz/rustls/blob/881bdcb5f62da6128d51021d457129627aff3ff1/rustls/src/client/mod.rs#L556).

**Comment by ctz** [comment]
rustls does not send alerts with description=internal_error; this error is coming from the peer. Could you give detailed reproduction steps?

**Comment by amrx101** [comment]
Hi,

1. Set up a client.
2. Add `ca_config` to client.
3. Add client cert and key to client config.
4. Start the client.
5. Send a payload of specified size.

We get this error.

**Comment by amrx101** [comment]
@ctz ,

- Is the origin of the message peer and not `Rustls` client?
- How can I confirm that the message originates from the server?
-

**Comment by ctz** [comment]
- Yes
- Take a packet capture, with SSLKEYLOG output from at least one peer.

Please could you include precise version and configuration information for the server?

**Comment by amrx101** [comment]
@briansmith , I had an interesting discovery debugging this.So basically the `mtu` of the network I was trying to send data to was limited to `4075` and I was sending payload greater than that.

I used `set_mtu` in `ClientConfig` to to set the `mtu` size  to 4075.  I discovered this by comparing the packets sent out by a `Golang` TLS client and our `Client`. Apparently `Golang` TLS client has a mechanism of discovering and setting `MTU` using this [heuristics](https://www.igvita.com/2013/10/24/optimizing-tls-record-size-and-buffering-latency/).

Would you be open to a PR that does something similar in a separate issue.

**Comment by briansmith** [comment]
@amrx101 That's a question for @ctz.

**Comment by amrx101** [comment]
@briansmith , Yup, I tagged you wrongly. My bad.
