### ISSUE TITLE
Can't I use std::io::Read::read(&[u8]) for ClientSession?

### ISSUE THREAD

**Issue by qiujiangkun** [ctz/rustls#396]
Now I have
```rust
let mut vec = vec![];
client.read_to_end(&mut vec);
```
and
```rust
let mut buf = [0u8; 10000];
client.read(&mut buf);
```
The first example works fine but the second doesn't work. It always returns Ok(0). I want to use &[u8] instead of Vec<u8> for my project.

**Comment by djc** [comment]
By itself, this doesn't make much sense. Please add a fully worked example (if you still have this problem) so that someone can reproduce the issue you're seeing.

**Comment by qiujiangkun** [comment]
An example would like this. The version I used was in non-blocking mode and my Rust toolchain was on another computer. If this compiles and works, I will update that code.

It's not really a problem for me anymore, since I switched to `rustls::Stream` instead of encapsulating everything by myself. Maybe SSL does not support read a certain amount of bytes, I am not sure.

Btw, TcpStream::read_to_end() seems not working properly and missing the first few data in non-blocking mode, so I have to use TcpStream::read() instead. It(plus the ClientSession issue) was confusing to me until I figured it out.

```rust
use std::sync::Arc;

use std::net::TcpStream;
use std::io::{Read, Write, stdout};

use rustls;
use webpki;
use webpki_roots;

use rustls::Session;

fn main() {
    let mut config = rustls::ClientConfig::new();
    config.root_store.add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);

    let dns_name = webpki::DNSNameRef::try_from_ascii_str("google.com").unwrap();
    let mut sess = rustls::ClientSession::new(&Arc::new(config), dns_name);
    let mut sock = TcpStream::connect("google.com:443").unwrap();
    sess.write(concat!("GET / HTTP/1.1\r\n",
                      "Host: google.com\r\n",
                      "Connection: close\r\n",
                      "Accept-Encoding: identity\r\n",
                      "\r\n")
              .as_bytes())
        .unwrap();
    sess.write_tls(&mut sock);
    let mut plaintext = [0u8; 1024];
    sess.read_tls(&mut sock).unwrap();
    sess.read(&mut plaintext).unwrap();
    stdout().write_all(plaintext).unwrap();
}
```

**Comment by ctz** [comment]
```
    sess.write_tls(&mut sock);
```

Since `sock` here is in blocking mode, this will write the whole TLS ClientHello, but none of the remaining handshake and none of the application data.

```
    sess.read_tls(&mut sock).unwrap();
```

This will block until the server sends the reply to the handshake.

```
    let mut plaintext = [0u8; 1024];
    sess.read(&mut plaintext).unwrap();
```

No plaintext is available at this point, because the handshake has not finished. Therefore `Ok(0)` is the expected outcome.

I'd definitely that you continue to use `rustls::Stream` if you want blocking IO to work like this.
