### ISSUE TITLE
[Question] Can Rustls generate self signed certificate?

### ISSUE THREAD

**Issue by Geobert** [ctz/rustls#400]
Hi there, 

After looking in the documentation, it seems that it cannot, but I prefer to ask before pulling in another dependency to do it.

Can Rustls generate self signed certificate?

**Comment by Ralith** [comment]
tools for manipulating certificates are out of scope for rustls; you might be interested in [rcgen](https://crates.io/crates/rcgen).

**Comment by Geobert** [comment]
> 
> 
> tools for manipulating certificates are out of scope for rustls; you might be interested in [rcgen](https://crates.io/crates/rcgen).

thank you for your answer, I've seen this crate indeed, but I was just wondering to avoid another dep if possible :) I used that eventually :)
