### ISSUE TITLE
RUSTSEC-2019-0031

### ISSUE THREAD

**Issue by juarezr** [ctz/rustls#401]
This was reported by Rust [audit-check Action](https://github.com/actions-rs/audit-check):

## Warnings

[RUSTSEC-2019-0031](https://rustsec.org/advisories/RUSTSEC-2019-0031.html)

>    spin is no longer actively maintained

Details |  
-- | --
Status | unmaintained
Package | spin
Version | 0.5.2
URL | mvdnes/spin-rs@7516c80
Date | 2019-11-21

### Description

The author of the spin crate does not have time or interest to maintain it.

Consider the following alternatives (all of which support no_std):

- [conquer-once](https://github.com/oliver-giersch/conquer-once)
- [lock_api](https://crates.io/crates/lock_api) (a subproject of parking_lot)
   - [spinning_top](https://github.com/rust-osdev/spinning_top) spinlock crate built on lock_api
- [spinning](https://github.com/4lDO2/spinning-rs)

### More Info

mvdnes/spin-rs@7516c80

**Comment by ctz** [comment]
This is being tracked upstream at https://github.com/briansmith/ring/issues/921 -- I can't really deal with issues in dependencies of dependencies here.
