### ISSUE TITLE
[Question] Load a RSA private key with a passphrase

### ISSUE THREAD

**Issue by Geobert** [ctz/rustls#402]
Hi,

I can't find any function to load a private key which is protected with a passphrase.

What am I missing?

Thanks!

**Comment by ctz** [comment]
This isn't supported. That's for two reasons, really:

1. The standards involved are terrible:
    - standard methods of encrypting key material, specified back in 1993 by the PEM RFCs, are entirely inadequate for use with passphrases. This is what openssl uses by default if you ask for an encrypted key from `openssl genrsa`
    - later methods specified by PKCS#5 in 1993 and 1999 are also really very poor: `openssl req -newkey rsa:2048` does not sufficiently protect the passphrase against bruteforce.
    - compatibility with all this stuff would require having implementations of DES, 3DES, RC4, RC5, etc solely for this purpose; that seems like a bad complexity tradeoff.
2. There's not a valuable threat model addressed by having the private key encrypted at rest alongside the passphrase; but this is how this is typically used. People often check-in passphrase-protected private keys into configuration management, but actually (thanks to reason 1) does not provide good cryptographic security.

If you're worried about at-rest security of your private keys, I'd strongly recommend investigating whether your OS offers a key storage subsystem: macOS has the keychain, windows has CAPI-NG, linux has a big variety of options (like the kernel keyring, or keychain-like services offered by a desktop environments).

**Comment by Geobert** [comment]
I do understand but for the need of our project, I don't have much a choice for now :) I ended up parsing the PEM to extract which cipher to use and the IV and then decrypt it using some RustCrypto's crate :)
