### ISSUE TITLE
Get selected ALPN protocol

### ISSUE THREAD

**Issue by xpepermint** [ctz/rustls#405]
```rs
/// This represents a single TLS client session.
#[derive(Debug)]
pub struct ClientSession {
    // We use the pimpl idiom to hide unimportant details.
    pub(crate) imp: ClientSessionImpl,
}
```

How should I retrieve the ALPN protocol that was selected on a handshake? Access to this information is restricted. The `imp` should be public or the `ClientSession` should expose this.

```rs
session.imp.get_alpn_protocol()
```

**Comment by Ralith** [comment]
https://docs.rs/rustls/0.18.1/rustls/trait.Session.html#tymethod.get_alpn_protocol

**Comment by xpepermint** [comment]
Eh, silly me. I should include the trait `use rustls::{Session};`. Thanks @Ralith, for the tip.
