### ISSUE TITLE
Getting lots of "Resumption ignored, DHE_KE not offered" warnings

### ISSUE THREAD

**Issue by amouat** [ctz/rustls#410]
In the Trow project, we're currently using Rocket which in turn uses rustls. We recently updated and are now getting the following message throughout our logs:

```
[2020-09-29T13:12:26Z WARN  rustls::server::hs] Resumption ignored, DHE_KE not offered
```

It appears to originate in the TLS 1.3 code for rustls: https://docs.rs/crate/rustls/0.16.0/source/src/server/tls13.rs

The connection to Trow is started from Kubernetes, which presumably uses the standard Go http library.

I don't fully follow what the message means or why it occurs, so I may well have opened this issue in the wrong repo. If you think it's the fault of the Go library or something else, please let me know. If it's sort of expected behaviour and not indicative of a bug in the caller or rustls, could it be downgraded from a warning to info?

**Comment by ctz** [comment]
This is expected if the connect client is unwilling to do resumption. Likely our warning here is much too noisy -- nothing is really going wrong here.

**Comment by djc** [comment]
I pushed a proposal to downgrade it to debug, and reword the error a little bit.

**Comment by amouat** [comment]
Thanks @djc @ctz
