### ISSUE TITLE
write_vectored implementation are not atomic

### ISSUE THREAD

**Issue by carllerche** [ctz/rustls#418]
https://github.com/ctz/rustls/blob/716e7ec9b5a78a081f3727e505cb3871ea456d76/rustls/src/server/mod.rs#L682-L684

`write_vectored` should not write buffers in a loop. An error can happen in the loop, leaving the operation in an inconsistent state. If any data gets written, then the function call must succeed.

**Comment by ctz** [comment]
In practice send_some_plaintext was infallible, so I've reflected that in the types in 931560d
