### ISSUE TITLE
Question: How can I get the master_secret ?

### ISSUE THREAD

**Issue by NotBad4U** [ctz/rustls#422]
Hi,

I was unable to find a method that would allow to get the `master_secret` shared between the two peers in the connection. I found a structure which contain this key: [rustls/src/msgs/persist.rs#L59](https://github.com/ctz/rustls/blob/20a2c5811ad35c90de0737ad97e738037f6ca06f/rustls/src/msgs/persist.rs#L59), but not a way to access it from the [ClientSession](https://docs.rs/rustls/0.18.1/rustls/struct.ClientSession.html) and [SessionServer](https://docs.rs/rustls/0.18.1/rustls/struct.ServerSession.html).

Is there any way to perform that ?

For more context, we have an internal protocol where the sender and receiver run the regular SSL handshake which permits them to agree on a key `k`. The sender and receiver use `k` to derive three keys (e.g., using a pseudorandom generator).

Thank you in advance.

**Comment by djc** [comment]
You should `export_keying_material()` rather than relying specifically on the master key:

https://docs.rs/rustls/0.18.1/rustls/trait.Session.html#tymethod.export_keying_material
