### ISSUE TITLE
Consider exposing SessionSecrets 

### ISSUE THREAD

**Issue by thalesfragoso** [ctz/rustls#424]
I'm facing a protocol that uses TLS 1.2 for end-to-end security, but it also generates some keys to use at the protocol level, these keys are generated using HKDF and some of the session's secrets. So, I was thinking of exposing the `SessionSecrets` through the `Session` trait, which seems pretty straight forward. However, I'm not sure on how to deal with TLS 1.3.

I can craft a PR if this have good acceptance. Interest for this was already brought up in #198

**Comment by djc** [comment]
Is it impossible to do this using the data exposed by `Session::export_keying_material()`?

**Comment by thalesfragoso** [comment]
> Is it impossible to do this using the data exposed by Session::export_keying_material()?

In this case, yes. The procedure used has some similarities with `RFC 5705`, but enough differences to not allow this, unfortunately.

**Comment by ctz** [comment]
You can get at the secrets via the existing KeyLog trait. I don't really want to normalise or support this kind of use; it makes it too easy to introduce non-obvious cross-protocol attacks. The right, proper, and standard way to do this is exporters.

Out of interest, what is this protocol?

**Comment by thalesfragoso** [comment]
@ctz 

> You can get at the secrets via the existing KeyLog trait.

Hmm, it doesn't seem to expose the master random, or am I missing something ?

> Out of interest, what is this protocol?

https://usp.technology/
