### ISSUE TITLE
Weird empty if statement in extension processing

### ISSUE THREAD

**Issue by thomwiggers** [ctz/rustls#429]
https://github.com/ctz/rustls/blob/e35305b2c126ba5518cc6b4006ff70674f4e6586/rustls/src/server/hs.rs#L263

This line doesn't appear to be doing anything. Is there a special reason for it to be there?

**Comment by ctz** [comment]
Thanks for pointing that out; during refactoring the entire body of that branch ended up in `process_tls12()` so the branch should've been removed too.
