### ISSUE TITLE
Cloning a {Client, Server}Config without allocation

### ISSUE THREAD

**Issue by NeoLegends** [ctz/rustls#431]
Hey! In various parts of the client or server config I see `Vec<Vec<_>>`'s being used, while many of the other properties are arc-wrapped. Is there a specific reason why those lists cannot be `Arc<[Vec<_>]>` instead (leaving aside that this would break APIs obviously)? That would allow cloning the config (which I presume is done rather often) more cheaply, in particular, w/o allocations.

**Comment by djc** [comment]
As I understand it, the `ClientConfig` and `ServerConfig` are generally themselves wrapped in `Arc` (for example, for `ClientSession::new()` and `ServerSession::new()`, so if that's the only use then wrapping these fields wouldn't make much sense.
