### ISSUE TITLE
Module `pemfile` is private

### ISSUE THREAD

**Issue by Ekleog** [ctz/rustls#432]
Hello!

I know this is a duplicate of https://github.com/ctz/rustls/issues/310, but `rustls::pemfile` is still private, and is still referenced by eg. https://docs.rs/rustls/0.19.0/rustls/struct.Certificate.html and https://docs.rs/rustls/0.19.0/rustls/struct.PrivateKey.html .

I'll just use `rustls::internal::pemfile`, but FWIW my feeling about `::internal::` stuff is that it's probably something that should be `#[doc(hidden)]` and not encouraged — in which case maybe just updating the documentation for Certificate and PrivateKey to point to the right crate to use might be best?

I'm still learning how to use rustls (haven't completed a full application with it yet, just relying on the typechecker and hoping things to just work when I'll get to testing), but it looks quite neat, despite the few rough edges that can still be seen with stuff like the above.

Anyway, thank you for rustls! :D
  Leo

**Comment by ctz** [comment]
This has been moved wholesale to https://crates.io/crates/rustls-pemfile

**Comment by Ekleog** [comment]
Cool, thank you! I've just opened #434 to remove the references to rustls::pemfile from the documentation, so as to point people towards the new correct destination
