### ISSUE TITLE
TOFU

### ISSUE THREAD

**Issue by neezer** [ctz/rustls#435]
Very new to Rust & this library—so please pardon if this is a simplistic question—but looking to build a library for consuming the [gemini](https://gemini.circumlunar.space) protocol, which allows for TOFU (Trust on First Use) handling of certificates. Many of the Gemini sites serve with self-signed certs or CAs not found in more well-known trust stores like those from Google, Mozilla, or Apple. 

Is this possible with `rustls`? If so, can someone post a clear, minimal example I can try to parse through? I haven't found a tutorial/resource that actually implements TOFU with Rust yet... 🤷‍♂️ 

Much appreciated!

**Comment by Ralith** [comment]
This is possible by implementing the `ServerCertVerifier` trait and passing in your implementation via `ClientConfig::dangerous().set_certificate_verifier()`, exposed when the `dangerous_configuration` feature is enabled. `rustls-mio/examples/tlsclient.rs` has an option to do this, and may be a useful reference.
