### ISSUE TITLE
Per-session log facility

### ISSUE THREAD

**Issue by jsha** [ctz/rustls#438]
I'm working on defining [C bindings to rustls](https://github.com/abetterinternet/crustls) for [use in curl](https://github.com/curl/curl/pull/6350) and eventually Apache and hopefully other contexts.

I'd like to [add a log facility](https://github.com/abetterinternet/crustls/issues/24) so C code can register a handler to receive log lines. So, for instance, when you run `curl -vv`, you would see detailed logs from the rustls layer. Or if a program using libcurl registers a handler to receive debug logs, that handler would also receive rustls logs.

The problem I'm running into is that `log`'s state is global, and some client code has no global initializer where I can set up a log handler for crustls. Perhaps more importantly, a single global log handler would be incorrect. Imagine, for instance, if both libcurl and libgit link rustls, and one binary links both libcurl and libgit. Each library would want to receive log lines for its own connections in different ways.

It would be nice to have a per-session log capability. For instance, `ClientConfig` and `ServerConfig` could have a `logger: Log` field (https://docs.rs/log/0.4.13/log/trait.Log.html) that they would then pass on to Session. This would still be rather difficult to make work, though. There are a number of subcomponents besides `Session` that make use of the `log` crate. They would need to either gain a logger field or be passed a logger in the functions that do logging.

Is a change along these lines interesting to you? Do you see a better way to do it?

**Comment by ctz** [comment]
> It would be nice to have a per-session log capability

I agree. This might also be an improvement to the current feature-based fix for #22. I'll have a look at doing this.

(At present cargo features are not flexible enough to allow, for example, a user of hyper-rustls to turn off logging in rustls, unless hyper-rustls and tokio-rustls exposes the full set of all features for all their dependencies.)

**Comment by briansmith** [comment]
I think it is important that, if this feature were to be added, that it is zero-cost, or close to zero-cost, for the vast majority of applications that don't need it. If anything, Rustls should be changing in the opposite direction, to be *less* heavyweight. 

It also seems unlikely that you'll convince all the maintainers of all the crates you'd like to use, underneath Rustls or more directly, to introduce the complexity needed for that context-specific logging. I would expect you to soon depend on dozens if not hundreds of independently-maintained crates if your projects are anything like other projects I've worked on, so you can see how that won't scale. In the crustls project, perhaps you could create your own logging sink that controls this without the cooperation of Rustls and its dependencies, e.g. by fiddling with thread-local state before and after calling into Rust?

**Comment by djc** [comment]
I'm invested in coming up with a solution that address the curl/httpd use cases. Keying off of Brian's suggestion here, I think the best way to address this might be outside rustls. For example, `log` already works with a centralized `Log` instance. We could write a custom logger that includes an `Arc<Mutex<Option<T: Log>>>` so that the logger can be switched at runtime (before and after calling into rustls/switching sessions). It looks like the flexi_logger crate already allows stuff like this via its [`LoggerHandle` type](https://docs.rs/flexi_logger/0.17.1/flexi_logger/struct.LoggerHandle.html). @jsha do you think this would be a viable direction?

**Comment by jsha** [comment]
Yes, I think switching logging based on the current thread is viable, and is probably the best way to solve this. From https://github.com/icing/mod_tls/issues/2#issuecomment-800495123, we know that rustls will do all work on the thread it was invoked from.

Given that, I think we don't necessarily need special support from the `rustls` package. It should be possible to write a generic FFI log facility that calls a callback with some thread-local state. Ideally that would be its own, independent library. That way if a C project wants to link in both crustls and Hyper, the two libraries don't have to fight over registering a logger. Instead, the C project would link a third library, `ffi-log` or similar.

I'm happy closing out this issue on rustls if other folks here agree.
