### ISSUE TITLE
Add ability to configure server certificate resolvers

### ISSUE THREAD

**Issue by sciyoshi** [ctz/rustls#44]
The `ResolvesCert` trait is currently private, so it's not possible to provide a custom certificate resolver, which would be useful for providing different certificates based on the domain name in a request with SNI. However this may also require stabilizing/exposing the additional types in the `resolve()` interface, like `ServerNameRequest`, `SupportedSignatureAlgorithms`, `EllipticCurveList` and `ECPointFormatList`.

**Comment by ctz** [comment]
You're right, `ResolvesCert` was definitely intended to be part of the public interface but the reexport is missing. And `ServerNameRequest` should probably have been dropped to a &str in the public API.

**Comment by ctz** [comment]
Public as of 0.5.5
