### ISSUE TITLE
When verifying certificates, a single time should be used

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#440]
When verifying SCTs, we use two different calls to SystemTime::now(). One is used for the call into webpki:

```
fn try_now() -> Result<webpki::Time, TLSError> {
    webpki::Time::try_from(std::time::SystemTime::now())
        .map_err(|_| TLSError::FailedToGetCurrentTime)
}
```

and another is used for the call into sct.rs:
```
fn unix_time_millis() -> Result<u64, TLSError> {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|dur| dur.as_secs())
        .map_err(|_| TLSError::FailedToGetCurrentTime)
        .and_then(|secs| {
            secs.checked_mul(1000)
                .ok_or(TLSError::FailedToGetCurrentTime)
        })
}
```

I think it would be better to have a single time for which we're validating the certificate, i.e. a single call to `SystemTime::now()` for all aspects of certificate validation. I think this would be more logically correct. It would also be more efficient. (I also think webpki should just do the SCT validation so Rustls doesn't need to, and so Rustls can support SCTs within certificates; see https://github.com/briansmith/webpki/issues/177.) 

Also note that there is a third call to `SystemTime::now()` per handshake, which is used for ticket rolling. I think in terms of correctness, this duplication is not as important as the duplication between SCT and other certificate validation, but it isn't optimal w.r.t. performance.

**Comment by briansmith** [comment]
I think this should be closed because #442 fixes it. Is there anything remaining @djc?

**Comment by djc** [comment]
#442 didn't include the ticketer, maybe we should keep this open for that?

**Comment by briansmith** [comment]
The ticketer isn't about verifying certificates so maytbe we should just have a separate issue about that if people think it is important. I don't really think it is that urgent after looking into it.
