### ISSUE TITLE
Change randomness functions to return result

### ISSUE THREAD

**Issue by jsha** [ctz/rustls#441]
https://github.com/ctz/rustls/blob/a49f1117cad9082f1d0ccfd2ff45d3a336462f76/rustls/src/rand.rs#L2-L4

> /// The single place where we generate random material
> /// for our own use.  These functions never fail,
> /// they panic on error.

Because ring's SystemRandom is implemented in terms of fallible system operations, it would be good to propagate errors and return them as Result. This is helpful in presenting an API that never panics, which makes the C API much easier.

**Comment by djc** [comment]
I gave this a spin to see what it would feel like in #443. As could be expected, it is highly invasive, and I'm not sure this is the best direction. Would be happy to continue if Joe thinks it is the way to go.

**Comment by briansmith** [comment]
It's important to point out that not every platform provides an infallible randomness API. In particular, WASI doesn't, and WASI is an important target to support. Even Linux really doesn't, in a variety of scenerios, especially at early boot. So I think this isn't really something that should be controversial. I think @djc's PR doesn't make the code messy.
