### ISSUE TITLE
Customizing ALPN on a per-hostname basis

### ISSUE THREAD

**Issue by jsha** [ctz/rustls#444]
The [ACME TLS-ALPN challenge](https://tools.ietf.org/html/rfc8737) allows web servers to perform domain validation at the TLS layer (rather than the HTTP layer). For instance, Apache's mod_md uses it: https://httpd.apache.org/docs/trunk/mod/mod_md.html. The definition says:

> 4.  acme-tls/1 Protocol Definition
>   The "acme-tls/1" protocol MUST only be used for validating ACME tls-
>   alpn-01 challenges.  The protocol consists of a TLS handshake in
>   which the required validation information is transmitted.  The "acme-
>   tls/1" protocol does not carry application data.  Once the handshake
>   is completed, the client MUST NOT exchange any further data with the
>   server and MUST immediately close the connection.

To implement this in rustls, it would be useful to (a) have a way to configure accepted ALPN protocols on a per-hostname basis, rather than on a per-ServerConfig basis, and (b) access the ALPN protocol from a `ServerSession`

**Comment by djc** [comment]
I think (b) already exists? https://docs.rs/rustls/0.19.0/rustls/trait.Session.html#tymethod.get_alpn_protocol

For (a), see the discussions in #89.

**Comment by jsha** [comment]
Ah, thanks for pointing that out. I was indeed looking for the method on `ServerSession`, but now that I think about it it makes sense to have it on `Session`. And 👍🏻 on the pointer to #89.

**Comment by djc** [comment]
If you think there's something needed here that is not covered, it would be useful to point that out here. Otherwise, perhaps it makes sense to close this issue for now?
