### ISSUE TITLE
Way to fetch the peer certificate without performing client authentication?

### ISSUE THREAD

**Issue by abusch** [ctz/rustls#446]
I'm trying to write a toy [syncthing](https://syncthing.net/) client for fun. In syncthing, all peers have a self-signed certificate and private key that identifies them. When 2 peers connect to each other, they present their certificate as part of the TLS handshake, but they don't perform client authentication. They each use the peer's certificate to compute the peer's device id. To achieve this, the original golang source uses the `RequestClientCert` value as the `ClientAuthType` (see https://golang.org/pkg/crypto/tls/#ClientAuthType). 

However, there doesn't seem to be a way to do this with `rustls`. As far as I could see, `NoClientAuth` skips client authentication, but doesn't fetch the peer certificate, and both `AllowAnyAuthenticatedClient` and `AllowAnyAnonymousAuthenticatedClient` request the certificate but try to do client authentication...

The way I worked around it is by enabling the `dangerous_configuration` feature and implementing my own `ClientCertVerifier`. I'm just wondering if there is something I missed, or if something similar to go's `RequestClientCert` should be added? Note that I know very little about all of this, so maybe there is a good reason why this is not possible in rustls :sweat_smile:

**Comment by djc** [comment]
I think you're right that there's no built-in way to do exactly that, but the use case seems rare enough that building a custom `ClientCertVerifier` is a decent way to implement it. In general, trusting self-signed certificates is dangerous since it enables person-in-the-middle attacks, so I think that's why you need to enable `dangerous_configuration` to build something like this.

**Comment by abusch** [comment]
Fair enough, thanks for the answer.

**Comment by briansmith** [comment]
I think this should be closed based on the above discussion.

**Comment by abusch** [comment]
Closing as discussed.
