### ISSUE TITLE
Document how to install the correct version of rustfmt (2.x) for Rustls

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#448]
I messed up some PRs I had in progress because I instinctively typed `cargo fmt` which reformatted too much code using the stable version of rustfmt. This wasted an annoying amonut of effort. I know @ctz reformatted the code recently with rustfmt 2.x but I could not figure out how to install rustfmt 2.x or which exact revision of rustfmt 2.x is being used. It would be very helpful for contributors to document this.

**Comment by djc** [comment]
IMO it should just get checked in CI - that also has the advantage that, for smaller changes you can just make the changes manually rather than chasing down the right version of rustfmt. (I'm still a little unclear on what the non-standard version of rustfmt provides over stable or even just nightly rustfmt.)

**Comment by briansmith** [comment]
I would prefer to just use the latest stable rustfmt but the most important thing for me is that I need to know the installation instructions for the version that is to be used.

**Comment by djc** [comment]
FWIW, I would prefer the latest stable, too. The common version ~everyone is uses is better even if the particular style it generates is not optimal. (Adding a `rustfmt.toml` with options that work on stable is also fine, of course.)

**Comment by ctz** [comment]
> I'm still a little unclear on what the non-standard version of rustfmt provides over stable or even just nightly rustfmt

https://github.com/ctz/rustls/pull/327#issuecomment-570077354 covers it, I think.

Instructions for installing rustfmt v2 are in their readme, but:

```
$ git clone git@github.com:rust-lang/rustfmt.git
$ cd rustfmt
$ git checkout 21130bc0 # current top of master
$ export CFG_RELEASE=nightly
$ export CFG_RELEASE_CHANNEL=nightly
$ cargo install --path . --force --features rustfmt,cargo-fmt
```

This was with:

```
rustc 1.51.0-nightly (368275062 2021-02-02)
```

**Comment by djc** [comment]
#478 sets up CI to run this.
