### ISSUE TITLE
SessionId::len

### ISSUE THREAD

**Issue by manuels** [ctz/rustls#45]
Quick question about SessionID:

    #[derive(Copy)]
    pub struct SessionID {
        len: usize,
        data: [u8; 32],
    }

Is there a reason why this is not simply a `Vec`?
Having a `len` field makes this data type a bit clumsy/non-rusty.

**Comment by ctz** [comment]
It used to be a vec, but got optimised to be a externally sized array to avoid an extra interior allocation. Perhaps a premature optimisation, because I don't think the difference was necessarily measured before and after.

**Comment by briansmith** [comment]
This is basically a simplified implementation of `ArrayVec`. You could try using `ArrayVec` instead.

**Comment by manuels** [comment]
Ok, I was just wondering because I need a similar data structure for DTLS cookies (with a max capacity of 255).
