### ISSUE TITLE
Eliminate all uses of the `is_none()`/`unwrap()` anti-pattern

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#453]
There are many places in the code that have this pattern:

```
if maybe_x.is_none() {
    <send an alert or log or something>
    return Err(...);
};
let x = maybe_x.unwrap();
```

All, or almost all of these, can be rewritten to avoid `unwrap()`, which would make the code more clearly correct. I have submitted PRs to demonstrate various ways of doing this: PR #449, PR #450, PR #451, PR #452.

To find instances of this anti-pattern, search the code for `is_none` and then look for uses of `unwrap()` on the same value.

**Comment by briansmith** [comment]
If you are interested in working on this cleanup, please submit some PRs, one per instance. I am happy to pre-review them before @ctz.

**Comment by briansmith** [comment]
Also, I suggest that you address the instances in the the `rustls/src` directory first; i.e. I suggest we fix the instances in the Rustls library proper before fixing the examples and the tests.

**Comment by ab-cgh** [comment]
Once either https://github.com/ctz/rustls/pull/505 or https://github.com/ctz/rustls/pull/497 is merged, that should be all of the cases in `rustls/src` taken care of. I have not updated any examples.

**Comment by djc** [comment]
I'll close this, since the library instance of this have been addressed and it doesn't matter that much for examples and tests IMO.
