### ISSUE TITLE
RFC 8446 Section D.4 fake session ID compatibility hack is missing during resumption

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#470]
In PR #464, @dhobsd pointed out that Rustls doesn't implement the RFC 8446 Section D.4 fake session ID workaround:

> The client always provides a non-empty session ID in the ClientHello, as described in the legacy_session_id section of Section 4.1.2.

I am not sure how important it is to implement this workaround. Maybe there are no more compatibility issues? I would prefer to not implement it unless somebody shares compelling and recent data indicating the the compatibility issue still exists.

/cc @davidben

**Comment by dhobsd** [comment]
I pointed it out because someone hit this issue using an SMB-class firewall that hadn't had version updated in a while. That happened a week ago.

**Comment by davidben** [comment]
Yeah, I wouldn't expect the need for D.4 to go away for the foreseeable future. The non-compliant firewalls were rampant, slow to upgrade, and I doubt all the vendors even have fixes. After all, the protocol worked around them. It's disappointing, but the alternative was everyone shipping an insecure fallback, so it was the right call.

Note Rustls already tries to implement D.4. It's got the ChangeCipherSpec logic and even fills in a random session ID here. The problem simply is a bug: you all the missed the resumption case.
https://github.com/ctz/rustls/blob/main/rustls/src/client/hs.rs#L213

**Comment by briansmith** [comment]
as @dhobsd pointed out in the PR, `EmptySessionID-TLS13` tests this as of https://boringssl.googlesource.com/boringssl/+/c5e4538e3b0bcfdda30d2dabecbee952faf54c1c.

**Comment by briansmith** [comment]
> Note Rustls already tries to implement D.4. It's got the ChangeCipherSpec logic and even fills in a random session ID here. The problem simply is a bug: you all the missed the resumption case.

OK, then I don't have any objection to doing this.

**Comment by briansmith** [comment]
Issue #502 fixes this. @dhobsd do you agree?

**Comment by dhobsd** [comment]
I think it was corrected in #527, but agree this can be closed due to that.
