### ISSUE TITLE
SCTs should be passed to the cert verifier so the cert verifier can enforce CT

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#480]
Consider the case where one is using a platform-provided certificate verifier, or another custom certificate verifier, where the certificate verifier has its own CT enforcement. Rustls doesn't pass the SCTs from the handshake to the certificate verifier so CT doesn't work in this scenario.

Further, when the cert verifier has support for SCTs embedded into X.509 certificates, the built-in CT support may cause verification to fail when the cert verifier's CT verification would succeed.

In general, CT verification cannot be separated from certificate verification.

Proposal: Move all the CT support from the handshake logic to the default implementations of the certificate verification traits. Remove the `ct_logs` client configuration option; instead the user will need to configure CT in the certificate verifier implementation it chooses.

This is related to #479 but somewhat orthogonal.

**Comment by ctz** [comment]
Pretty sure this is addressed now.
