### ISSUE TITLE
Share RootCertStore between ClientConfigs

### ISSUE THREAD

**Issue by brson** [ctz/rustls#5]
Building `RootCertStore` is expensive. I expect to want a single instance for my entire app, but multiple `ClientConfigs`, and I don't want to rebuild the cert store. If it was `Arc`d then I could reuse it.

**Comment by briansmith** [comment]
A normal application should also share `ClientConfig`s across all connections. it would likely be pretty rare to need multiple `ClientConfig`s. Most likely if you need different configs you need different trust stores too.

**Comment by brson** [comment]
Yeah I suppose I was thinking you might change the ciphersuites, but I can't think of any reason to do that.
