### ISSUE TITLE
Document read_tls returning 0

### ISSUE THREAD

**Issue by P-E-Meunier** [ctz/rustls#50]
As far as I can tell from the source, whenever `read_tls` returns `Ok(0)`, it means the socket was just closed. This might be obvious, but still should appear in the documentation.

**Comment by ctz** [comment]
https://docs.rs/rustls/0.5.6/rustls/trait.Session.html#tymethod.read_tls hopefully that covers it now.

**Comment by P-E-Meunier** [comment]
Great, thanks!
