### ISSUE TITLE
"received fatal alert: HandshakeFailure" on some websites

### ISSUE THREAD

**Issue by Shnatsel** [ctz/rustls#512]
Trying to connect via HTTPS using `rustls` results in the following failure on 1750 websites out of the top 1 million:

> received fatal alert: HandshakeFailure

Firefox and curl (OpenSSL) work fine.

Example website where it's happening: http://java-forums.org

At a glance I don't see any reason why it should not work - it uses TLS 1.2 with modern cipher suites.

I have reproduced it in `reqwest`, `ureq`, `hreq` and `zeptohttpc` clients. Full test code used can be found here: https://github.com/Shnatsel/rust-http-clients-smoke-test

List of all occurrences of this error, together with test tool output: [ureq-handshake-failure.tar.gz](https://github.com/ctz/rustls/files/5983090/ureq-handshake-failure.tar.gz)

Top million websites is from the [Tranco list generated on the 3rd of February](https://tranco-list.eu/list/3G6L/)

**Comment by quininer** [comment]
The [scan report of ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=java-forums.org) show that java-forums.org does not support any Forward Secrecy cipher suites and did not provide a complete certificate chain. I think these will cause handshake to fail.

I suggest HandshakeFailure can provide a reason field.

**Comment by ctz** [comment]
I'm actually reasonably happy that the failure rate here is as low as 0.175%

> I suggest HandshakeFailure can provide a reason field.

This isn't possible, because HandshakeFailure is a TLS alert and sadly those don't come with any more information :(

In the case of java-forums.org it seems like #381 covers this.

**Comment by Shnatsel** [comment]
Yeah, the error rate is surprisingly low for the top 1M websites (based on my preliminary analysis, anyway). I'll learn more in the coming days.

**Comment by Shnatsel** [comment]
I'll close this, since it seems to be WAI and there's no way to surface more info.

**Comment by Shnatsel** [comment]
FYI, rustls fails on roughly 1% of websites out of the top million due to the mismatch in the set of supported cypher suites. But Only 59% of the top 1M websites use HTTPS, so the real failure rate is closer to 2%.

This also appears to be WAI, so I won't open an issue about that. More info can be found at https://github.com/algesten/ureq/issues/318

**Comment by Darkspirit** [comment]
> so the real failure rate is closer to 2%.

[Firefox Beta 86 telemetry](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2021-02-11&include_spill=0&keys=__none__!__none__!__none__&max_channel_version=beta%252F86&measure=SSL_CIPHER_SUITE_FULL&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_by_value=0&sort_keys=submissions&start_date=2021-01-25&table=0&trim=1&use_submission_date=0) seems to confirm this. ([Legend](https://searchfox.org/mozilla-central/rev/b32d4ca055ca9cf717be480df640f8970724a0ce/security/manager/ssl/nsNSSCallbacks.cpp#878))

| id | ciphersuite | percentage |
| --- | --- | --- |
| 6 | TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA | 0.01% |
| 4 | TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA | 0.02% |
| 3 | TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA | 0.2% |
| 5 | TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA | 0.33% |
| 69 | TLS_RSA_WITH_AES_256_GCM_SHA384 | 0.95% |
| 68 | TLS_RSA_WITH_AES_128_GCM_SHA256 | 0.79% |
| 63 | TLS_RSA_WITH_AES_256_CBC_SHA | 0.36% |
| 61 | TLS_RSA_WITH_AES_128_CBC_SHA | 0.33% |
| 66 | TLS_RSA_WITH_3DES_EDE_CBC_SHA | 0.01% |
| | | sum: 3%

java-forums.org wouldn't require plain RSA: https://www.ssllabs.com/ssltest/analyze.html?d=java-forums.org
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384

The gov domain @briansmith mentioned on [Twitter](https://twitter.com/BRIAN_____/status/1361442494429294597) wouldn't need plain RSA either: https://www.ssllabs.com/ssltest/analyze.html?d=egov.ice.gov
> TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384

Rustls eagerly awaits:
* https://bugs.chromium.org/p/chromium/issues/detail?id=658905 Deprecate RSA+SHA-1 from TLS 1.2 (https://github.com/briansmith/webpki/issues/110)
* https://bugs.chromium.org/p/chromium/issues/detail?id=1078469 Drop RSA key exchange

Hopefully Rustls can simply wait and avoid such legacy cipher suites.
