### ISSUE TITLE
no server certificate chain resolved

### ISSUE THREAD

**Issue by andrewbanchich** [ctz/rustls#514]
I'm trying to set up mTLS using rustls / tide / tide-rustls, but I'm kind of new to this. What I want to do is configure a server to only accept connections from clients which use a cert that was created by a root CA I trust.

To do this I'm using: https://docs.rs/rustls/0.19.0/rustls/struct.AllowAnyAuthenticatedClient.html

So far, what I have is this:

        // CA public key
        let ca_path = format!("{}/ca.pem", std::env::var("CERT_DIR").unwrap());
        let mut ca = BufReader::new(File::open(ca_path).unwrap());
    
        let mut cert_store = RootCertStore::empty();
        cert_store.add_pem_file(&mut ca).unwrap();
    
        let verifier = AllowAnyAuthenticatedClient::new(cert_store);
        let tls_config = ServerConfig::new(verifier);

This is compiling okay, but when I try making a request using this Reqwest Client:

        let mut pem = Vec::new();
    
        let key_path = format!(
            "{}/test-pkcs8-key.pem",
            std::env::var("CERT_DIR").unwrap()
        );
        std::fs::File::open(key_path)
            .unwrap()
            .read_to_end(&mut pem)
            .unwrap();
    
        let cert_path = format!("{}/test.pem", std::env::var("CERT_DIR").unwrap());
        std::fs::File::open(cert_path)
            .unwrap()
            .read_to_end(&mut pem)
            .unwrap();
    
        let identity = reqwest::Identity::from_pem(&pem).unwrap();
    
        let mut buf = Vec::new();
        let ca = format!("{}/ca.pem", std::env::var("CERT_DIR").unwrap());
        std::fs::File::open(ca)
            .unwrap()
            .read_to_end(&mut buf)
            .unwrap();
        let ca = reqwest::Certificate::from_pem(&buf).unwrap();
    
        let client = reqwest::Client::builder()
            .add_root_certificate(ca)
            .identity(identity)
            .build()
            .unwrap();

it produces an error: `error unexpected error: no server certificate chain resolved`.

I'm not sure what this means. How can I fix this?

Thanks

**Comment by djc** [comment]
Is it possible you haven't configured the actual certificate for the server to use? I think you need to call `tls_config.set_single_cert()` on the server side.

**Comment by andrewbanchich** [comment]
That would help, wouldn't it? 😄 That worked, thanks!
