### ISSUE TITLE
Performance: Unnecessary cloning of handshake message contents during handshaking

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#519]
There are two macros that do the same thing, `require_handshake_msg!` and `require_handshake_msg_mut!`. The former returns the message contents by reference (`&Vec<u8>`) whereas the latter returns the message contents by value.

When `require_handshake_msg!` is used, frequently it is the case that the returned reference is cloned, where if `require_handshake_msg_mut!` were used the clone would be avoided. For example, this happens in `ExpectCertificate::handle` which causes us to clone the entire certificate chain, which can be huge.

We should audit all the places where we're calling `clone()`, especially when we're cloning the result of `require_handshake_msg!`, and refactor that code to avoid the cloning.

**Comment by briansmith** [comment]
Further, there may be no reason for `require_handshake_msg!` to exist. It seems like `require_handshake_msg_mut!` should be able to replace it for most uses, and maybe all. If so, we should delete `require_handshake_msg!` and rename `require_handshake_msg_mut!` to `require_handshake_msg!`.

**Comment by djc** [comment]
After thinking about this (and implementing some transformations like this), I wonder if this isn't the wrong way around. Currently an incoming `Message` will contain a bunch of allocated memory, which I think at least conceptually could be owned by the original message buffer (although we'll need to simplify some of the layering in `ServerSession`/`ClientSession`). We would then only clone the bytes we need into the handshake state as necessary, and do so only when transitioning to the next state.

**Comment by briansmith** [comment]
Yes, I also came to a similar conclusion, and I think that's the right way to go if somebody is willing to take the time to refactor the underlying layers. Also ideally the certificate validation API would change so that no cloning is required just for the purpose of validating the certificate. Similarly, the validation of the certificate should start earlier in the handshake so that less state is required to be carried into the next state. Put another way: Ideally, it would be possible to validate the certificate chain without any heap allocations.

The above is specific to certificate messages, but the idea generalizes.

**Comment by djc** [comment]
I am happy to spend time on that, but at the current review pace it will likely take a while to get there.

**Comment by ctz** [comment]
> Further, there may be no reason for require_handshake_msg! to exist. 

Fixed in 837acd5 -- see note in the commit message for why this needs to exist.
