### ISSUE TITLE
"Session" terminology is confusing; `{Client,Server}Session` should be `{Client,Server}Connection`

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#525]
When describing to people how TLS sessions work in the context of Rustls, the fact that Rustls calls connections "sessions" makes things very confusing. There is a 1:N relationship between sessions:connections. Since we've been making breaking API changes, it seems like a good time to fix this naming.

**Comment by djc** [comment]
Do you mean that rustls' `Session` type's lifetimes are tied to the transport-level connection, and a conceptual TLS session can be resumed across multiple `Session`s (each of which has a 1:1 relationship to a transport-level connection)? Does the RFC also use the term "connection" for what rustls currently calls a `Session`?

**Comment by briansmith** [comment]
> Do you mean that rustls' `Session` type's lifetimes are tied to the transport-level connection, and a conceptual TLS session can be resumed across multiple `Session`s (each of which has a 1:1 relationship to a transport-level connection)? Does the RFC also use the term "connection" for what rustls currently calls a `Session`?

Yes. And basically yes.

**Comment by djc** [comment]
Okay, I guess this makes sense to me then.

(If we're going around changing this, my pet peeve is the use of `TLSError` vs `TlsError` -- the latter style is preferred in the API guidelines and is used pretty much everywhere -- there's also `AEADTicketer`.)

**Comment by briansmith** [comment]
> (If we're going around changing things, my pet peeve is the use of `TLSError` vs `TlsError` -- the latter style is preferred in the API guidelines and is used pretty much everywhere -- there's also `AEADTicketer`.)

I think we should have another issue about complying with the Rust naming conventions for people to discuss that, which is orthogonal.

**Comment by ctz** [comment]
Done in 9ee16c4c
