### ISSUE TITLE
Use #[cfg(test)] or cfg!(test) instead of DANGEROUS_DISABLE_VERIFY

### ISSUE THREAD

**Issue by heartsucker** [ctz/rustls#53]
This is pedantic, but perhaps you should make it impossible for someone to foot-gun themselves by eliding dangerous features at compile time.

**Comment by alex** [comment]
`DANGEROUS_DISABLE_VERIFY` has been superseded by the `dangerous_configuration` feature, so I think this can be closed.

**Comment by ctz** [comment]
Yes, good point.
