### ISSUE TITLE
Support SSL_CERT_FILE/SSL_CERT_DIR

### ISSUE THREAD

**Issue by pimterry** [ctz/rustls#540]
OpenSSL supports `SSL_CERT_FILE` and `SSL_CERT_DIR` to allow configuration of CA certificates in an application without making code changes. It would be very helpful if rustls also supported this.

This is a pretty widely used feature (a quick search shows them cumulatively appearing about 200,000 times in scripts, sources & docs on github alone). It's especially useful when you want to reconfigure an application that's _not_ your own, where needing to change the code itself would be very inconvenient. By using these env vars, you can automatically reconfigure applications so they work happily in enterprise environments with internal cert infrastructure, with HTTPS debugging tools, or when using self-signed certs in development.

For a general purpose reconfiguration like this, it's very inconvenient to require every end application author to check for and use env vars themselves (and in practice, when they do, they each use a different env var - e.g. Cargo supports this manually via its own CARGO_HTTP_CAINFO - where a single global env var would be much better).

I can imagine this might be an OpenSSL feature that's considered risky, since it takes TLS configuration from the environment, but if an attacker can inject arbitrary environment variables they can already do things like setting LD_PRELOAD or even just PATH to exert almost complete control over the application being run regardless. Notably almost all other platforms allow SSL configuration in env vars in some form, e.g. the JVM via options with JAVA_TOOL_OPTIONS, node via NODE_EXTRA_CA_CERTS, anything using OpenSSL via SSL_CERT_FILE, etc etc.

Providing the same here would effectively add this widely used & supported capability to the rust ecosystem too, matching other platforms and working out of the box with existing OpenSSL configurations.

**Comment by briansmith** [comment]
@pimterry I think this should be filed in https://github.com/ctz/rustls-native-certs instead.

**Comment by pimterry** [comment]
Agreed, that makes complete sense, thanks @briansmith. I've filed a new issue there, I'll close this.
