### ISSUE TITLE
access to negotiated protocol values?

### ISSUE THREAD

**Issue by icing** [ctz/rustls#543]
I tried to find a way to retrieve the negotiated vales of a `ServerSession` regarding protocol version and ciphers selected. Is there a way to get those?

Thanks for the help.

Background: in Apache, we expose those values from our existing ssl module to other components and running applications and I would like the upcoming `mod_tls` to do the same.

**Comment by djc** [comment]
`ServerSession` implements [`Session`](https://docs.rs/rustls/0.19.0/rustls/trait.Session.html), so you should be able to use its methods (so in this case `get_protocol_version()` and `get_negotiated_ciphersuite()`, I think?).

**Comment by icing** [comment]
I suspected I was overlooking something. Thanks for the pointer and sorry for the noise.
