### ISSUE TITLE
Consider returning Arc from ResolvesServerCert

### ISSUE THREAD

**Issue by fd** [ctz/rustls#566]
Currently `ResolvesServerCert` returns a `CertifiedKey` as is. This means that all implementations of `ResolvesServerCert` must make a full clone of the `CertifiedKey`. Returning a `Arc<CertifiedKey>` instead would prevent the full clone.

```diff
- pub fn resolve(&self, client_hello: ClientHello<'_>) -> Option<CertifiedKey>
+ pub fn resolve(&self, client_hello: ClientHello<'_>) -> Option<Arc<CertifiedKey>>
```

Are there any reasons for not doing this? I may be overlooking something.
I'd be willing to prepare a PR.

**Comment by djc** [comment]
Yeah, I think this makes sense. Please submit a PR!

**Comment by djc** [comment]
This is done.
