### ISSUE TITLE
no_ecdhe test is failing

### ISSUE THREAD

**Issue by sayrer** [ctz/rustls#568]
It looks like OpenSSL's s_server doesn't have a `-no_ecdhe` option, so this test is skipped. LibreSSL's s_server does have this option, so the test runs and fails. 

```
sayrer@sayrers-air ~ % which openssl  
/usr/bin/openssl
sayrer@sayrers-air ~ % openssl version
LibreSSL 2.8.3
sayrer@sayrers-air ~ % openssl s_server -help 2>&1 | grep no_ecdhe 
 -no_ecdhe     - Disable ephemeral ECDH
sayrer@sayrers-air ~ % brew --prefix openssl
/opt/homebrew/opt/openssl@1.1
sayrer@sayrers-air ~ % /opt/homebrew/opt/openssl@1.1/bin/openssl version
OpenSSL 1.1.1j  16 Feb 2021
sayrer@sayrers-air ~ % /opt/homebrew/opt/openssl@1.1/bin/openssl s_server -help 2>&1 | grep no_ecdhe
sayrer@sayrers-air ~ %
```

The test for this option is here: https://github.com/ctz/rustls/blob/552475df50572f01ff85be4c2a3d663a68fd4dc2/rustls-mio/tests/common/mod.rs#L231

**Comment by ctz** [comment]
Could you include a copy of the panic message on failure with LibreSSL?

I'm minded to delete this test, as really it's not contributing to any coverage and mostly is testing that openssl's no_ecdhe option works.

**Comment by sayrer** [comment]
I hacked "-no_ecdhe" into the default arguments to see if it was doing anything, and it did break the curves.rs tests, but not the `no_ecdhe` test in errors.rs.
  
This will load LibreSSL 2.8.3 on Big Sur:

`rustls-mio % RUST_BACKTRACE=1 OPENSSL_DIR=/usr cargo test`

[panic.txt](https://github.com/ctz/rustls/files/6144078/panic.txt)

**Comment by ctz** [comment]
OK, thanks. That output clearly shows that -no_ecdhe doesn't work, thought I can't find an upstream bug. 🤷🏽

**Comment by sayrer** [comment]
Yeah... I was kind of assuming the test args were buggy in some way, but it seems like either `-no_ecdhe` doesn't work as we expected, or it's just buggy.

**Comment by ctz** [comment]
Deleted in fd6d63d

**Comment by sayrer** [comment]
@briansmith I believe these tests should now work with Big Sur's bundled LibreSSL 2.8.3, either by relying on the new detection code, or by using "OPENSSL_DIR=/usr" on the command line.

I tried LibreSSL 3.4.2 from https://formulae.brew.sh/formula/libressl, and it broke 4 or 5 tests.
