### ISSUE TITLE
ALL_PROTOCOL_VERSIONS

### ISSUE THREAD

**Issue by icing** [ctz/rustls#577]
Suggestions: it would be useful to have all implemented `ProtocolVersion` in rustls available for iteration. similar so the supported cipher suites.

Background: `mod_tls` would like to make the minimal tls protocol version configurable. `TLSv1.3+` would indicate that version, plus all numerically higher ones that rustls supports. In addition, this would also allow warnings to be issued on configurations that rustls (no longer) supports.

**Comment by icing** [comment]
In addition to this, I propose the `ProtocolVersion` to follow the `Unknown(u16)` pattern of other, IANA defined  properties. Or make the distinction between `ProtocolVersion` and `SupportedProtocolVersion`, if that makes certain matches easier.

**Comment by djc** [comment]
`ProtocolVersion` seems to already follow that pattern? https://docs.rs/rustls/0.19.0/rustls/enum.ProtocolVersion.html

**Comment by icing** [comment]
> `ProtocolVersion` seems to already follow that pattern? https://docs.rs/rustls/0.19.0/rustls/enum.ProtocolVersion.html

You are correct. I misread the enum_builder macro here and should have read the documentation instead!
