### ISSUE TITLE
server support for MaxFragmentLength

### ISSUE THREAD

**Issue by bobmcwhirter** [ctz/rustls#585]
I've an embedded system with constrained resources, attempting to negotiate MaxFragmentLength extension with the server during ClientHello.

Seems rustls ignores that extension when supplied by the client, but enums.rs does acknowledge that the extension exists, along with the presence of the Fragmenter type. But it seems Fragmenter is statically configured for the server, and not on a per-connection negotiation with the client.

**Comment by djc** [comment]
Do you need that particular extension, or just something that works in the constrained environment? I was reading up on max_fragment_length and it looks like there's a [newer RFC](https://tools.ietf.org/html/rfc8449) that covers similar use cases.

**Comment by bobmcwhirter** [comment]
Just something negotiable. Happy to use record_size_limit or whatnot.

**Comment by bobmcwhirter** [comment]
fwiw, reading over that RFC, I don't see the associated extension type constant for that extension, and it's only in the "proposed" state. I'm still happy to go with it if we can work out those details (and I'll also continue to emit max_fragment_length for those servers that support only it).

**Comment by ctz** [comment]
I don't think we should implement either of those extensions. There are two reasons for that opinion:

1. ecosystem implementation is patchy and broken. For example, mbedtls (very common device-side iot tls library) misimplements MaxFragmentLength so it is **not able to handshake** with a server that supports it^[1].  That is, like, obviously terrible and makes the extension a no-go. The other proposal is only that, and has no tlswg or common implementation backing.

2. you don't need it: in IoT you commonly control both ends for device-server communications, and can configure them to respect each other's limitations: this works -- at my day job we've shipped millions of iot devices using this approach.

[1]: https://github.com/ARMmbed/mbedtls/issues/387

**Comment by bobmcwhirter** [comment]
@ctz Thanks, I was unaware of (1) and do mostly agree with (2). 

Mostly this just caught me out when I moved from a Java-based TLS server to rustls, and noticed the lack of support for it, which caught me out initially.

No complaints from me if closed as WONTFIX.
