### ISSUE TITLE
Refactor quic submodule into `client::quic` and `server::quic`

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#586]
When reviewing PR #575 I noticed that lots of the implementation details of `ClientSession`/`ClientSessionImpl`, especially the fields, are `pub(crate)` or equivalent when they ideally wouldn't be. It seems like one of the biggest reasons for this is that the implementations of types in the `quic` module directly access those fields.

It seems to me like we should refactor the `quic` submodule so that there is a `client::quic` submodule for the client-specific parts and a `server::quic` submodule for the server-specific parts. This would allow us to encapsulate more of the client and server state better.

**Comment by djc** [comment]
Makes sense. I started drafting this for the client, but will wait to submit it until after #575 lands, otherwise rebasing it will just cause a lot of pain.
