### ISSUE TITLE
panic on client with message "No such file or directory"

### ISSUE THREAD

**Issue by yanns** [ctz/rustls#6]
Just tried the client locally:

```
./target/debug/examples/tlsclient --http mozilla-modern.badssl.com
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

the rust version:
```
rustc --version
rustc 1.10.0 (cfcb716cf 2016-07-03)
```

I am using mac.

**Comment by ctz** [comment]
See `--help`. The default for `--cafile` is `/etc/ssl/certs/ca-certificates.crt` which is only really sensible on Debian linux and derivatives.

A good new feature (probably in a crate of its own) would be something that knew how to access the root certificate stores on Windows, Mac and Linux.

In the meantime, you can download a suitable file to feed to `--cafile` here: https://curl.haxx.se/docs/caextract.html .

**Comment by yanns** [comment]
Thx for the answer.
It seems that there are no default CA installed on mac.

Because I already installed openssl, I could also use that one:
```
./target/debug/examples/tlsclient --http mozilla-modern.badssl.com --cafile /usr/local/etc/openssl/cert.pem
```

I suggest we can make the error message more helpful for the user here. I'll try to make a PR for that.
