### ISSUE TITLE
SNI with capital letter leads to TLS decryption error

### ISSUE THREAD

**Issue by Tuetuopay** [ctz/rustls#601]
An HTTP server that uses Rustls for https encryption gets completely confused by a client that sends a capital letter in the SNI field, even when rustls is configured to use a single certificate, which is documented to completely ignore the SNI.

This has been tested with a barebones H2 server (following example code) and with hyper-rustls's server example. The following of this issue will use hyper-rustls' example.

# Expectation

A request made to the server works regardless of the capitalization of the SNI:

```
 ~/hyper-rustls$ cargo run --example server &
   Compiling libc v0.2.92
---
   Compiling hyper-rustls v0.22.1 (/root/hyper-rustls)
    Finished dev [unoptimized + debuginfo] target(s) in 22.58s
     Running `target/debug/examples/server`
Starting to serve on https://127.0.0.1:1337.
 ~/hyper-rustls$ curl --insecure --http2-prior-knowledge -is https://localhost:1337
HTTP/2 200
date: Tue, 30 Mar 2021 13:18:44 GMT
content-length: 15

Try POST /echo
 ~/hyper-rustls$ curl --insecure --http2-prior-knowledge -is https://Localhost:1337
HTTP/2 200
date: Tue, 30 Mar 2021 13:18:44 GMT
content-length: 15

Try POST /echo
```

# Observed behaviour

```
 ~/hyper-rustls$ curl --insecure --http2-prior-knowledge -is https://Localhost:1337
[!] Voluntary server halt due to client-connection error...
FAILED: error accepting connection: TLS Error: Custom { kind: InvalidData, error: DecryptError }
Job 1, 'cargo run --example server &' has ended
```

If we enable verbose logging on the curl side, we can see that curl bails out right after receiving the server tls hello:

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x556d66b29fb0)
* Connected to Localhost (127.0.0.1) port 1337 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
*[!] Voluntary server halt due to client-connection error...
 TLSv1.3 (OUT), TLS alert, bad record mac (532):
* error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
* Closing connection 0
FAILED: error accepting connection: TLS Error: Custom { kind: InvalidData, error: DecryptError }
Job 1, 'cargo run --example server &' has ended
```

I am trying to troubleshoot the issue, but since I am not familiar at all with the rustls codebase, I have no idea what I'm doing...

# Usecase

Although this might look like a mistake to send capital letters in the SNI, this can be used in the gRPC world where the service name is sent in the SNI, e.g. `grpc.health.v1.Health` to help routing between various services (this is how I got the issue).

**Comment by djc** [comment]
It seems to me like the usage you're proposing is invalid per the spec. From [RFC 6066](https://tools.ietf.org/html/rfc6066#section-3):

```
struct {
          NameType name_type;
          select (name_type) {
              case host_name: HostName;
          } name;
      } ServerName;

      enum {
          host_name(0), (255)
      } NameType;

      opaque HostName<1..2^16-1>;

      struct {
          ServerName server_name_list<1..2^16-1>
      } ServerNameList;
```

and

```
"HostName" contains the fully qualified DNS hostname of the server,
   as understood by the client.  The hostname is represented as a byte
   string using ASCII encoding without a trailing dot.  This allows the
   support of internationalized domain names through the use of A-labels
   defined in [RFC5890].  DNS hostnames are case-insensitive.  The
   algorithm to compare hostnames is described in [RFC5890], Section
   2.3.2.4.
```

**Comment by djc** [comment]
Alright, I think I do agree that this is a bug. It looks like the decrypt error here happens because the transcript hashes for the handshakes from the client and the server are not the same. We update the transcript from a parsed and reencoded representation of incoming messages, and we normalize server names to lowercase as soon as they are parsed. In this case that means our transcript contains the lowercased version of the hostname, as evidenced by this test:

```rust
diff --git a/rustls/src/msgs/handshake_test.rs b/rustls/src/msgs/handshake_test.rs
index bfb938a..b66ef74 100644
--- a/rustls/src/msgs/handshake_test.rs
+++ b/rustls/src/msgs/handshake_test.rs
@@ -95,6 +95,17 @@ fn can_roundtrip_single_sni() {
     assert_eq!(bytes.to_vec(), ext.get_encoding());
 }
 
+#[test]
+fn can_round_trip_mixed_case_sni() {
+    let bytes = [0, 0, 0, 7, 0, 5, 0, 0, 2, 0x4c, 0x6f];
+    let mut rd = Reader::init(&bytes);
+    let ext = ClientExtension::read(&mut rd).unwrap();
+    println!("{:?}", ext);
+
+    assert_eq!(ext.get_type(), ExtensionType::ServerName);
+    assert_eq!(bytes.to_vec(), ext.get_encoding());
+}
+
 #[test]
 fn can_roundtrip_other_sni_name_types() {
     let bytes = [0, 0, 0, 7, 0, 5, 1, 0, 02, 0x6c, 0x6f];
```

**Comment by ctz** [comment]
Ah, good find. Introduced in 69407290, so was a regression in 0.12.

**Comment by Tuetuopay** [comment]
So if I'm getting this correctly, the issue then boils down to webpki's `try_from_ascii` [seen here](https://github.com/ctz/rustls/blob/main/rustls/src/msgs/handshake.rs#L254) automatically lowercase-ing the hostname, and this lowercased version being sent back to the client, hence producing an invalid handshake?

**Comment by ctz** [comment]
I think it's reasonable for webpki::DNSName to smash things to lower case, since that is always OK for DNS names.

But in TLS the two peers keep a transcript of all the messages, and feed a hash of their transcript into various key derivations and signature verifications (to detect any adversarial edits to messages). In this case the case smashing was being done inappropriately -- after parsing the message, but before putting it into the transcript.

**Comment by Tuetuopay** [comment]
Thanks for the great explanation and quick fix!
