### ISSUE TITLE
Ciphers supported for TLS1.2

### ISSUE THREAD

**Issue by ayoshi** [ctz/rustls#62]
I apologize for a naive question, I'm not a crypto expert. Looking at the list of all cipher suites:

```rust
pub static ALL_CIPHERSUITES: [&'static SupportedCipherSuite; 9] =
    [// TLS1.3 suites
     &TLS13_CHACHA20_POLY1305_SHA256,
     &TLS13_AES_256_GCM_SHA384,
     &TLS13_AES_128_GCM_SHA256,

     // TLS1.2 suites
     &TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
     &TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
     &TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
     &TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
     &TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
     &TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256];
```
I see that  AES_256_GCM_SHA384 and AES_128_GCM_SHA256 are not supported without Diffie-Helman for TLS1.2. Are those configurations insecure? openssl has those ciphers defined.

I encountered a problem trying to build a library working with syslog-ng over TLS, and it doesn't support DH ciphers, at least in OSE version. I could probably work around it with native-tls, not sure I like the idea though, and since there is no TLS13 in openssl (at least not in any common version) I can't switch syslog-ng to it either.

Is my only option going back to native-tls?

**Comment by ctz** [comment]
> Are those configurations insecure?

Yes, I would say that ciphersuites without forward secrecy (ie, something that uses DHE or ECDHE) are not suitable for use these days. For similar reasons, they are not supported in TLS1.3.

I don't plan to support these kinds of ciphersuites in rustls.
