### ISSUE TITLE
AEADTicketer::new_custom panics instead of returning an error when key is the wrong length

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#624]
```
    pub fn new_custom(
        alg: &'static aead::Algorithm,
        key: &[u8],
        lifetime_seconds: u32,
    ) -> AEADTicketer {
        let key = aead::UnboundKey::new(alg, key).unwrap();
```

Note that we refactored the `new()` function to return an error when the PRNG fails:
```
    pub fn new() -> Result<AEADTicketer, rand::GetRandomFailed> {
        let mut key = [0u8; 32];
        rand::fill_random(&mut key)?;
        Ok(AEADTicketer::new_custom(
            &aead::CHACHA20_POLY1305,
            &key,
            60 * 60 * 12,
        ))
    }
```

**Comment by ctz** [comment]
Perhaps `aead::Algorithm` could have an associated function that takes a `[u8; 32]` and returns an `aead::UnboundKey`? That'd make it infallible. In the meantime I'll remove `new_custom` as it's not used and not public.

**Comment by briansmith** [comment]
This was done in commit a2675ffe6c5319f7ceec87042b5cb35c96a8c812.

**Comment by briansmith** [comment]
> Perhaps `aead::Algorithm` could have an associated function that takes a `[u8; 32]` and returns an `aead::UnboundKey`? That'd make it infallible. In the meantime I'll remove `new_custom` as it's not used and not public.

That wouldn't work for AES-128-GCM because the array would need to be 16 bytes in that case. We could make a trait-based API for AEADs in *ring* but that would make the Rustls code more complicated.

**Comment by ctz** [comment]
Ah I had assumed `aead::Algorithm` was already a trait and `CHACHA20_POLY1305` was a struct that impl'd it. But I see it's not like that; fair enough.
