### ISSUE TITLE
How to expose negotiated connection state

### ISSUE THREAD

**Issue by djc** [ctz/rustls#630]
Currently, we keep around a number of bits of state in the `Connection` for the sole reason of allowing the API user to get at that state (for example, ALPN protocol, SNI, peer certificates). These are exposed using methods on `Session`/`ClientSession`/`ServerSession` which return `Option`: `None` until the value is available, `Some` after that point. In #606 we started duplicating some of this state to make it more accessible to the API, because the other copy is stored in the connection `State`, where it's not as easy to get to. In another branch, I had a similar strategy for the peer's certificate chain on the client side. In my view, a more efficient strategy (though perhaps somewhat harder to use for some users) would be not to keep this state around after rustls itself no longer needs it.

For example, one design could be that the `process_new_packets()` return value contains an `impl Iterator<Item = NegotiatedState>` with `enum NegotiatedState { Sni(Vec<u8>), Suite(&'static SupportedCipherSuite), Alpn(Vec<u8>), .. }`; the downstream users gets the value once and the onus to keep it around would be on them. This would make rustls sessions more efficient in terms of memory use and would also alleviate complexity resulting from the mismatch between handshake state and "temporal"  `Option` values in the session types.

**Comment by Ralith** [comment]
I like the sound of this from a high level. Life would be easier for downstream code if the yielded states were as monolithic as possible, i.e. if multiple values determined simultaneously by a single TLS message, keeping them bundled together into a single yielded struct.

**Comment by djc** [comment]
An API like this might also help with unifying the client/server APIs (#522).

**Comment by djc** [comment]
> Life would be easier for downstream code if the yielded states were as monolithic as possible, i.e. if multiple values determined simultaneously by a single TLS message, keeping them bundled together into a single yielded struct.

Given the current API, where reading/writing is separate from processing the packets, I think this would mean emitting a structure with all of the possible fields in it wrapped in `Option` after each call to `process_new_packets()`, which seems like an unattractive API to me. Why do you think this would make life easier compared to having something return the individual bits of state?

**Comment by ctz** [comment]
I'm not sure downstream users necessarily know _when_ they'll need to fetch these values, so having rustls emit them once means each downstream user need to store them anyway to plug that gap -- and that is churn without any net reduction in complexity.
