### ISSUE TITLE
would it be possible to have different configurations depending on the certificate?

### ISSUE THREAD

**Issue by Geal** [ctz/rustls#635]
very low priority, as I already have an alternative with openssl, but I'd like to see if it's feasible with rustls.

I host a lot of applications with SNI behind the sozu load balancer, and I have an issue where some clients would like different TLS options (like, restrict to TLS 1.3 or remove some ciphers) that may not make sense for others.

With openssl, it would be done by switching contexts depending on SNI in the client hello callback. In rustls I do not see a way to switch, and the documentation for [ServerConfig](https://docs.rs/rustls/0.19.0/rustls/struct.ServerConfig.html) states "Making one of these can be expensive, and should be once per process rather than once per connection".

Is my use case something that:
- would be possible with small changes
- requires large architecture changes
- is explicitely frowned upon :wink: 

(again, I'm not asking for implementation, just about feasibility)

**Comment by djc** [comment]
I think this would be covered by #89, can you take a look?

**Comment by djc** [comment]
Going to close this, since I think it's covered by #89. Feel free to reopen if you meant something else.
