### ISSUE TITLE
C bindings in the rustls repo

### ISSUE THREAD

**Issue by jsha** [ctz/rustls#671]
I've been working on C bindings for rustls over in https://github.com/abetterinternet/crustls/. I'd like to check in on how the rustls project would like the collaboration to work long-term. Do you want crustls incorporated into the rustls repo? If so, when is a good time to do that incorporation? We have one open style issue, a request to remove all type annotations (https://github.com/abetterinternet/crustls/issues/31), which I'm happy to do as part of the process.

I also wanted to check in on naming. Per https://github.com/abetterinternet/crustls/pull/41, `curl-rust` would like to depend on the rustls C binding as a crate. Would you like this crate to be named `crustls`, or would you prefer, e.g. `rustls-ffi`? And who would you like to be the owners of the crate?

To be clear, I intend to keep working on improving the C bindings, whichever repo they are in.

**Comment by djc** [comment]
Some things to consider:

1. Maintaining C APIs requires different kinds of expertise compared to maintaining Rust APIs, and putting code in the same repo might deter (casual?) contributors from making contributions if CI fails unless the C APIs get updated.
2. If the C API is successful, it's possible that end users of the C API outnumber end users of the Rust API.
3. There might be pressure on the Rust API to be easy to access in C, versus being idiomatic or maximally safe Rust.
4. Putting the C APIs in a separate repo might run the risk of making them somewhat second class citizens, even if just for the reason that updates to latest rustls are likely going to be done manually.
5. The C APIs being in a separate repository might make downstream integration harder.

I'm personally not that worried about (3), but (1) is making me think that a separate repo is maybe a better solution. In that case we should probably move it into the rustls GitHub org to make the connection clearer. I'm not sure whether (5) leads to any substantial issues, would be interested in more feedback on that.

I think rustls-ffi would be a fine name; the `-ffi` suffix seems to be in fairly common use.

**Comment by jsha** [comment]
> Maintaining C APIs requires different kinds of expertise compared to maintaining Rust APIs, and putting code in the same repo might deter (casual?) contributors from making contributions if CI fails unless the C APIs get updated.

If we do put the C bindings in the rustls repo, I think they should still depend on a specific version of rustls, to avoid this problem. So it should be possible for one person to submit a PR to the Rust side, and another person to come along later and update the C bindings if needed.

> There might be pressure on the Rust API to be easy to access in C, versus being idiomatic or maximally safe Rust.

A couple of concrete examples: https://github.com/abetterinternet/crustls/issues/81 and https://github.com/ctz/rustls/issues/438. So far we're planning to resolve these with thread locals.

> Putting the C APIs in a separate repo might run the risk of making them somewhat second class citizens, even if just for the reason that updates to latest rustls are likely going to be done manually.

Per my first response above, I think updates for the C bindings to use the latest rustls probably should happen manually, to avoid the "everyone needs to know both Rust and C" problem you describe (though we can tighten the cycle over time).

> The C APIs being in a separate repository might make downstream integration harder.

FWIW, when I wrote the curl integration, having a separate repository did not make the downstream integration harder.

**Comment by ctz** [comment]
I have loose preference for this to be in a separate repo inside the rustls org. At some point I'll move the main repo there too.

Rationale for that preference: 
- it feels like per-repo things (like CI settings) are wanting a slightly different approach (variety of compilers, platforms, etc.)
- I'd like to grep for 'unsafe' in the main repo and keep no hits :) (aside, of course, from `deny(unsafe)`)

**Comment by Ralith** [comment]
I think the strongest reason to use a single repo is so a cargo workspace can be used, which makes it much easier, but also obligatory, to update both sides simultaneously. It sounds like there's some desire to *not* require that they be updated in lockstep, in which case I'm not sure there's any advantage to a single repo.

**Comment by briansmith** [comment]
> If we do put the C bindings in the rustls repo, I think they should still depend on a specific version of rustls, to avoid this problem. So it should be possible for one person to submit a PR to the Rust side, and another person to come along later and update the C bindings if needed.

That's exactly the workflow I would like to see as well, and I think having separate repos would enable that workflow both more easily and more clearly.

**Comment by sayrer** [comment]
> 
> That's exactly the workflow I would like to see as well, and I think having separate repos would enable that workflow both more easily and more clearly.

I built crustls with Bazel, see: https://github.com/abetterinternet/crustls/issues/77#issuecomment-807820044. That would allow pinning the C API to specific rustc and rustls versions pretty easily. It would be easy to maintain that in the rustls org, but outside of the main rustls repo.

**Comment by djc** [comment]
This now lives in https://github.com/rustls/rustls-ffi. Closing.
