### ISSUE TITLE
Could we add an error type to pkcs8_private_keys function?

### ISSUE THREAD

**Issue by amouat** [ctz/rustls#675]
At the moment the function prototype is:

```
pub fn pkcs8_private_keys(rd: &mut dyn BufRead) -> Result<Vec<PrivateKey>, ()>
```

(From https://docs.rs/rustls/0.19.1/rustls/internal/pemfile/fn.pkcs8_private_keys.html)

I'm wondering why this doesn't have an explicit error type; I ended up having to do a `map_err` to deal with it.

I do note this is inside the "internal" API and there is now work on a rustls-pemfile project - should I be using that instead?

**Comment by djc** [comment]
Yes, you should probably be using that instead.

**Comment by amouat** [comment]
Thanks! That was a fast reply :)

**Comment by djc** [comment]
I'll close this for now. Feel free to reopen if you still think there's anything that could be improved here.
