### ISSUE TITLE
Impl for modifiable trusted server/client data store at runtime

### ISSUE THREAD

**Issue by textandfury** [ctz/rustls#689]
Because I'm faced with the requirement to modify trusted clients (by servers) and trusted servers (by clients) at runtime, I need to add impl's for the following traits:

1. `pub cert_resolver: Arc<dyn ResolvesServerCert>` in ServerConfig
2. `verifier: Arc<dyn verify::ClientCertVerifier>` in ServerConfig
3. `pub client_auth_cert_resolver: Arc<dyn ResolvesClientCert>` in ClientConfig
4. `verifier: Arc<dyn verify::ServerCertVerifier>` in ClientConfig

Do such impl's have a place in the main repo?

As a first example, I have added an impl for the `ResolvesServerCert` trait (albeit with a painfully long struct name).
Please refer to the following commit:
[https://github.com/textandfury/rustls/commit/bb67f1571e660ce30761926072b1b2287d929972](https://github.com/textandfury/rustls/commit/bb67f1571e660ce30761926072b1b2287d929972)

I can do impl's for (2), (3), and (4) immediately if I get an OK. Also please suggest appropriate struct names for such impl's .

Thanks

**Comment by djc** [comment]
This doesn't feel to me like something of broad enough interest that it's worth maintaining as part of this repository. If you feel it would be useful for other people, maybe publish them as a separate crate?

**Comment by textandfury** [comment]
No problem.
Closing.
