### ISSUE TITLE
Code coverage doesn't seem to instrument struct fields correctly

### ISSUE THREAD

**Issue by sayrer** [ctz/rustls#695]
I changed these allegedly uncovered fields to private and many things failed to build, including test-only files. From handshake_test.rs:

```
error[E0616]: field `hpke_kem_id` of struct `handshake::HpkeKeyConfig` is private
    --> rustls/src/msgs/handshake_test.rs:1234:39
     |
1234 |     assert_eq!(hkc.hpke_kem_id, hkc_2.hpke_kem_id);
     |                                       ^^^^^^^^^^^ private field
```

[Screen Shot 2021-05-13 at 6 30 40 PM](https://user-images.githubusercontent.com/253473/118207484-a2983c00-b419-11eb-9aed-776593ed4604.png)

**Comment by briansmith** [comment]
It's probably not codecov.io that's the problem; it's probably the coverage mechanism used by admin/coverage.

**Comment by sayrer** [comment]
> It's probably not codecov.io that's the problem; it's probably the coverage mechanism used by admin/coverage.

Fair enough, title edited.

**Comment by ctz** [comment]
Missing coverage on struct fields is from code generated by derive Debug or Clone. If important these can be trvially exercised in a test.

**Comment by sayrer** [comment]
Ok, that makes sense, just didn't want bigger patches to look poorly tested.

**Comment by sayrer** [comment]
Looks like it only requires Clone (just tested this).
