### ISSUE TITLE
Use Arc<RootCertStore> in ClientConfig and Allow*AuthenticatedClient

### ISSUE THREAD

**Issue by jsha** [ctz/rustls#704]
Related to conversation at https://github.com/abetterinternet/crustls/pull/98.

ClientConfig and ServerConfig both say: "Making one of these can be expensive, and should be once per process rather than once per connection." What we're finding in the curl and Apache work is that making just one ClientConfig or ServerConfig per process is not practical.

For curl, the curl API allows different TLS settings on a per-connection basis. So you might have one request that uses one group of settings, and another request that uses a different group of settings.

For Apache, we can't choose a CertifiedKey to respond with until after we've seen the ClientHello. The `Acceptor` API in https://github.com/ctz/rustls/issues/89 will solve part of that problem, and we're working around in the meantime. But in either case we wind up constructing a fresh ServerConfig for each connection.

I believe the expensive part of building a ServerConfig or a ClientConfig is primarily loading the RootCertStore. Is that right? If so, it makes sense to make RootCertStores shareable with an `Arc`, allowing ServerConfig and ClientConfig to be cheap to build.

/cc @icing

**Comment by djc** [comment]
I think this is a duplicate of #688, right?

**Comment by jsha** [comment]
Yep, thanks - I looked in the recent issues but should have done a search.
