### ISSUE TITLE
Significant heap growth with reqwest+rustls

### ISSUE THREAD

**Issue by darkprokoba** [ctz/rustls#712]
I'm observing significant heap growth when using reqwest to upload a large file to a remote HTTPS server. (I'm using reqwest 0.11.3 with rustls 0.22.1 to stream the payload in the body of a PUT request, I can provide code snippets, if needed)

The funny thing is, everything is fine when there's a gigabit link between the client and the server. But if I throttle the network between the client and the server to 1 mbit/sec, I'm seeing huge growth in the client heap. I've confirmed this with valgrind's massif tool. According to valgrind massif, on the client 99% of the heap seems to be allocated here: https://github.com/ctz/rustls/blob/rel-19-backports/rustls/src/session.rs#L725

I can provide massif output for both throttled and unthrottled network runs...

I've found out that there's a rustls::Session::set_buffer_limit() API. I'm not sure if is (a) safe to use in a reqwest+rustls async app and (b) would actually reduce the per-session heap allocations in the case described above (uploading a large file over a slow network).

Any help on this would be greatly appreciated.

**Comment by briansmith** [comment]
I filed issue #713 to change the default buffering so it isn't unlimited.

It sounds like your issue is that your application can produce data to send faster than it can be sent. At the same time, your application isn't getting backpressure from Rustls, or it is ignoring the backpressure and keeps trying to send data. Try setting the buffer size to a reasonable value for your application and then see how well it works. I don't think there should be any downside to doing this and in fact it seems to be mandatory for the reasons you state.

**Comment by darkprokoba** [comment]
reqwest uses rustls via the tokio-rustls crate, and it looks like it handles backpressure: https://github.com/tokio-rs/tls/blob/794659740dcc399f79058c4eba325ffd97474c7b/tokio-rustls/src/common/mod.rs#L270 (many thanks to @seanmonstar from the reqwest discord channel for pointing this out).

I've tried setting the limit to 1 MiB, performance dropped significantly, but the heap was still huge. The massif report looks different though. The offending allocations now happen in the hyper crate :-)

I'll try and back-port @djc 's changeset for setting the default limits to the rel-19-backports branch and see if it helps.

**Comment by darkprokoba** [comment]
I have forked the repo and applied djc's changeset to the rel-19-backports branch.
The situation has much improved, and I'll probably ship it like that (cargo [patch.crates-io] rocks)!
Do you feel this needs to be in the official repo's rel-19-backports branch?

**Comment by djc** [comment]
The reason I didn't propose that is that it might be a compatibility hazard, but maybe it makes sense to consider it a bug fix?
