### ISSUE TITLE
The default send buffer limit should not be unlimited

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#713]
The documentation for `set_buffer_limit()` says "By default, there is no limit. The limit can be set at any time, even if the current buffer use is higher."

This is not a safe default. It seems like it is pretty common (see #712) for users to get tripped up by this and then use massive amounts of memory. Given that we're changing the public API in this release, we should change it so that either the user must provide a buffer limit, or we should have a "safe" default.

**Comment by ctz** [comment]
> we should change it so that either the user must provide a buffer limit, or we should have a "safe" default.

agreed. i'd suggest something the order of 64KB to match a typical tcp send window.

**Comment by djc** [comment]
Currently we only set the limit on the `sendable_tls` and `sendable_plaintext` windows; should we also set a limit on the incoming application data buffer (`received_plaintext`)?0

**Comment by ctz** [comment]
> Currently we only set the limit on the `sendable_tls` and `sendable_plaintext` windows; should we also set a limit on the incoming application data buffer (`received_plaintext`)?

See https://github.com/ctz/rustls/blob/beef0be1658cd457d4f47039abf4f4bb37d59a78/rustls/src/server/mod.rs#L336-L342
