### ISSUE TITLE
Malformed Server Hello / BadDER

### ISSUE THREAD

**Issue by maufl** [ctz/rustls#72]
Hi, was trying to use rustls (tokio-rustls). However, I can not make the handshake work.
I generated a CA key/cert and a server key/cert using OpenSSL. To verify the problem I used the tlsclient and tlsserver example. Both the client and the server start correctly (i.e. read the certificate and key files), however, the client exits with a `WebPKIError(BadDER)` error and Wireshark shows an malformed Server Hello packet (for example, the version field is 0x00007f12).

I guess there might be a problem with the generated certificates/keys, I can attach them if you like. However, I would expect to get a error message when the file is read and not invalid TLS records.

**Comment by ctz** [comment]
> Wireshark shows an malformed Server Hello packet (for example, the version field is 0x00007f12

This is a valid version, it means TLS1.3 draft 18 has been negotiated. I guess wireshark can't decode that yet.

> I guess there might be a problem with the generated certificates/keys, I can attach them if you like. 

Yes please. At the very least the server side *should* do basic verification of its own certificate, rather than waiting for a client to find out via the protocol.

**Comment by maufl** [comment]
Then I guess I made a mistake somewhere when generating or using the certificates.

[ca.cert.txt](https://github.com/ctz/rustls/files/1033705/ca.cert.txt)
[ca.key.txt](https://github.com/ctz/rustls/files/1033703/ca.key.txt)
[server.cert.txt](https://github.com/ctz/rustls/files/1033704/server.cert.txt)
[server.key.txt](https://github.com/ctz/rustls/files/1033702/server.key.txt)

**Comment by maufl** [comment]
Pinning the version to TLS1.2 results in handshake messages Wireshark can decode.

**Comment by ctz** [comment]
The underlying problem is that your server certificate is version 1, which makes this very similar to https://github.com/briansmith/webpki/issues/47 . `test-ca/build-a-pki.sh` has sample openssl invocations to make suitable keys/certificates if you need a reference.
