### ISSUE TITLE
Refactor key share / HRR for easier testing

### ISSUE THREAD

**Issue by sayrer** [ctz/rustls#720]
It would be nice to easily test HRR by omitting a key share in the initial ClientHello. While working on ECH, I've hacked this like so:

```
    let key_share = if support_tls13 {
        None // Some(tls13::initial_key_share(&config, hostname)?)
    } else {
        None
    };
```

and then hacked `handle_hello_retry_request` so that it doesn't try to `unwrap()` here:

```
// We always send a key share when TLS 1.3 is enabled.
let offered_key_share = self.next.offered_key_share.unwrap();
```

Is there an easier way to trigger HRR? Even if there is, it might be nice to get rid of that unwrap.

**Comment by briansmith** [comment]
I'm not understanding. If you configure the server to not accept the key share type the client offers, you'll get an HRR, right?

**Comment by briansmith** [comment]
> Right, but I'm testing against Cloudflare's public server ("crypto.cloudflare.com"). It seems to support all of Rustls's key-exchange groups, so this is the only way I could get it to send a HRR.

I suggest in your WIP you just add an API to control this until we have a fully self-contained test suite for ECH. (BTW, I think BoGo is adding ECH tests.)

**Comment by sayrer** [comment]
OK, that sounds like a fine plan. Maybe some of that work will live on to remove that unwrap() call.
