### ISSUE TITLE
Support for SCT TLS extension

### ISSUE THREAD

**Issue by alex** [ctz/rustls#73]
It'd be great if there was a way to provide SCTs for serving as a part of the TLS handshake.

**Comment by ctz** [comment]
This should be done at the same time as OCSP stapling, because they're similar moving parts.

**Comment by ctz** [comment]
There's support for this on the ocsp branch now. ctz/sct.rs is a new crate to separate out SCT verification, and there'll be another crate along the lines of ctz/webpki-roots but for CT logs.
