### ISSUE TITLE
Handshake Failure When Going Through My Proxy Server

### ISSUE THREAD

**Issue by zicklag** [ctz/rustls#731]
For all HTTP traffic on my computer I must go through an HTTP proxy server. I notice that all Rust applications I use that are configured to use `rustls` always error with a `HandshakeFailure` error when trying to go through my proxy.

Looking around some of these issues it seems like it might be due to a lower-than-supported security configuration by my proxy server? Is there any way I can go about troubleshooting to figure out what exactly is the issue and how I might be able to get around it?

Essentially I end  up resorting to re-compiling all Rust programs that I use that use `rustls`, usually by turning off the `rustls` feature of `reqwest` or otherwise avoiding the Rust libraries that require it such as `ureq`, which is unfortunate.

I'd be glad to provide any extra information that might help, but I don't necessarily have easy access to my proxy server configuration directly so any info that I can collect remotely through http clients, etc. would be much easier to obtain.

**Comment by djc** [comment]
It seems likely that the issue here is the limited selection of cipher suites that rustls supports; rustls only supports cipher suites that enable forward secrecy, on versions 1.2 and 1.3 of the TLS protocol. I have no experience with this tool, but maybe it can help you find out more information: https://github.com/rbsec/sslscan/. Feel free to share your results here and I can take a look.

**Comment by zicklag** [comment]
Thanks for the link. I'll see if I can try that out.

Also, I just realized, my proxy server also uses a custom certificate that must be added to the system trust. Does `rustls` read the system certificate store? I know that can be a particularly difficult to do universally and all kinds of tools have different cert stores.

Would I get a different message than `HandshakeFailure` if it were a certificate issue?

**Comment by ctz** [comment]
> Would I get a different message than `HandshakeFailure` if it were a certificate issue?

Yes, something like `UnknownIssuer` typically.

**Comment by djc** [comment]
I don't think this is actionable at this point. Please feel free to re-open if you think there's something we should fix here.

**Comment by zicklag** [comment]
Oh yes, I forgot to close this! I looked into it and it does seem that it is caused by my proxy server not supporting any of the required ciphers. thanks for the help! :heart:
