### ISSUE TITLE
Error returns from write and read

### ISSUE THREAD

**Issue by jsha** [ctz/rustls#746]
Since Reader and Writer implement `io::Read` and `io::Write`, their `read()` and `write()` functions return a Result. However, they will never actually return an error because they are reading from internal buffers. Is it okay for downstream consumers to rely on this and ignore the possibility of an error return on `read()`?

For the specific case of `write()`, one can imagine reserving the possibility to return error in case of allocator failure, if we move to fallible allocation. Is that something this library is likely to do?

**Comment by briansmith** [comment]
You should assume something that returns a `Result` might fail.

I am hoping we'll redo many aspects of the buffering and I/O stuff to reduce buffer memory usage and copying, and I don't think it would be smart to promise read/write would never fail until that would be done.

**Comment by jsha** [comment]
Do you think implementing a method like `read_infallible()` on `Reader` is at all likely in the future?

**Comment by jsha** [comment]
Upon rereading the above, I realized the answer was clear. :-) Closing.
