### ISSUE TITLE
QUIC API should encapsulate key material

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#748]
Looking at the API, I see things like this:

```
pub struct PacketKey {
    /// Encrypts or decrypts a packet's payload
    pub key: aead::LessSafeKey,
    /// Computes unique nonces for each packet
    pub iv: Iv,
}
```

I don't think `key` and `iv` should be exposed publicly. Instead, I think we should have an API that looks like this:

```
    pub fn encrypt(&self, packet: u64, buf: &mut [u8], header_len: usize) {
        let (header, payload) = buf.split_at_mut(header_len);
        let (payload, tag_storage) =
            payload.split_at_mut(payload.len() - self.key.algorithm().tag_len());
        let aad = aead::Aad::from(header);
        let nonce = self.iv.nonce_for(packet);
        let tag = self
            .key
            .seal_in_place_separate_tag(nonce, aad, payload)
            .unwrap();
        tag_storage.copy_from_slice(tag.as_ref());
    }

    pub fn decrypt(
        &self,
        packet: u64,
        header: &[u8],
        payload: &mut BytesMut,
    ) -> Result<(), CryptoError> {
        if payload.len() < self.key.algorithm().tag_len() {
            return Err(CryptoError);
        }

        let payload_len = payload.len();
        let aad = aead::Aad::from(header);
        let nonce = self.iv.nonce_for(packet);
        self.key.open_in_place(nonce, aad, payload.as_mut())?;
        payload.truncate(payload_len - self.key.algorithm().tag_len());
        Ok(())
    }

    pub fn tag_len(&self) -> usize {
        self.key.algorithm().tag_len()
    }

    pub fn confidentiality_limit(&self) -> u64 {
        let cipher = self.key.algorithm();
        if cipher == &aead::AES_128_GCM || cipher == &aead::AES_256_GCM {
            2u64.pow(23)
        } else if cipher == &aead::CHACHA20_POLY1305 {
            u64::MAX
        } else {
            panic!("unknown cipher")
        }
    }

    pub fn integrity_limit(&self) -> u64 {
        let cipher = self.key.algorithm();
        if cipher == &aead::AES_128_GCM || cipher == &aead::AES_256_GCM {
            2u64.pow(52)
        } else if cipher == &aead::CHACHA20_POLY1305 {
            2u64.pow(36)
        } else {
            panic!("unknown cipher")
        }
    }
}
```

Note that I copy-pasted that directly out of quinn's rustls.rs. 

Basically, we should move the code from Quinn's rustls.rs that deals with *ring* types into Rustls's quic.rs, and remove all the APIs that expose *ring* types from Rustls's QUIC API.

This would ensure (1) We're minimizing how much key material is leaked outside of Rustls, improving security, and (2) we can upgrade *ring* to a new major version without it being a breaking API change.

**Comment by djc** [comment]
I'm open to moving the crypto stuff from Quinn into rustls. I think @ctz didn't want to have a bunch of QUIC-specific code in rustls, but maybe he has changed his mind on that/feels safer now that I'm helping out with maintenance?

**Comment by Ralith** [comment]
I'd be happy to upstream as much of that stuff as possible.

**Comment by briansmith** [comment]
> tls. I think @ctz didn't want to have a bunch of QUIC-specific code in rustls

I think what I'm suggesting moving from Quinn to Rustls is a very small amount of logic. Outside the crypto stuff, the QUIC-specific stuff would all stay outside of Rustls.

**Comment by Ralith** [comment]
Having the confidentiality/integrity limit lookup in rustls is a big footgun reduction, in particular, since it moves the decision to add support for negotiating new ciphers, and the code that must be updated as a consequence, into the same repo.
