### ISSUE TITLE
Provide socket-like API

### ISSUE THREAD

**Issue by stepancheg** [ctz/rustls#75]
E. g. similar to rust-native-tls:

```
let tcp_stream: TcpStream = ...;
let connector = ...; // which is called ClientConfig in rustls
let tls_stream: TlsStream<TcpStream> = connector.connect("github.com", tcp_stream);
// work with tls_stream as with `Read` and `Write`
```

**Comment by ctz** [comment]
I've done this, in two complementary parts:

- `complete_io` in the `Session` trait: this function does whatever IO the session currently needs using whatever transport you give it.
- a new `Stream` type which wraps up a `Session` and a transport, and implements blocking `io::Read` and `io::Write` traits on top of it

The first is intended to be generally useful, the second hopefully solves this bug. Let me know if not.

**Comment by Keruspe** [comment]
Fwiw, I just published https://docs.rs/rustls-connector/0.6.0/rustls_connector/ which wraps the above in an API similar to the ones from native-tls and openssl.
Not making the version number match rustls yet, until I've done some more testing
