### ISSUE TITLE
Enable weak cipersuites via configuration.

### ISSUE THREAD

**Issue by ArtBlnd** [ctz/rustls#754]
Some sites do only supports TLS 1.2 record layer. but seems rustls is sending TLS 1.0 record layer for all packets. is there are any way to change TLS record layer version via ClientConfig?

**Comment by ArtBlnd** [comment]
![image](https://user-images.githubusercontent.com/2209400/122975747-a6cb5800-d3ce-11eb-80e1-96443c2d813c.png)

**Comment by djc** [comment]
Wireshark is saying TLSv1, which I don't think necessarily implies 1.0? rustls only supports 1.2 and 1.3, and I think it will only ever send TLS v1.2 versioned records.

**Comment by ctz** [comment]
Here's what the standard (RFC8446) says for this:
```
   legacy_record_version:  MUST be set to 0x0303 for all records
      generated by a TLS 1.3 implementation other than an initial
      ClientHello (i.e., one not generated after a HelloRetryRequest),
      where it MAY also be 0x0301 for compatibility purposes.  This
      field is deprecated and MUST be ignored for all purposes.
```

I think we're following this, but if you want to experiment the code for this is here: https://github.com/ctz/rustls/blob/main/rustls/src/client/hs.rs#L386

It's much more likely that the server doesn't support something inside the ClientHello rather than the record version, though.

**Comment by ctz** [comment]
That server doesn't support any ciphersuites that are good options: see the "weak" labels on https://www.ssllabs.com/ssltest/analyze.html?d=lostark.game.onstove.com

**Comment by ArtBlnd** [comment]
Thanks for the investigate. is there are any way to enable **weak** ciphersuites on rustls manually? I know this is not good for security. but I just want to know.

**Comment by djc** [comment]
No, we don't support any weak cipher suites.

**Comment by ArtBlnd** [comment]
Thank you for the answer. closing issue.
