### ISSUE TITLE
EnabledVersions not exported

### ISSUE THREAD

**Issue by jsha** [ctz/rustls#757]
ServerConfig has a public field:

    pub versions: EnabledVersions,

And EnabledVersions is declared:

    pub struct EnabledVersions

But there's no pub use statement in lib.rs.

**Comment by briansmith** [comment]
I guess this means we either don't have tests for enabling the versions or the tests are not written as integration tests (under tests/). If we were to have an integration test under tests/ for this then the build would fail without this export.

**Comment by djc** [comment]
Most callers wouldn't touch the field directly because they would use the builder API.

**Comment by ctz** [comment]
I think exporting this type would mean the public API surface of it is included in the documentation, right?

(But, for the avoidance of doubt, it still wouldn't be a publicly constructible type: its `new()` is `pub(crate)` and its fields are private.)

**Comment by jsha** [comment]
Good to know. If the goal is that EnabledVersions cannot be touched outside of the Builder API, it probably makes more sense to make the `versions` field of ServerConfig / ClientConfig entirely private. For instance, in this generated documentation (https://hoffman-andrews.com/rustls/rustls/struct.ServerConfig.html), it shows `    pub versions: EnabledVersions,` but does not actually link to anything for `EnabledVersions` since it's not public.

This is somewhat related to #758: having a public field in ServerConfig / ClientConfig suggests that that field is user-modifiable or at least user-inspectable, and so when it is not, that is surprising.

**Comment by ctz** [comment]
This is now private and the tests that required it to be public have been refactored to use the builder interface.
