### ISSUE TITLE
Use newer version of LLVM in code coverage CI jobs

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#762]
In `.github/workflows/build.yml` we have:
```
      - name: Install dependencies
        run: sudo apt-get install llvm llvm-7 libclang-common-7-dev llvm-7-dev
```

llvm-7 is very old. Recent versions of Rust require clang-10 or higher to enable cross-language LTO and similar.

**Comment by briansmith** [comment]
Actually, right above that we're installing clang-12. So, probably we should just bump all those `-7` to `-12` to match.

**Comment by ctz** [comment]
I think this entire step might now be not required, now we install LLVM directly from the project.
