### ISSUE TITLE
Considering support ECC keys?

### ISSUE THREAD

**Issue by halldong** [ctz/rustls#767]
Currently I see only `rsa_private_keys` is supported on [doc page](https://docs.rs/rustls/0.19.1/rustls/internal/pemfile/index.html)

Is there any plan to support other type of encryption?

**Comment by djc** [comment]
pkcs8_private_keys() can handle other kinds of keys, should work for ECDSA keys if that's what you want.

**Comment by Darkspirit** [comment]
You need to convert keys of the format `-----BEGIN EC PRIVATE KEY-----` (EC private key in base64)
to the universal format `-----BEGIN PRIVATE KEY-----` (PKCS8 in base64):

https://wiki.openssl.org/index.php/Command_Line_Elliptic_Curve_Operations
$ openssl pkcs8 -topk8 -nocrypt -in before.pem -out after.pem

Then you can read the pkcs8 pem file with `pkcs8_private_keys()`.
