### ISSUE TITLE
Consider an enum that implements Connection

### ISSUE THREAD

**Issue by eloff** [ctz/rustls#775]
ClientConnection and ServerConnection are different types, and I needed an abstraction over both of them. At first I implemented a Transport struct with generic T: Connection. However, this caused the ClientConnection and ServerConnection types to propagate throughout much of the code that used the Transport type, because the calling code now also had to be generic. This also meant I wouldn't be able to make a future version that used a different TLS library, because I had rustls types propogating everywhere in the generic constraints.

One workaround is to use `Box<dyn Connection>`, but I didn't want the extra allocation, extra indirection, and vtable lookup overhead.

So I created an enum to combine the two: https://gist.github.com/eloff/f82c3e08133d233c395b5e64680f66b4

This allows me to use Connection methods with only the match overhead, which should be slightly better than the vtable lookup overhead, but I won't have the memory allocation or extra indirection of the `Box<dyn Connection>`. When I need a ClientConnection or a ServerConnection it's then trivial to get them with the enum, e.g. to do the handshake.

I think it would be useful to have it fully implement the Connection interface and have it in rustls itself. I'm probably not the only person with a need to use both the client and server tls, anyone implementing a proxy would have that same requirement.

**Comment by djc** [comment]
I think this is a duplicate of https://github.com/ctz/rustls/issues/522?

**Comment by eloff** [comment]
@djc Yes, it's a duplicate of that issue. I'll post a link to this issue there, and close this.
