### ISSUE TITLE
Replace `WebPkiError`/`WebPkiOp` with a more general mechanism

### ISSUE THREAD

**Issue by briansmith** [ctz/rustls#782]
There are three issues with `WebPkiError` I see immediately:

1. `WebPkiError` is a straight copy of webpki's `Error` type, but the licensing of `WebPkiError` seems vaguely wrong. Note that `webpki` and `Rustls` have different licenses. Unless we're planning to only ship Rustls under the ISC license, which I doubt. Regardless, the attribution is also missing.

2. The definition of `WebPkiError` is very brittle. It basically assumes that webpki will do error reporting much like its present `Error` type. However, I think in the future details of how webpki returns errors, and which errors are returned in which circumstances, will change. This brittleness will be too hard to deal with when updating the version of webpki used in Rustls.

2. When implementing an alternative certificate verifier that isn't implemented in terms of webpki, the only choices are to map the errors to webpki Errors or to map them to a string and use `GeneralError`. Mapping to `WebPkiError` is difficult/impossible/error-prone for similar reasons as (2) above. Using `GeneralError` works but it's too...general.

Concerns similar to (2) and (3) also apply to the design of WebPkiOp, which I think I noted at the time it was proposed.

I propose instead we:

1. Add variant `Error::InvalidCertificate(Cow<'static, str>)` or similar that is like `GeneralError` but which allows users to more easily differentiate certificate errors from other kinds of errors.
2. Remove `WebPkiError` and `WebPkiOp`.

**Comment by djc** [comment]
Your plan makes sense to me.

**Comment by briansmith** [comment]
> I propose that we add distinct `InvalidServerCert`/`InvalidClientCert`

I think it would make more sense to have `InvalidPeerCert` as a single error, since our goal is to make clients and servers uniform.

Otherwise, I agree with your idea.

**Comment by djc** [comment]
Sounds okay to me.

**Comment by djc** [comment]
Do you want to implement this, or would you like me to? If the latter, I can probably get it done on Wednesday.

**Comment by lygstate** [comment]
`pki_error` doesn't exported
