### ISSUE TITLE
Protocol state should use a typed representation

### ISSUE THREAD

**Issue by nbraud** [ctz/rustls#81]
AFAICT, the state of the TLS session is currently represented in a way that would allow the implementation to access/set data at inappropriate times in the protocol.  Such state machine issues have lead to severe vulnerabilities such as [CCS Injection](http://ccsinjection.lepidum.co.jp/blog/2014-06-05/CCS-Injection-en/index.html), [`goto fail`](https://www.imperialviolet.org/2014/02/22/applebug.html), [SMACK](https://mitls.org/pages/attacks/SMACK), and [many others](https://www.usenix.org/system/files/conference/usenixsecurity15/sec15-paper-de-ruiter.pdf).

Indeed, the handshake implementation acts directly on the session state (in [`SessionCommon`](https://github.com/ctz/rustls/blob/master/src/session.rs#L248-L268), `{Client,Server}HandshakeData`, ...), implicitely relying on the implementation correctly setting fields to `None` or `Some(_)` depending on the protocol phase, instead of using a more constrained type that prevents having fields inconsistent with the protocol state.

This can be implemented in several ways in Rust with low to no overhead, incl. using [session types](http://munksgaard.me/papers/munksgaard-laumann-thesis.pdf), and [experiences in other languages](https://usenix15.nqsb.io/) strongly suggest that this can prevent many issues.

I have started working on this, but I'm opening the issue so other people may comment (or take this up if I cannot find the time/energy to finish).  It seems to be a pretty major refactoring effort, though.

**Comment by ctz** [comment]
Yes, I agree with this. It's something I've wanted to do for a while. The other thing I wanted to gain from this was separation of each state function (ex. `handle_server_hello`) so it can be unit-tested separately from   any other state.

**Comment by ctz** [comment]
I've given this an initial pass. It's not totally comprehensive at this point, but feedback is appreciated all the same.

**Comment by ctz** [comment]
I'm happy with how this turned out.

**Comment by nbraud** [comment]
@ctz Oops, sorry for the issue going dead.

Life and medical badness happened and I was unable to contribute anything here, but I'm glad you did it anyhow  :)
I will try to go through it and review at some point in the future  :3
