### ISSUE TITLE
Bump ring to 0.11

### ISSUE THREAD

**Issue by SergioBenitez** [ctz/rustls#86]
`rustls` is presently unusable with up-to-date libraries due to `ring` version incompatibilities. Please update the `ring` dependency to `0.11`. You will also need to update the `webpki` dependency to `0.14` and `webpki-roots` to `0.11`, which first needs to exist (https://github.com/ctz/webpki-roots/pull/9). You may also wish to update `base64` to `0.6`.

**Comment by ctz** [comment]
0.9 published. Sorry for the inconvenience!
