### ISSUE TITLE
rustls chooses "ECDSA_NISTP256_SHA256" as the signature scheme, but is unable to sign messages that way

### ISSUE THREAD

**Issue by wfraser** [ctz/rustls#88]
Background, which may or may not be relevant: I'm attempting to implement a library that works with Syncthing, which uses TLS with client auth. It doesn't use a regular chain of trust, but instead each side knows in advance and checks what is essentially a hash of the certificates used.

I'm using a 2048-bit RSA client certificate (RSA is all that rustls currently supports for client certs?).

I'm hitting a panic in `rustls::client_hs::emit_certverify` where there's this block:
```
        let encoding: &signature::RSAEncoding = match scheme {
            SignatureScheme::RSA_PKCS1_SHA256 => &signature::RSA_PKCS1_SHA256,
            SignatureScheme::RSA_PKCS1_SHA384 => &signature::RSA_PKCS1_SHA384,
            SignatureScheme::RSA_PKCS1_SHA512 => &signature::RSA_PKCS1_SHA512,
            SignatureScheme::RSA_PSS_SHA256 => &signature::RSA_PSS_SHA256,
            SignatureScheme::RSA_PSS_SHA384 => &signature::RSA_PSS_SHA384,
            SignatureScheme::RSA_PSS_SHA512 => &signature::RSA_PSS_SHA512,
            _ => return Err(()),
        };
```

However, earlier in the handshake, rustls decided to do this:
```
INFO:rustls::client_hs: Got CertificateRequest CertificateRequestPayload { certtypes: [RSASign, ECDSASign], sigschemes: [RSA_PKCS1_SHA256, ECDSA_NISTP256_SHA256, RSA_PKCS1_SHA384, ECDSA_NISTP384_SHA384, RSA_PKCS1_SHA1, ECDSA_SHA1_Legacy], canames: [] }
INFO:rustls::client_hs: Attempting client auth, will use ECDSA_NISTP256_SHA256
```

Basically it picked a sig scheme that it doesn't actually support. Why didn't `RSA_PKCS1_SHA256` get chosen?

The backtrace of the panic is:
```
thread 'main' panicked at 'client auth signing failed unexpectedly: ()', src/libcore/result.rs:860
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <core::result::Result<T, E>>::expect
  10: rustls::client_hs::emit_certverify
  11: rustls::client_hs::handle_server_hello_done
  12: rustls::client::ClientSessionImpl::process_main_protocol
  13: rustls::client::ClientSessionImpl::process_new_handshake_messages
  14: rustls::client::ClientSessionImpl::process_msg
  15: rustls::client::ClientSessionImpl::process_new_packets
  16: <rustls::client::ClientSession as rustls::session::Session>::process_new_packets
  17: [my code from here down]
```

**Comment by wfraser** [comment]
As a side gripe, I wish it didn't panic in this situation, and also wish that `RSASigner::sign` returned something other than `()` for its error type. I had to use a debugger to figure out what was going on because the only log message is `client auth signing failed unexpectedly: ()` 👎

**Comment by ctz** [comment]
Thanks for the report, and sorry for this defect. This is fixed on master now, with a regression test.

I'll have a look at eliminating some of the panics here later.

**Comment by wfraser** [comment]
Hey, thanks! I updated to master and it's working great!

**Comment by ctz** [comment]
I've now made this bug structurally impossible in the type system.
