### ISSUE TITLE
tlsserver example not working on OCSP commits

### ISSUE THREAD

**Issue by moderation** [ctz/rustls#90]
I was previously able to run a standalone tlsserver prior to the OCSP commits at https://github.com/ctz/rustls/commits/master/examples/tlsserver.rs. This was tested against Firefox Nightly and Chrome Beta on Linux. This is using valid Lets Encrypt certificates.

Using a fresh clone of the full rustls repo and running `cargo run --release --verbose --example tlsserver -- --certs ~/Library/letsencrypt/cert.pem --key ~/Library/letsencrypt/rsa_key.pem --verbose -p 10443 http` successfully compiles the test server and runs it.

When trying to connect Chrome Beta to https://localhost:10443 the following error is returned - https://gist.github.com/moderation/23029dccdae58b02368efcf8750b11c5

**Comment by ctz** [comment]
Hm, I can't reproduce this (similar set-up -- on rustls.jbp.io -- with either chrome beta or firefox nightly). The handshake looks very similar. It's very strange that its happening on both TLS1.3 and TLS1.2 too.

**Comment by moderation** [comment]
I finally figured this out. I had not regenerated the RSA key from the Let's Encrypt keys for use with rustls with `openssl rsa -in privkey.pem -out rsa_key.pem`. Working fine now. Closing.
