### ISSUE TITLE
`complete_io` does not appear to send error alerts

### ISSUE THREAD

**Issue by univerio** [ctz/rustls#91]
_(See quininer/tokio-rustls#12)_

When a fatal error occurs, such as when TLS 1.2 is not supported by the client, or when the server fails to resolves an appropriate certificate, `complete_io` appears to close the connection abruptly, without sending the error alert, even though `process_new_packets` queues up such a message.

Is it safe to call `write_tls` after an error occurs in `process_new_packets`? Is this a simple oversight in `complete_io`?

**Comment by ctz** [comment]
Thanks for the report. Fixed in 9f1b9b3
