### ISSUE TITLE
Webpki no matching version in crates.io

### ISSUE THREAD

**Issue by TheCynosure** [ctz/rustls#98]
Error Here:

error: no matching version `^0.2.1` found for package `webpki` (required by `rustls`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.16.0, 0.15.0, 0.14.0, ...

I am trying to use the v0.1 crate for rustls.

**Comment by ctz** [comment]
0.1 is an awfully old version. Did you really mean to use it?

**Comment by TheCynosure** [comment]
Looking at the error now I believe it is rustls that is trying to download the v0.1. I will submit an issue there as well.

**Comment by TheCynosure** [comment]
This is the version that is downloaded by the rustls crate. I am not linking to this crate in my Cargo.toml. Instead I thought this was something that rustls required.

**Comment by ctz** [comment]
I mean the version of rustls. v0.1 is the very first version, which worked but only barely. v0.10 is the latest.

**Comment by TheCynosure** [comment]
I deleted my Cargo.toml and retried the whole process. It worked this time, must have had the version wrong. Thank you for all the help.
